version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - nilerr
    - errorlint

  settings:
    errorlint:
      errorf: true
      asserts: true
      comparison: true

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/fetburner/rokuban
