/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Rokuban API
 * Cloud-native recording server API
 * OpenAPI spec version: 0.0.1
 */
import * as zod from 'zod';

/**
 * @summary Health check
 */
export const HealthzResponse = zod.object({
  "status": zod.string()
})


/**
 * **ロードバランサ（k8s の Service）向けの readiness 専用**。DB への
 * ping が通れば 200、通らなければ 503 を返す。
 *
 * `/healthz`（liveness）とは目的が違うので分けている。liveness に依存
 * チェックを入れると DB の瞬断で全 Pod が同時に再起動する（回復を待つ
 * べき状況で、回復を最も妨げる挙動）。一方 readiness で DB を見ないと、
 * DB に繋がっていない Pod に Service がトラフィックを振る窓が開く。
 *
 * **見るのは DB への ping だけで、mirakc への到達性は見ない**（不変条件
 * 1「api ロールは mirakc に問い合わせない」。ハイブリッド構成では
 * クラウド側 api から mirakc に到達できないのが正常状態）。
 *
 * `/healthz` / `/metrics` と同じく Host allowlist を免除する
 * （probe は Pod IP で叩くので allowlist に載せようがない）。
 *
 * **`/metrics` と違ってこの spec に載せる**のは、JSON を返す
 * リクエスト/レスポンスの契約であり、`/healthz` と同じ形だから
 * （`/metrics` は Prometheus の text exposition format なので載せない）。
 * フロントから呼ぶ面ではないので、生成クライアントの readyz は使われない。
 * @summary Readiness check (DB ping)
 */
export const ReadyzResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Get server version
 */
export const GetVersionResponse = zod.object({
  "version": zod.string()
})


/**
 * **オプション機能の導線を出してよいかをフロントが判断するための公開面**
 * （issue #209）。フロントは config を読めない（api ロールは設定ファイルを
 * 配らない。不変条件 1）ため、`live.enabled` のように「無効なら導線ごと
 * 消したい」設定は API で観測できる必要がある。
 *
 * **設定値そのものではなく「導線を出してよいか」だけを返す。** 返すのは
 * 真偽値だけで、config のキー名・値・ffmpeg のパス・プロファイル定義は
 * 載せない（`GET /api/encode-profiles` / `GET /api/sites` と同じ規律）。
 *
 * **機能が「有効」であることは「今すぐ使える」ことを意味しない。**
 * `live: true` はこのデプロイの config が `live.enabled: true` である
 * ことだけを表し、streamer ロールが実際に動いている / チューナーが空いて
 * いることは表さない（後者はプレイリスト取得の 404 / 503 として出る。
 * docs/frontend/live.md）。
 * @summary Report which optional features this deployment has enabled
 */
export const GetCapabilitiesResponse = zod.object({
  "live": zod.boolean().describe('ライブ視聴（`live.enabled`）が有効か。false のときフロントは\nライブへの導線（主ナビ・番組行のリンク等）を出さない。\n')
}).describe('オプション機能のフラグ集合。\*\*すべてのフィールドを required にする\*\* ---\n欠けた項目を「未対応の古いサーバー」として扱うか「無効」として扱うかを\nフロント側で判断させると、判断が導線ごとにばらける。足すときは既定値を\nサーバー側で必ず埋める。\n')


/**
 * `config.mirakc`/`mirakcs` レジストリの公開面（issue #184 M4-12）。api は
 * site に束縛されない（不変条件 1）ため、フロントが正しい `{site}` を
 * パスに埋めるにはこの一覧が要る（旧 `web/src/lib/site.ts` の
 * `DEFAULT_SITE` 決め打ちを撤去する対応）。
 *
 * **機微情報は載せない。** mirakc の URL は返さない（site 名の配列のみ。
 * `GET /api/encode-profiles` が ffmpeg のパス等を出さないのと同じ規律）。
 * @summary List the mirakc sites this deployment knows about
 */
export const ListSitesResponseItem = zod.string()
export const ListSitesResponse = zod.array(ListSitesResponseItem)


/**
 * `config.encode.profiles` に定義されたプロファイルの公開面。UI が
 * ルール / overrides の `encodeProfiles` を選ぶために使う（M3-6 / issue #68）。
 *
 * **機微情報は載せない。** ffmpeg のパスや extra_args は出さない。
 * 名前（と表示用の container）だけを返す。
 * @summary List configured encode profile names
 */
export const ListEncodeProfilesResponseItem = zod.object({
  "name": zod.string().describe('ルール \/ overrides の `encodeProfiles` が参照する名前。\nconfig.encode.profiles[].name と一致する。\n'),
  "container": zod.enum(['mp4', 'mkv']).optional().describe('出力コンテナ（表示用。未注入なら省略）。\n')
})
export const ListEncodeProfilesResponse = zod.array(ListEncodeProfilesResponseItem)


/**
 * @summary List recording rules
 */
export const listRulesResponseOneEnabledDefault = true;
export const listRulesResponseOnePriorityDefault = 10;
export const listRulesResponseOneTextMatchesItemCaseSensitiveDefault = false;
export const listRulesResponseOneTextMatchesItemNegateDefault = false;
export const listRulesResponseOneGenresItemMin = 0;
export const listRulesResponseOneGenresItemMax = 15;

export const listRulesResponseOneTimesItemWeekdaysMax = 127;

export const listRulesResponseOneTimesItemStartSecMin = 0;
export const listRulesResponseOneTimesItemStartSecMax = 86400;

export const listRulesResponseOneTimesItemEndSecMin = 0;
export const listRulesResponseOneTimesItemEndSecMax = 86400;

export const listRulesResponseOneDedupeEnabledDefault = false;
export const listRulesResponseOneDedupeThresholdExclusiveMin = 0;
export const listRulesResponseOneDedupeThresholdMax = 1;

export const listRulesResponseOneDedupeWindowSecondsExclusiveMin = 0;

export const listRulesResponseOneKeepOriginalDefault = `always`;

export const ListRulesResponseItem = zod.object({
  "name": zod.string(),
  "description": zod.string().optional(),
  "enabled": zod.boolean().default(listRulesResponseOneEnabledDefault),
  "priority": zod.number().default(listRulesResponseOnePriorityDefault),
  "isFree": zod.boolean().nullish().describe('null = 問わない'),
  "durationMinMs": zod.number().nullish(),
  "durationMaxMs": zod.number().nullish(),
  "periodStartAt": zod.string().datetime({"offset":true}).nullish(),
  "periodEndAt": zod.string().datetime({"offset":true}).nullish(),
  "textMatches": zod.array(zod.object({
  "target": zod.enum(['name', 'description', 'extended']),
  "mode": zod.enum(['keyword', 'regex']).describe('keyword = 部分一致 \/ regex = POSIX ARE'),
  "value": zod.string(),
  "caseSensitive": zod.boolean().default(listRulesResponseOneTextMatchesItemCaseSensitiveDefault),
  "negate": zod.boolean().default(listRulesResponseOneTextMatchesItemNegateDefault).describe('true なら除外条件')
})).optional(),
  "services": zod.array(zod.object({
  "networkId": zod.number(),
  "serviceId": zod.number()
})).optional(),
  "channelTypes": zod.array(zod.enum(['GR', 'BS', 'CS', 'SKY'])).optional(),
  "genres": zod.array(zod.number().min(listRulesResponseOneGenresItemMin).max(listRulesResponseOneGenresItemMax)).optional().describe('genre lv1'),
  "times": zod.array(zod.object({
  "weekdays": zod.number().min(1).max(listRulesResponseOneTimesItemWeekdaysMax).describe('bit0=月 … bit6=日'),
  "startSec": zod.number().min(listRulesResponseOneTimesItemStartSecMin).max(listRulesResponseOneTimesItemStartSecMax),
  "endSec": zod.number().min(listRulesResponseOneTimesItemEndSecMin).max(listRulesResponseOneTimesItemEndSecMax).describe('start より小さい場合は翌日跨ぎ')
})).optional(),
  "sites": zod.array(zod.string()).optional().describe('空または省略 = 全サイト。指定する各要素は GET \/api\/sites が返す既知の site 名でなければならず、レジストリに無い名前（タイポ含む）や空文字列は 400 になる。更新では、そのルールに既に保存されている site 名だけは既知として扱う（GET で得た sites を載せ直す更新が、レジストリから site が消えた後も通るように）。免除は更新対象のルール単位なので \*\*作成では効かない\*\* —— 既存ルールの sites をそのまま載せて別のルールを作る（フォーク）場合、レジストリから消えた site 名は 400 になる。`POST \/api\/sites\/{site}\/programs\/search` の `sites` も同じ「空または省略 = 全サイト」の軸規約を使うが、一回限りの問い合わせで 保存された行を持たないため、既知名検証と更新時の免除はルールの保存にのみ 適用される。'),
  "dedupeEnabled": zod.boolean().default(listRulesResponseOneDedupeEnabledDefault),
  "dedupeThreshold": zod.number().gt(listRulesResponseOneDedupeThresholdExclusiveMin).max(listRulesResponseOneDedupeThresholdMax).nullish().describe('pg_trgm の similarity() と比較する閾値。similarity() の値域は [0, 1] なので\nこの範囲外は無意味。0 を許すと similarity() >= 0 が常に真になり、finished の\n録画が 1 本でもあれば以降の全番組が重複扱いで黙ってスキップされる\n（録画が黙って止まる）。1 を超えると常に偽になり、重複排除が黙って無効化される。\n'),
  "dedupeWindowSeconds": zod.number().gt(listRulesResponseOneDedupeWindowSecondsExclusiveMin).nullish().describe('重複排除の時間窓（秒）。interval の API 表現。省略（null）が「時間窓なし」で、\n0 はその意味にはならない。0 以下を許すと\n`program_start_at >= now() - window` が現在以降の開始時刻を要求する形になり、\n比較対象は必ず過去の放送なので常に偽（重複排除が黙って無効化される）。\n'),
  "keepOriginal": zod.enum(['always', 'until_encoded']).default(listRulesResponseOneKeepOriginalDefault),
  "encodeProfiles": zod.array(zod.string()).optional(),
  "filenameTemplate": zod.string().optional(),
  "metadata": zod.record(zod.string(), zod.unknown()).optional()
}).and(zod.object({
  "id": zod.number(),
  "createdAt": zod.string().datetime({"offset":true}),
  "updatedAt": zod.string().datetime({"offset":true})
}))
export const ListRulesResponse = zod.array(ListRulesResponseItem)


/**
 * @summary Create a recording rule
 */
export const createRuleBodyEnabledDefault = true;
export const createRuleBodyPriorityDefault = 10;
export const createRuleBodyTextMatchesItemCaseSensitiveDefault = false;
export const createRuleBodyTextMatchesItemNegateDefault = false;
export const createRuleBodyGenresItemMin = 0;
export const createRuleBodyGenresItemMax = 15;

export const createRuleBodyTimesItemWeekdaysMax = 127;

export const createRuleBodyTimesItemStartSecMin = 0;
export const createRuleBodyTimesItemStartSecMax = 86400;

export const createRuleBodyTimesItemEndSecMin = 0;
export const createRuleBodyTimesItemEndSecMax = 86400;

export const createRuleBodyDedupeEnabledDefault = false;
export const createRuleBodyDedupeThresholdExclusiveMin = 0;
export const createRuleBodyDedupeThresholdMax = 1;

export const createRuleBodyDedupeWindowSecondsExclusiveMin = 0;

export const createRuleBodyKeepOriginalDefault = `always`;

export const CreateRuleBody = zod.object({
  "name": zod.string(),
  "description": zod.string().optional(),
  "enabled": zod.boolean().default(createRuleBodyEnabledDefault),
  "priority": zod.number().default(createRuleBodyPriorityDefault),
  "isFree": zod.boolean().nullish().describe('null = 問わない'),
  "durationMinMs": zod.number().nullish(),
  "durationMaxMs": zod.number().nullish(),
  "periodStartAt": zod.string().datetime({"offset":true}).nullish(),
  "periodEndAt": zod.string().datetime({"offset":true}).nullish(),
  "textMatches": zod.array(zod.object({
  "target": zod.enum(['name', 'description', 'extended']),
  "mode": zod.enum(['keyword', 'regex']).describe('keyword = 部分一致 \/ regex = POSIX ARE'),
  "value": zod.string(),
  "caseSensitive": zod.boolean().default(createRuleBodyTextMatchesItemCaseSensitiveDefault),
  "negate": zod.boolean().default(createRuleBodyTextMatchesItemNegateDefault).describe('true なら除外条件')
})).optional(),
  "services": zod.array(zod.object({
  "networkId": zod.number(),
  "serviceId": zod.number()
})).optional(),
  "channelTypes": zod.array(zod.enum(['GR', 'BS', 'CS', 'SKY'])).optional(),
  "genres": zod.array(zod.number().min(createRuleBodyGenresItemMin).max(createRuleBodyGenresItemMax)).optional().describe('genre lv1'),
  "times": zod.array(zod.object({
  "weekdays": zod.number().min(1).max(createRuleBodyTimesItemWeekdaysMax).describe('bit0=月 … bit6=日'),
  "startSec": zod.number().min(createRuleBodyTimesItemStartSecMin).max(createRuleBodyTimesItemStartSecMax),
  "endSec": zod.number().min(createRuleBodyTimesItemEndSecMin).max(createRuleBodyTimesItemEndSecMax).describe('start より小さい場合は翌日跨ぎ')
})).optional(),
  "sites": zod.array(zod.string()).optional().describe('空または省略 = 全サイト。指定する各要素は GET \/api\/sites が返す既知の site 名でなければならず、レジストリに無い名前（タイポ含む）や空文字列は 400 になる。更新では、そのルールに既に保存されている site 名だけは既知として扱う（GET で得た sites を載せ直す更新が、レジストリから site が消えた後も通るように）。免除は更新対象のルール単位なので \*\*作成では効かない\*\* —— 既存ルールの sites をそのまま載せて別のルールを作る（フォーク）場合、レジストリから消えた site 名は 400 になる。`POST \/api\/sites\/{site}\/programs\/search` の `sites` も同じ「空または省略 = 全サイト」の軸規約を使うが、一回限りの問い合わせで 保存された行を持たないため、既知名検証と更新時の免除はルールの保存にのみ 適用される。'),
  "dedupeEnabled": zod.boolean().default(createRuleBodyDedupeEnabledDefault),
  "dedupeThreshold": zod.number().gt(createRuleBodyDedupeThresholdExclusiveMin).max(createRuleBodyDedupeThresholdMax).nullish().describe('pg_trgm の similarity() と比較する閾値。similarity() の値域は [0, 1] なので\nこの範囲外は無意味。0 を許すと similarity() >= 0 が常に真になり、finished の\n録画が 1 本でもあれば以降の全番組が重複扱いで黙ってスキップされる\n（録画が黙って止まる）。1 を超えると常に偽になり、重複排除が黙って無効化される。\n'),
  "dedupeWindowSeconds": zod.number().gt(createRuleBodyDedupeWindowSecondsExclusiveMin).nullish().describe('重複排除の時間窓（秒）。interval の API 表現。省略（null）が「時間窓なし」で、\n0 はその意味にはならない。0 以下を許すと\n`program_start_at >= now() - window` が現在以降の開始時刻を要求する形になり、\n比較対象は必ず過去の放送なので常に偽（重複排除が黙って無効化される）。\n'),
  "keepOriginal": zod.enum(['always', 'until_encoded']).default(createRuleBodyKeepOriginalDefault),
  "encodeProfiles": zod.array(zod.string()).optional(),
  "filenameTemplate": zod.string().optional(),
  "metadata": zod.record(zod.string(), zod.unknown()).optional()
})

export const createRuleResponseOneEnabledDefault = true;
export const createRuleResponseOnePriorityDefault = 10;
export const createRuleResponseOneTextMatchesItemCaseSensitiveDefault = false;
export const createRuleResponseOneTextMatchesItemNegateDefault = false;
export const createRuleResponseOneGenresItemMin = 0;
export const createRuleResponseOneGenresItemMax = 15;

export const createRuleResponseOneTimesItemWeekdaysMax = 127;

export const createRuleResponseOneTimesItemStartSecMin = 0;
export const createRuleResponseOneTimesItemStartSecMax = 86400;

export const createRuleResponseOneTimesItemEndSecMin = 0;
export const createRuleResponseOneTimesItemEndSecMax = 86400;

export const createRuleResponseOneDedupeEnabledDefault = false;
export const createRuleResponseOneDedupeThresholdExclusiveMin = 0;
export const createRuleResponseOneDedupeThresholdMax = 1;

export const createRuleResponseOneDedupeWindowSecondsExclusiveMin = 0;

export const createRuleResponseOneKeepOriginalDefault = `always`;

export const CreateRuleResponse = zod.object({
  "name": zod.string(),
  "description": zod.string().optional(),
  "enabled": zod.boolean().default(createRuleResponseOneEnabledDefault),
  "priority": zod.number().default(createRuleResponseOnePriorityDefault),
  "isFree": zod.boolean().nullish().describe('null = 問わない'),
  "durationMinMs": zod.number().nullish(),
  "durationMaxMs": zod.number().nullish(),
  "periodStartAt": zod.string().datetime({"offset":true}).nullish(),
  "periodEndAt": zod.string().datetime({"offset":true}).nullish(),
  "textMatches": zod.array(zod.object({
  "target": zod.enum(['name', 'description', 'extended']),
  "mode": zod.enum(['keyword', 'regex']).describe('keyword = 部分一致 \/ regex = POSIX ARE'),
  "value": zod.string(),
  "caseSensitive": zod.boolean().default(createRuleResponseOneTextMatchesItemCaseSensitiveDefault),
  "negate": zod.boolean().default(createRuleResponseOneTextMatchesItemNegateDefault).describe('true なら除外条件')
})).optional(),
  "services": zod.array(zod.object({
  "networkId": zod.number(),
  "serviceId": zod.number()
})).optional(),
  "channelTypes": zod.array(zod.enum(['GR', 'BS', 'CS', 'SKY'])).optional(),
  "genres": zod.array(zod.number().min(createRuleResponseOneGenresItemMin).max(createRuleResponseOneGenresItemMax)).optional().describe('genre lv1'),
  "times": zod.array(zod.object({
  "weekdays": zod.number().min(1).max(createRuleResponseOneTimesItemWeekdaysMax).describe('bit0=月 … bit6=日'),
  "startSec": zod.number().min(createRuleResponseOneTimesItemStartSecMin).max(createRuleResponseOneTimesItemStartSecMax),
  "endSec": zod.number().min(createRuleResponseOneTimesItemEndSecMin).max(createRuleResponseOneTimesItemEndSecMax).describe('start より小さい場合は翌日跨ぎ')
})).optional(),
  "sites": zod.array(zod.string()).optional().describe('空または省略 = 全サイト。指定する各要素は GET \/api\/sites が返す既知の site 名でなければならず、レジストリに無い名前（タイポ含む）や空文字列は 400 になる。更新では、そのルールに既に保存されている site 名だけは既知として扱う（GET で得た sites を載せ直す更新が、レジストリから site が消えた後も通るように）。免除は更新対象のルール単位なので \*\*作成では効かない\*\* —— 既存ルールの sites をそのまま載せて別のルールを作る（フォーク）場合、レジストリから消えた site 名は 400 になる。`POST \/api\/sites\/{site}\/programs\/search` の `sites` も同じ「空または省略 = 全サイト」の軸規約を使うが、一回限りの問い合わせで 保存された行を持たないため、既知名検証と更新時の免除はルールの保存にのみ 適用される。'),
  "dedupeEnabled": zod.boolean().default(createRuleResponseOneDedupeEnabledDefault),
  "dedupeThreshold": zod.number().gt(createRuleResponseOneDedupeThresholdExclusiveMin).max(createRuleResponseOneDedupeThresholdMax).nullish().describe('pg_trgm の similarity() と比較する閾値。similarity() の値域は [0, 1] なので\nこの範囲外は無意味。0 を許すと similarity() >= 0 が常に真になり、finished の\n録画が 1 本でもあれば以降の全番組が重複扱いで黙ってスキップされる\n（録画が黙って止まる）。1 を超えると常に偽になり、重複排除が黙って無効化される。\n'),
  "dedupeWindowSeconds": zod.number().gt(createRuleResponseOneDedupeWindowSecondsExclusiveMin).nullish().describe('重複排除の時間窓（秒）。interval の API 表現。省略（null）が「時間窓なし」で、\n0 はその意味にはならない。0 以下を許すと\n`program_start_at >= now() - window` が現在以降の開始時刻を要求する形になり、\n比較対象は必ず過去の放送なので常に偽（重複排除が黙って無効化される）。\n'),
  "keepOriginal": zod.enum(['always', 'until_encoded']).default(createRuleResponseOneKeepOriginalDefault),
  "encodeProfiles": zod.array(zod.string()).optional(),
  "filenameTemplate": zod.string().optional(),
  "metadata": zod.record(zod.string(), zod.unknown()).optional()
}).and(zod.object({
  "id": zod.number(),
  "createdAt": zod.string().datetime({"offset":true}),
  "updatedAt": zod.string().datetime({"offset":true})
}))


/**
 * @summary Get a recording rule
 */
export const GetRuleParams = zod.object({
  "id": zod.number()
})

export const getRuleResponseOneEnabledDefault = true;
export const getRuleResponseOnePriorityDefault = 10;
export const getRuleResponseOneTextMatchesItemCaseSensitiveDefault = false;
export const getRuleResponseOneTextMatchesItemNegateDefault = false;
export const getRuleResponseOneGenresItemMin = 0;
export const getRuleResponseOneGenresItemMax = 15;

export const getRuleResponseOneTimesItemWeekdaysMax = 127;

export const getRuleResponseOneTimesItemStartSecMin = 0;
export const getRuleResponseOneTimesItemStartSecMax = 86400;

export const getRuleResponseOneTimesItemEndSecMin = 0;
export const getRuleResponseOneTimesItemEndSecMax = 86400;

export const getRuleResponseOneDedupeEnabledDefault = false;
export const getRuleResponseOneDedupeThresholdExclusiveMin = 0;
export const getRuleResponseOneDedupeThresholdMax = 1;

export const getRuleResponseOneDedupeWindowSecondsExclusiveMin = 0;

export const getRuleResponseOneKeepOriginalDefault = `always`;

export const GetRuleResponse = zod.object({
  "name": zod.string(),
  "description": zod.string().optional(),
  "enabled": zod.boolean().default(getRuleResponseOneEnabledDefault),
  "priority": zod.number().default(getRuleResponseOnePriorityDefault),
  "isFree": zod.boolean().nullish().describe('null = 問わない'),
  "durationMinMs": zod.number().nullish(),
  "durationMaxMs": zod.number().nullish(),
  "periodStartAt": zod.string().datetime({"offset":true}).nullish(),
  "periodEndAt": zod.string().datetime({"offset":true}).nullish(),
  "textMatches": zod.array(zod.object({
  "target": zod.enum(['name', 'description', 'extended']),
  "mode": zod.enum(['keyword', 'regex']).describe('keyword = 部分一致 \/ regex = POSIX ARE'),
  "value": zod.string(),
  "caseSensitive": zod.boolean().default(getRuleResponseOneTextMatchesItemCaseSensitiveDefault),
  "negate": zod.boolean().default(getRuleResponseOneTextMatchesItemNegateDefault).describe('true なら除外条件')
})).optional(),
  "services": zod.array(zod.object({
  "networkId": zod.number(),
  "serviceId": zod.number()
})).optional(),
  "channelTypes": zod.array(zod.enum(['GR', 'BS', 'CS', 'SKY'])).optional(),
  "genres": zod.array(zod.number().min(getRuleResponseOneGenresItemMin).max(getRuleResponseOneGenresItemMax)).optional().describe('genre lv1'),
  "times": zod.array(zod.object({
  "weekdays": zod.number().min(1).max(getRuleResponseOneTimesItemWeekdaysMax).describe('bit0=月 … bit6=日'),
  "startSec": zod.number().min(getRuleResponseOneTimesItemStartSecMin).max(getRuleResponseOneTimesItemStartSecMax),
  "endSec": zod.number().min(getRuleResponseOneTimesItemEndSecMin).max(getRuleResponseOneTimesItemEndSecMax).describe('start より小さい場合は翌日跨ぎ')
})).optional(),
  "sites": zod.array(zod.string()).optional().describe('空または省略 = 全サイト。指定する各要素は GET \/api\/sites が返す既知の site 名でなければならず、レジストリに無い名前（タイポ含む）や空文字列は 400 になる。更新では、そのルールに既に保存されている site 名だけは既知として扱う（GET で得た sites を載せ直す更新が、レジストリから site が消えた後も通るように）。免除は更新対象のルール単位なので \*\*作成では効かない\*\* —— 既存ルールの sites をそのまま載せて別のルールを作る（フォーク）場合、レジストリから消えた site 名は 400 になる。`POST \/api\/sites\/{site}\/programs\/search` の `sites` も同じ「空または省略 = 全サイト」の軸規約を使うが、一回限りの問い合わせで 保存された行を持たないため、既知名検証と更新時の免除はルールの保存にのみ 適用される。'),
  "dedupeEnabled": zod.boolean().default(getRuleResponseOneDedupeEnabledDefault),
  "dedupeThreshold": zod.number().gt(getRuleResponseOneDedupeThresholdExclusiveMin).max(getRuleResponseOneDedupeThresholdMax).nullish().describe('pg_trgm の similarity() と比較する閾値。similarity() の値域は [0, 1] なので\nこの範囲外は無意味。0 を許すと similarity() >= 0 が常に真になり、finished の\n録画が 1 本でもあれば以降の全番組が重複扱いで黙ってスキップされる\n（録画が黙って止まる）。1 を超えると常に偽になり、重複排除が黙って無効化される。\n'),
  "dedupeWindowSeconds": zod.number().gt(getRuleResponseOneDedupeWindowSecondsExclusiveMin).nullish().describe('重複排除の時間窓（秒）。interval の API 表現。省略（null）が「時間窓なし」で、\n0 はその意味にはならない。0 以下を許すと\n`program_start_at >= now() - window` が現在以降の開始時刻を要求する形になり、\n比較対象は必ず過去の放送なので常に偽（重複排除が黙って無効化される）。\n'),
  "keepOriginal": zod.enum(['always', 'until_encoded']).default(getRuleResponseOneKeepOriginalDefault),
  "encodeProfiles": zod.array(zod.string()).optional(),
  "filenameTemplate": zod.string().optional(),
  "metadata": zod.record(zod.string(), zod.unknown()).optional()
}).and(zod.object({
  "id": zod.number(),
  "createdAt": zod.string().datetime({"offset":true}),
  "updatedAt": zod.string().datetime({"offset":true})
}))


/**
 * @summary Update a recording rule
 */
export const UpdateRuleParams = zod.object({
  "id": zod.number()
})

export const updateRuleBodyEnabledDefault = true;
export const updateRuleBodyPriorityDefault = 10;
export const updateRuleBodyTextMatchesItemCaseSensitiveDefault = false;
export const updateRuleBodyTextMatchesItemNegateDefault = false;
export const updateRuleBodyGenresItemMin = 0;
export const updateRuleBodyGenresItemMax = 15;

export const updateRuleBodyTimesItemWeekdaysMax = 127;

export const updateRuleBodyTimesItemStartSecMin = 0;
export const updateRuleBodyTimesItemStartSecMax = 86400;

export const updateRuleBodyTimesItemEndSecMin = 0;
export const updateRuleBodyTimesItemEndSecMax = 86400;

export const updateRuleBodyDedupeEnabledDefault = false;
export const updateRuleBodyDedupeThresholdExclusiveMin = 0;
export const updateRuleBodyDedupeThresholdMax = 1;

export const updateRuleBodyDedupeWindowSecondsExclusiveMin = 0;

export const updateRuleBodyKeepOriginalDefault = `always`;

export const UpdateRuleBody = zod.object({
  "name": zod.string(),
  "description": zod.string().optional(),
  "enabled": zod.boolean().default(updateRuleBodyEnabledDefault),
  "priority": zod.number().default(updateRuleBodyPriorityDefault),
  "isFree": zod.boolean().nullish().describe('null = 問わない'),
  "durationMinMs": zod.number().nullish(),
  "durationMaxMs": zod.number().nullish(),
  "periodStartAt": zod.string().datetime({"offset":true}).nullish(),
  "periodEndAt": zod.string().datetime({"offset":true}).nullish(),
  "textMatches": zod.array(zod.object({
  "target": zod.enum(['name', 'description', 'extended']),
  "mode": zod.enum(['keyword', 'regex']).describe('keyword = 部分一致 \/ regex = POSIX ARE'),
  "value": zod.string(),
  "caseSensitive": zod.boolean().default(updateRuleBodyTextMatchesItemCaseSensitiveDefault),
  "negate": zod.boolean().default(updateRuleBodyTextMatchesItemNegateDefault).describe('true なら除外条件')
})).optional(),
  "services": zod.array(zod.object({
  "networkId": zod.number(),
  "serviceId": zod.number()
})).optional(),
  "channelTypes": zod.array(zod.enum(['GR', 'BS', 'CS', 'SKY'])).optional(),
  "genres": zod.array(zod.number().min(updateRuleBodyGenresItemMin).max(updateRuleBodyGenresItemMax)).optional().describe('genre lv1'),
  "times": zod.array(zod.object({
  "weekdays": zod.number().min(1).max(updateRuleBodyTimesItemWeekdaysMax).describe('bit0=月 … bit6=日'),
  "startSec": zod.number().min(updateRuleBodyTimesItemStartSecMin).max(updateRuleBodyTimesItemStartSecMax),
  "endSec": zod.number().min(updateRuleBodyTimesItemEndSecMin).max(updateRuleBodyTimesItemEndSecMax).describe('start より小さい場合は翌日跨ぎ')
})).optional(),
  "sites": zod.array(zod.string()).optional().describe('空または省略 = 全サイト。指定する各要素は GET \/api\/sites が返す既知の site 名でなければならず、レジストリに無い名前（タイポ含む）や空文字列は 400 になる。更新では、そのルールに既に保存されている site 名だけは既知として扱う（GET で得た sites を載せ直す更新が、レジストリから site が消えた後も通るように）。免除は更新対象のルール単位なので \*\*作成では効かない\*\* —— 既存ルールの sites をそのまま載せて別のルールを作る（フォーク）場合、レジストリから消えた site 名は 400 になる。`POST \/api\/sites\/{site}\/programs\/search` の `sites` も同じ「空または省略 = 全サイト」の軸規約を使うが、一回限りの問い合わせで 保存された行を持たないため、既知名検証と更新時の免除はルールの保存にのみ 適用される。'),
  "dedupeEnabled": zod.boolean().default(updateRuleBodyDedupeEnabledDefault),
  "dedupeThreshold": zod.number().gt(updateRuleBodyDedupeThresholdExclusiveMin).max(updateRuleBodyDedupeThresholdMax).nullish().describe('pg_trgm の similarity() と比較する閾値。similarity() の値域は [0, 1] なので\nこの範囲外は無意味。0 を許すと similarity() >= 0 が常に真になり、finished の\n録画が 1 本でもあれば以降の全番組が重複扱いで黙ってスキップされる\n（録画が黙って止まる）。1 を超えると常に偽になり、重複排除が黙って無効化される。\n'),
  "dedupeWindowSeconds": zod.number().gt(updateRuleBodyDedupeWindowSecondsExclusiveMin).nullish().describe('重複排除の時間窓（秒）。interval の API 表現。省略（null）が「時間窓なし」で、\n0 はその意味にはならない。0 以下を許すと\n`program_start_at >= now() - window` が現在以降の開始時刻を要求する形になり、\n比較対象は必ず過去の放送なので常に偽（重複排除が黙って無効化される）。\n'),
  "keepOriginal": zod.enum(['always', 'until_encoded']).default(updateRuleBodyKeepOriginalDefault),
  "encodeProfiles": zod.array(zod.string()).optional(),
  "filenameTemplate": zod.string().optional(),
  "metadata": zod.record(zod.string(), zod.unknown()).optional()
})

export const updateRuleResponseOneEnabledDefault = true;
export const updateRuleResponseOnePriorityDefault = 10;
export const updateRuleResponseOneTextMatchesItemCaseSensitiveDefault = false;
export const updateRuleResponseOneTextMatchesItemNegateDefault = false;
export const updateRuleResponseOneGenresItemMin = 0;
export const updateRuleResponseOneGenresItemMax = 15;

export const updateRuleResponseOneTimesItemWeekdaysMax = 127;

export const updateRuleResponseOneTimesItemStartSecMin = 0;
export const updateRuleResponseOneTimesItemStartSecMax = 86400;

export const updateRuleResponseOneTimesItemEndSecMin = 0;
export const updateRuleResponseOneTimesItemEndSecMax = 86400;

export const updateRuleResponseOneDedupeEnabledDefault = false;
export const updateRuleResponseOneDedupeThresholdExclusiveMin = 0;
export const updateRuleResponseOneDedupeThresholdMax = 1;

export const updateRuleResponseOneDedupeWindowSecondsExclusiveMin = 0;

export const updateRuleResponseOneKeepOriginalDefault = `always`;

export const UpdateRuleResponse = zod.object({
  "name": zod.string(),
  "description": zod.string().optional(),
  "enabled": zod.boolean().default(updateRuleResponseOneEnabledDefault),
  "priority": zod.number().default(updateRuleResponseOnePriorityDefault),
  "isFree": zod.boolean().nullish().describe('null = 問わない'),
  "durationMinMs": zod.number().nullish(),
  "durationMaxMs": zod.number().nullish(),
  "periodStartAt": zod.string().datetime({"offset":true}).nullish(),
  "periodEndAt": zod.string().datetime({"offset":true}).nullish(),
  "textMatches": zod.array(zod.object({
  "target": zod.enum(['name', 'description', 'extended']),
  "mode": zod.enum(['keyword', 'regex']).describe('keyword = 部分一致 \/ regex = POSIX ARE'),
  "value": zod.string(),
  "caseSensitive": zod.boolean().default(updateRuleResponseOneTextMatchesItemCaseSensitiveDefault),
  "negate": zod.boolean().default(updateRuleResponseOneTextMatchesItemNegateDefault).describe('true なら除外条件')
})).optional(),
  "services": zod.array(zod.object({
  "networkId": zod.number(),
  "serviceId": zod.number()
})).optional(),
  "channelTypes": zod.array(zod.enum(['GR', 'BS', 'CS', 'SKY'])).optional(),
  "genres": zod.array(zod.number().min(updateRuleResponseOneGenresItemMin).max(updateRuleResponseOneGenresItemMax)).optional().describe('genre lv1'),
  "times": zod.array(zod.object({
  "weekdays": zod.number().min(1).max(updateRuleResponseOneTimesItemWeekdaysMax).describe('bit0=月 … bit6=日'),
  "startSec": zod.number().min(updateRuleResponseOneTimesItemStartSecMin).max(updateRuleResponseOneTimesItemStartSecMax),
  "endSec": zod.number().min(updateRuleResponseOneTimesItemEndSecMin).max(updateRuleResponseOneTimesItemEndSecMax).describe('start より小さい場合は翌日跨ぎ')
})).optional(),
  "sites": zod.array(zod.string()).optional().describe('空または省略 = 全サイト。指定する各要素は GET \/api\/sites が返す既知の site 名でなければならず、レジストリに無い名前（タイポ含む）や空文字列は 400 になる。更新では、そのルールに既に保存されている site 名だけは既知として扱う（GET で得た sites を載せ直す更新が、レジストリから site が消えた後も通るように）。免除は更新対象のルール単位なので \*\*作成では効かない\*\* —— 既存ルールの sites をそのまま載せて別のルールを作る（フォーク）場合、レジストリから消えた site 名は 400 になる。`POST \/api\/sites\/{site}\/programs\/search` の `sites` も同じ「空または省略 = 全サイト」の軸規約を使うが、一回限りの問い合わせで 保存された行を持たないため、既知名検証と更新時の免除はルールの保存にのみ 適用される。'),
  "dedupeEnabled": zod.boolean().default(updateRuleResponseOneDedupeEnabledDefault),
  "dedupeThreshold": zod.number().gt(updateRuleResponseOneDedupeThresholdExclusiveMin).max(updateRuleResponseOneDedupeThresholdMax).nullish().describe('pg_trgm の similarity() と比較する閾値。similarity() の値域は [0, 1] なので\nこの範囲外は無意味。0 を許すと similarity() >= 0 が常に真になり、finished の\n録画が 1 本でもあれば以降の全番組が重複扱いで黙ってスキップされる\n（録画が黙って止まる）。1 を超えると常に偽になり、重複排除が黙って無効化される。\n'),
  "dedupeWindowSeconds": zod.number().gt(updateRuleResponseOneDedupeWindowSecondsExclusiveMin).nullish().describe('重複排除の時間窓（秒）。interval の API 表現。省略（null）が「時間窓なし」で、\n0 はその意味にはならない。0 以下を許すと\n`program_start_at >= now() - window` が現在以降の開始時刻を要求する形になり、\n比較対象は必ず過去の放送なので常に偽（重複排除が黙って無効化される）。\n'),
  "keepOriginal": zod.enum(['always', 'until_encoded']).default(updateRuleResponseOneKeepOriginalDefault),
  "encodeProfiles": zod.array(zod.string()).optional(),
  "filenameTemplate": zod.string().optional(),
  "metadata": zod.record(zod.string(), zod.unknown()).optional()
}).and(zod.object({
  "id": zod.number(),
  "createdAt": zod.string().datetime({"offset":true}),
  "updatedAt": zod.string().datetime({"offset":true})
}))


/**
 * 導出予約の整理を伴う。overrides のない rule 予約は削除し、
 * overrides 付きは detached 化して生き残る（recording.md §4.3）。
 * 応答に影響内訳を載せる。
 * @summary Delete a recording rule
 */
export const DeleteRuleParams = zod.object({
  "id": zod.number()
})

export const DeleteRuleResponse = zod.object({
  "id": zod.number(),
  "deletedReservations": zod.number().describe('overrides なしで削除した rule 予約の件数'),
  "detachedReservations": zod.number().describe('overrides 付きで detached 化した件数')
})


/**
 * 導出結果の読み取り専用ビュー（issue #29）。書き込みは
 * `PUT/DELETE /api/sites/{site}/programs/{programId}/intent` と
 * `PATCH/DELETE /api/sites/{site}/programs/{programId}/overrides` で行う
 * —— `reservations` の書き手は ruler だけであり、api はここを一切書かない。
 *
 * **全サイトの予約を返す**（issue #184 M4-12）。各要素の `site` で区別する。
 * 絞り込みパラメータは持たない（不変条件 11: 必要になった時点で足す）。
 * @summary List reservations
 */
export const ListReservationsResponseItem = zod.object({
  "id": zod.number(),
  "site": zod.string().describe('この予約がどのサイト（mirakc インスタンス）のものか。`reservations.site`\nそのままで、設定ファイルで定義されたサイト名（docs\/schema.md §1-5）。\n\nチューナー容量超過の判定はサイトごとに独立しているため\n（docs\/data.md §6.5）、予約一覧のバッジはこの値と超過区間の site を\n突き合わせる。M1\/M2 は単一サイト構成なので実質 `default` 固定だが、\n\*\*クライアントに定数を持たせない\*\*（他サイトの不足を自分の不足として\n出す形で静かに壊れるのを避ける）。\n'),
  "programId": zod.number(),
  "source": zod.enum(['rule', 'manual']).describe('導出値であり、reservations テーブルの列ではない（issue #26）。\nユーザーが録れと指定した番組（program_intents に action=record の行が\nある）なら manual、無ければ rule。ルールが今まさにこの予約に\nbase を供給しているか（ruleId の有無）とは無関係で、手動予約に\nルールがマッチしていても manual のまま変わらない。\n'),
  "ruleId": zod.number().optional(),
  "state": zod.enum(['active', 'detached', 'orphaned']),
  "overrides": zod.object({

}).passthrough().optional(),
  "title": zod.string(),
  "serviceName": zod.string().describe('番組スナップショット（program_snapshots.service_name）由来のチャンネル\n表示名。同じタイトルが日付・局違いで並ぶと区別できないため（issue #302）、\nrecordings と同じ形でここにも載せる。\n'),
  "channelType": zod.enum(['GR', 'BS', 'CS', 'SKY']).describe('予約時点のスナップショット（program_snapshots 由来）。\n'),
  "startAt": zod.string().datetime({"offset":true}),
  "durationMs": zod.number(),
  "createdAt": zod.string().datetime({"offset":true}),
  "updatedAt": zod.string().datetime({"offset":true}),
  "skip": zod.boolean().describe('effective.skip（M2-6, issue #24）。program_intents.action=\'skip\' の\n明示、または意図が無く base.skip（ルールの重複排除判定）が true。\ntrue の間 reconciler は mirakc に同期しないが、予約行自体は\n「なぜ録られていないか」を説明するため残る。\n'),
  "dedupMatchRecordingId": zod.number().optional().describe('履歴ベース重複排除でマッチした録画の ID（マッチが無ければ省略）'),
  "dedupSimilarity": zod.number().optional().describe('上記マッチの pg_trgm 類似度（0.0〜1.0、マッチが無ければ省略）')
})
export const ListReservationsResponse = zod.array(ListReservationsResponseItem)


/**
 * `(site, programId)` を宛先に予約を読む（issue #99）。`reservations.id` は
 * ruler の導出削除・再実体化で変わりうる不安定な値なので、UI の
 * ディープリンク・クエリキャッシュのような恒久的な資源同定には使わない。
 *
 * `UNIQUE (site, program_id)` が既に張られているため、このキーで一意に
 * 予約が定まる。予約行が再実体化されて `id` が変わっても、この URL・
 * クエリキーは変わらない —— ブックマーク・共有した URL、TanStack Query の
 * クエリキャッシュが再実体化を生き延びる（#98 で recordings.reservation_id /
 * 放送イベントの識別について踏んだのと同じ形の identity の問題。CLAUDE.md
 * 不変条件 9「導出器が作るキーを宛先にしない」）。
 *
 * 指定した番組に対する予約が無ければ 404（`reservations` に行が無い、
 * または site が設定と一致しない）。
 * @summary Get the reservation for a program, keyed by (site, programId)
 */
export const GetProgramReservationParams = zod.object({
  "site": zod.string().describe('mirakc インスタンスのサイト名。programId はインスタンス単位のスコープ\nしか持たないため、この site と組にしないと資源が一意に定まらない\n（issue #31）。api プロセス自身は特定の site に束縛されない\n（不変条件 1: mirakc にもファイルシステムにも依存しない）ので、権威は\n「`config.mirakc`\/`mirakcs` レジストリに存在するか」であり、1 プロセスが\nレジストリの全 site を処理できる（issue #184 M4-12）。レジストリに無い\nsite のエラーコードはエンドポイントの HTTP メソッドで決まる —— GET 系は\n404、POST\/PUT\/PATCH\/DELETE 系は 400（他の入力検証と同じ扱い。詳細は各\nエンドポイントの description・レスポンス定義を参照）。存在する site の\n一覧は `GET \/api\/sites` で取得できる。\n'),
  "programId": zod.number()
})

export const GetProgramReservationResponse = zod.object({
  "id": zod.number(),
  "site": zod.string().describe('この予約がどのサイト（mirakc インスタンス）のものか。`reservations.site`\nそのままで、設定ファイルで定義されたサイト名（docs\/schema.md §1-5）。\n\nチューナー容量超過の判定はサイトごとに独立しているため\n（docs\/data.md §6.5）、予約一覧のバッジはこの値と超過区間の site を\n突き合わせる。M1\/M2 は単一サイト構成なので実質 `default` 固定だが、\n\*\*クライアントに定数を持たせない\*\*（他サイトの不足を自分の不足として\n出す形で静かに壊れるのを避ける）。\n'),
  "programId": zod.number(),
  "source": zod.enum(['rule', 'manual']).describe('導出値であり、reservations テーブルの列ではない（issue #26）。\nユーザーが録れと指定した番組（program_intents に action=record の行が\nある）なら manual、無ければ rule。ルールが今まさにこの予約に\nbase を供給しているか（ruleId の有無）とは無関係で、手動予約に\nルールがマッチしていても manual のまま変わらない。\n'),
  "ruleId": zod.number().optional(),
  "state": zod.enum(['active', 'detached', 'orphaned']),
  "overrides": zod.object({

}).passthrough().optional(),
  "title": zod.string(),
  "serviceName": zod.string().describe('番組スナップショット（program_snapshots.service_name）由来のチャンネル\n表示名。同じタイトルが日付・局違いで並ぶと区別できないため（issue #302）、\nrecordings と同じ形でここにも載せる。\n'),
  "channelType": zod.enum(['GR', 'BS', 'CS', 'SKY']).describe('予約時点のスナップショット（program_snapshots 由来）。\n'),
  "startAt": zod.string().datetime({"offset":true}),
  "durationMs": zod.number(),
  "createdAt": zod.string().datetime({"offset":true}),
  "updatedAt": zod.string().datetime({"offset":true}),
  "skip": zod.boolean().describe('effective.skip（M2-6, issue #24）。program_intents.action=\'skip\' の\n明示、または意図が無く base.skip（ルールの重複排除判定）が true。\ntrue の間 reconciler は mirakc に同期しないが、予約行自体は\n「なぜ録られていないか」を説明するため残る。\n'),
  "dedupMatchRecordingId": zod.number().optional().describe('履歴ベース重複排除でマッチした録画の ID（マッチが無ければ省略）'),
  "dedupSimilarity": zod.number().optional().describe('上記マッチの pg_trgm 類似度（0.0〜1.0、マッチが無ければ省略）')
})


/**
 * EPG プロジェクションのサービス一覧。channelType, remoteControlKeyId, serviceId 順。
 *
 * サブサービス（ＮＨＫ総合２ 等）も含む全サービスを返す。マルチ編成のない
 * サブサービスは番組を持たないため、UI は時間窓内に番組があるサービスだけを
 * 表示することが期待される（issue #17 の S3）。
 * @summary List EPG services (channels)
 */
export const ListServicesParams = zod.object({
  "site": zod.string().describe('mirakc インスタンスのサイト名。programId はインスタンス単位のスコープ\nしか持たないため、この site と組にしないと資源が一意に定まらない\n（issue #31）。api プロセス自身は特定の site に束縛されない\n（不変条件 1: mirakc にもファイルシステムにも依存しない）ので、権威は\n「`config.mirakc`\/`mirakcs` レジストリに存在するか」であり、1 プロセスが\nレジストリの全 site を処理できる（issue #184 M4-12）。レジストリに無い\nsite のエラーコードはエンドポイントの HTTP メソッドで決まる —— GET 系は\n404、POST\/PUT\/PATCH\/DELETE 系は 400（他の入力検証と同じ扱い。詳細は各\nエンドポイントの description・レスポンス定義を参照）。存在する site の\n一覧は `GET \/api\/sites` で取得できる。\n')
})

export const ListServicesResponseItem = zod.object({
  "id": zod.number().describe('サービスの一意な識別子。`networkId \* 100000 + serviceId`（Mirakurun \/\nmirakc の `ServiceId` と同じ合成規則。権威は `internal\/mirakc.ServiceID`）。\n\n\*\*SI の `serviceId` は network をまたぐと一意でない\*\*（BS 101 と\n110度CS 101 は実在する衝突）ため、絞り込み・選択・キャッシュキーの\nidentity にはこの値を使う。`?service=` に載るのもこの値。\n\n\*\*int32 には収まらない\*\*（networkId \/ serviceId とも 16bit なので\n最大 65535 \* 100000 + 65535 = 6,553,565,535）。JavaScript の\nsafe integer には収まる。\n'),
  "networkId": zod.number(),
  "serviceId": zod.number(),
  "name": zod.string(),
  "channelType": zod.enum(['GR', 'BS', 'CS', 'SKY']),
  "channel": zod.string(),
  "remoteControlKeyId": zod.number(),
  "hasLogoData": zod.boolean(),
  "hasPrograms": zod.boolean().describe('EPG プロジェクション全体（表示中の時間窓ではない）に、このサービスの番組が\n1 件でもあるか。マルチ編成のないサブサービスは番組を持たないため false になる。\nこのエンドポイント自体はこのフラグで絞り込まない —— ルールはまだ番組を持たない\nサービスも参照できる必要があり、絞り込むと「EPG プロジェクションのサービス\n一覧」という定義に反する構成員を落とすことになる。\n')
})
export const ListServicesResponse = zod.array(ListServicesResponseItem)


/**
 * `tuner_sync`（worker が周期で mirakc の `/api/tuners` を投影する使い捨て
 * プロジェクション）の行をそのまま返す。導出はしない（不変条件 9・11）。
 * 列の意味の権威は docs/data/capacity.md §6.5。
 *
 * 「いまどの局を掴んでいるか」「ライブ視聴が何本か」は `tuner_sync` に
 * 無いため、このエンドポイントも持たない（watcher の観測対象を広げる
 * 別の判断）。
 *
 * 射影が 1 行も無いサイトは空配列を返す（「射影が 1 行も無いサイトは
 * 何も主張しない」docs/data/capacity.md §6.5）。
 * @summary List projected tuners
 */
export const ListTunersParams = zod.object({
  "site": zod.string().describe('mirakc インスタンスのサイト名。programId はインスタンス単位のスコープ\nしか持たないため、この site と組にしないと資源が一意に定まらない\n（issue #31）。api プロセス自身は特定の site に束縛されない\n（不変条件 1: mirakc にもファイルシステムにも依存しない）ので、権威は\n「`config.mirakc`\/`mirakcs` レジストリに存在するか」であり、1 プロセスが\nレジストリの全 site を処理できる（issue #184 M4-12）。レジストリに無い\nsite のエラーコードはエンドポイントの HTTP メソッドで決まる —— GET 系は\n404、POST\/PUT\/PATCH\/DELETE 系は 400（他の入力検証と同じ扱い。詳細は各\nエンドポイントの description・レスポンス定義を参照）。存在する site の\n一覧は `GET \/api\/sites` で取得できる。\n')
})

export const ListTunersResponseItem = zod.object({
  "index": zod.number().describe('mirakc の `\/api\/tuners` レスポンス内の配列インデックス。'),
  "name": zod.string(),
  "types": zod.array(zod.enum(['GR', 'BS', 'CS', 'SKY'])),
  "isAvailable": zod.boolean(),
  "isFault": zod.boolean().describe('mirakc の `\/api\/tuners` が返す値をそのまま射影している。\nMirakurun 互換 API のフィールドで、Mirakurun 本体ではチューナー\nプロセスの error を 3 回数えたら立つラッチだが、\*\*mirakc は\n実装しておらずリテラルの false を返す\*\*（models.rs が\n`Always false.` と明記）。`isAvailable` も同様に常に true。\n'),
  "observedAt": zod.string().datetime({"offset":true}).describe('この行を最後に投影した時刻。射影ループが止まっていても行は消えない\nため、鮮度の手がかりとして必ずこれを使う（`GET \/api\/storage` の\n`observedAt` と同じ契約）。\n')
}).describe('`tuner_sync` の行をそのまま返す（導出しない）。列の意味の権威は\ndocs\/data\/capacity.md §6.5「チューナー射影と容量超過の判定」。\n')
export const ListTunersResponse = zod.array(ListTunersResponseItem)


/**
 * ルール条件と同じコンパイラ（internal/rulequery）で epg_programs を検索する。
 * ruler 評価と同一の SQL 経路を通る（M2-2）。UI 検索（M2-11）の土台。
 *
 * **`sites`（絞り込み条件、空または省略 = 全サイト）が検索対象のサイト軸を決める。**
 * レスポンスは `{site, programId}` のフラットな配列で、同一放送が複数サイトで
 * マッチすれば行が複数出る（畳まない）。ruler はマッチした全サイトで予約を作る
 * （N 予約が既定。docs/recording/ruler.md「サイトの扱い」）ため、行数がそのまま
 * 実体化される予約数になる。
 *
 * **非互換の変更**: 旧仕様は `sites` を `rule_sites` 相当の絞り込み（空 = パスの
 * {site} のみを評価対象にする）と説明していたが、実際の SQL は `$site = ANY($sites)`
 * という両辺が定数でテーブル列を参照しない述語だったため、事実上パスの {site} だけが
 * 全か無かのゲートとして機能し `sites` は無効だった。新仕様では `sites` が
 * `epg_programs.site` に対する実際の絞り込み述語になる。
 *
 * `sites` の既定を「空 = 全サイト」と定義するのは、Go 側がレジストリ全件を埋めて
 * `Compile` に渡す前提のため。
 * @summary Search EPG programs by rule-style conditions
 */
export const SearchProgramsParams = zod.object({
  "site": zod.string().describe('mirakc インスタンスのサイト名。programId はインスタンス単位のスコープ\nしか持たないため、この site と組にしないと資源が一意に定まらない\n（issue #31）。api プロセス自身は特定の site に束縛されない\n（不変条件 1: mirakc にもファイルシステムにも依存しない）ので、権威は\n「`config.mirakc`\/`mirakcs` レジストリに存在するか」であり、1 プロセスが\nレジストリの全 site を処理できる（issue #184 M4-12）。レジストリに無い\nsite のエラーコードはエンドポイントの HTTP メソッドで決まる —— GET 系は\n404、POST\/PUT\/PATCH\/DELETE 系は 400（他の入力検証と同じ扱い。詳細は各\nエンドポイントの description・レスポンス定義を参照）。存在する site の\n一覧は `GET \/api\/sites` で取得できる。\n')
})

export const searchProgramsBodyTextMatchesItemCaseSensitiveDefault = false;
export const searchProgramsBodyTextMatchesItemNegateDefault = false;
export const searchProgramsBodyGenresItemMin = 0;
export const searchProgramsBodyGenresItemMax = 15;

export const searchProgramsBodyTimesItemWeekdaysMax = 127;

export const searchProgramsBodyTimesItemStartSecMin = 0;
export const searchProgramsBodyTimesItemStartSecMax = 86400;

export const searchProgramsBodyTimesItemEndSecMin = 0;
export const searchProgramsBodyTimesItemEndSecMax = 86400;



export const SearchProgramsBody = zod.object({
  "isFree": zod.boolean().nullish(),
  "durationMinMs": zod.number().nullish(),
  "durationMaxMs": zod.number().nullish(),
  "periodStartAt": zod.string().datetime({"offset":true}).nullish(),
  "periodEndAt": zod.string().datetime({"offset":true}).nullish(),
  "textMatches": zod.array(zod.object({
  "target": zod.enum(['name', 'description', 'extended']),
  "mode": zod.enum(['keyword', 'regex']).describe('keyword = 部分一致 \/ regex = POSIX ARE'),
  "value": zod.string(),
  "caseSensitive": zod.boolean().default(searchProgramsBodyTextMatchesItemCaseSensitiveDefault),
  "negate": zod.boolean().default(searchProgramsBodyTextMatchesItemNegateDefault).describe('true なら除外条件')
})).optional(),
  "services": zod.array(zod.object({
  "networkId": zod.number(),
  "serviceId": zod.number()
})).optional(),
  "channelTypes": zod.array(zod.enum(['GR', 'BS', 'CS', 'SKY'])).optional(),
  "genres": zod.array(zod.number().min(searchProgramsBodyGenresItemMin).max(searchProgramsBodyGenresItemMax)).optional(),
  "times": zod.array(zod.object({
  "weekdays": zod.number().min(1).max(searchProgramsBodyTimesItemWeekdaysMax).describe('bit0=月 … bit6=日'),
  "startSec": zod.number().min(searchProgramsBodyTimesItemStartSecMin).max(searchProgramsBodyTimesItemStartSecMax),
  "endSec": zod.number().min(searchProgramsBodyTimesItemEndSecMin).max(searchProgramsBodyTimesItemEndSecMax).describe('start より小さい場合は翌日跨ぎ')
})).optional(),
  "sites": zod.array(zod.string()).optional().describe('絞り込み条件。空または省略 = 全サイト（`GET \/api\/recordings` の `?site=` と 同じ軸の規約: 軸内は OR、他の絞り込み軸とは AND）。\*\*非互換の変更\*\*: 旧仕様は `sites` を `rule_sites` 相当の条件として扱い、空 = パスの {site}（評価 site） のみだった。')
}).describe('ルール条件の条件部分と同じ形。rulequery.Conditions に写像される。\n検索対象のサイトは `sites`（空または省略 = 全サイト）が決める。\n')

export const SearchProgramsResponseItem = zod.object({
  "site": zod.string().describe('マッチした放送のサイト'),
  "programId": zod.number().describe('マッチした放送の programId（`GET \/api\/sites\/{site}\/programs\/{programId}` などで使う ID）。同一放送は全サイトで同じ値を持つ（Mirakurun の ID 合成）')
}).describe('検索がマッチした 1 件（1 サイトの 1 放送）')
export const SearchProgramsResponse = zod.array(SearchProgramsResponseItem)


/**
 * 指定した時間窓に**一部でも重なる**番組を start_at 昇順で返す
 * （`start_at < end AND end_at > start`）。窓開始前に始まった放送中の番組も含む。
 *
 * 無限スクロールで窓を継ぎ足す場合、境界をまたぐ番組は隣接する 2 つの窓の
 * 両方に現れる。クライアントは programId で重複排除すること。
 *
 * ページネーショントークンは持たない。時間窓そのものがカーソルであり、
 * 同じ窓は常に同じ完全な結果を返す。
 *
 * レスポンスは一覧向けの軽い形で、extended / video / audios は含まない。
 * それらは `GET /api/sites/{site}/programs/{programId}` で取得する。
 * @summary List EPG programs in a time window
 */
export const ListProgramsParams = zod.object({
  "site": zod.string().describe('mirakc インスタンスのサイト名。programId はインスタンス単位のスコープ\nしか持たないため、この site と組にしないと資源が一意に定まらない\n（issue #31）。api プロセス自身は特定の site に束縛されない\n（不変条件 1: mirakc にもファイルシステムにも依存しない）ので、権威は\n「`config.mirakc`\/`mirakcs` レジストリに存在するか」であり、1 プロセスが\nレジストリの全 site を処理できる（issue #184 M4-12）。レジストリに無い\nsite のエラーコードはエンドポイントの HTTP メソッドで決まる —— GET 系は\n404、POST\/PUT\/PATCH\/DELETE 系は 400（他の入力検証と同じ扱い。詳細は各\nエンドポイントの description・レスポンス定義を参照）。存在する site の\n一覧は `GET \/api\/sites` で取得できる。\n')
})

export const listProgramsQueryServiceItemMax = 6553565535;



export const ListProgramsQueryParams = zod.object({
  "start": zod.string().datetime({"offset":true}).describe('時間窓の開始（この時刻より後に終わる番組が対象）'),
  "end": zod.string().datetime({"offset":true}).describe('時間窓の終了（この時刻より前に始まる番組が対象）。start からの幅は最大 7 日'),
  "service": zod.array(zod.number().min(1).max(listProgramsQueryServiceItemMax)).optional().describe('`Service.id`（`networkId \* 100000 + serviceId`）。複数指定は OR。\n')
})

export const ListProgramsResponseItem = zod.object({
  "programId": zod.number(),
  "networkId": zod.number(),
  "serviceId": zod.number(),
  "eventId": zod.number(),
  "startAt": zod.string().datetime({"offset":true}),
  "endAt": zod.string().datetime({"offset":true}),
  "durationMs": zod.number(),
  "name": zod.string(),
  "description": zod.string(),
  "genres": zod.array(zod.number()).describe('ジャンル絞り込み用の lv1 のみ。詳細は Program.genreDetails'),
  "isFree": zod.boolean()
})
export const ListProgramsResponse = zod.array(ListProgramsResponseItem)


/**
 * @summary Get a single EPG program with full detail
 */
export const GetProgramParams = zod.object({
  "site": zod.string().describe('mirakc インスタンスのサイト名。programId はインスタンス単位のスコープ\nしか持たないため、この site と組にしないと資源が一意に定まらない\n（issue #31）。api プロセス自身は特定の site に束縛されない\n（不変条件 1: mirakc にもファイルシステムにも依存しない）ので、権威は\n「`config.mirakc`\/`mirakcs` レジストリに存在するか」であり、1 プロセスが\nレジストリの全 site を処理できる（issue #184 M4-12）。レジストリに無い\nsite のエラーコードはエンドポイントの HTTP メソッドで決まる —— GET 系は\n404、POST\/PUT\/PATCH\/DELETE 系は 400（他の入力検証と同じ扱い。詳細は各\nエンドポイントの description・レスポンス定義を参照）。存在する site の\n一覧は `GET \/api\/sites` で取得できる。\n'),
  "programId": zod.number()
})

export const GetProgramResponse = zod.object({
  "programId": zod.number(),
  "networkId": zod.number(),
  "serviceId": zod.number(),
  "eventId": zod.number(),
  "startAt": zod.string().datetime({"offset":true}),
  "endAt": zod.string().datetime({"offset":true}),
  "durationMs": zod.number(),
  "name": zod.string(),
  "description": zod.string(),
  "genres": zod.array(zod.number()).describe('ジャンル絞り込み用の lv1 のみ。詳細は Program.genreDetails'),
  "isFree": zod.boolean()
}).and(zod.object({
  "extended": zod.record(zod.string(), zod.string()).optional().describe('拡張形式イベント（出演者等）'),
  "genreDetails": zod.array(zod.object({
  "lv1": zod.number(),
  "lv2": zod.number(),
  "un1": zod.number().optional(),
  "un2": zod.number().optional()
})).optional(),
  "video": zod.object({
  "type": zod.string().optional(),
  "resolution": zod.string().optional(),
  "streamContent": zod.number().optional(),
  "componentType": zod.number().optional()
}).optional(),
  "audios": zod.array(zod.object({
  "componentType": zod.number(),
  "isMain": zod.boolean(),
  "samplingRate": zod.number(),
  "langs": zod.array(zod.string()).optional()
})).optional()
}))


/**
 * 指定番組の放送時間帯（EPG プロジェクションから引く）と半開区間で重なる
 * 既存予約の件数と内訳を返す（`a.start < b.end AND b.start < a.end`。番組表は
 * 連続しているため、閉区間で判定すると隣接番組がすべて重なりになってしまう）。
 *
 * 対象は同じ site の予約のうち、自分自身（同じ programId の予約）を除き、
 * `state <> 'orphaned'`、実効オプション（`db.EffectiveOptions`）の `skip` が
 * true でないもの。
 *
 * **これは重なりの件数だけを返す。チューナー本数との比較や容量超過の判定は
 * 行わない**（[issue #21](https://github.com/fetburner/rokuban/issues/21) の
 * 「案 C」、docs/data.md §6.5 が扱う M2-10 の領分）。`count` が 0 より大きくても
 * 「録画できない」とは限らず（同一物理チャンネルなら 1 本のチューナーで
 * 複数番組を賄える）、逆に `count` が 0 でも他サイトや mirakc の他の消費者
 * （並走 EPGStation・ライブ視聴・EPG 収集）の存在は考慮されていない。
 * 呼び出し側は件数を「事実」として提示し、勝敗や可否を断定してはならない。
 *
 * 番組が EPG プロジェクションに無ければ 404。
 * @summary Count reservations overlapping this program's broadcast time
 */
export const GetProgramOverlapsParams = zod.object({
  "site": zod.string().describe('mirakc インスタンスのサイト名。programId はインスタンス単位のスコープ\nしか持たないため、この site と組にしないと資源が一意に定まらない\n（issue #31）。api プロセス自身は特定の site に束縛されない\n（不変条件 1: mirakc にもファイルシステムにも依存しない）ので、権威は\n「`config.mirakc`\/`mirakcs` レジストリに存在するか」であり、1 プロセスが\nレジストリの全 site を処理できる（issue #184 M4-12）。レジストリに無い\nsite のエラーコードはエンドポイントの HTTP メソッドで決まる —— GET 系は\n404、POST\/PUT\/PATCH\/DELETE 系は 400（他の入力検証と同じ扱い。詳細は各\nエンドポイントの description・レスポンス定義を参照）。存在する site の\n一覧は `GET \/api\/sites` で取得できる。\n'),
  "programId": zod.number()
})

export const GetProgramOverlapsResponse = zod.object({
  "count": zod.number().describe('重なっている既存予約の件数（自分自身を除く）'),
  "reservations": zod.array(zod.object({
  "id": zod.number(),
  "programId": zod.number(),
  "title": zod.string(),
  "startAt": zod.string().datetime({"offset":true}),
  "durationMs": zod.number()
})).describe('内訳。件数だけでなく何と重なっているかをユーザーが判断できるようにする')
})


/**
 * ユーザー意図（`program_intents`）を `(site, programId)` を自身のキーとして
 * 書く（issue #29）。導出行（`reservations`）の有無に依存しないので、
 * `base.skip` が立っている番組にも `action=record` を立てられる
 * （旧 `POST /api/reservations` は導出行が「無い」ときしか書けなかった）。
 *
 * 意図だけを書き、`reservations` は同一トランザクションで作らない
 * （`reservations` の書き手は ruler だけにする。issue #29 の決定）。
 * `insertRulerPassHint` で ruler_pass を即座に投入するので、実体化は
 * 秒オーダー。フロントエンドは楽観更新で一覧に即時反映する。
 *
 * 番組が EPG プロジェクションに無ければ 400。
 * @summary Assert record/skip intent for a program
 */
export const PutProgramIntentParams = zod.object({
  "site": zod.string().describe('mirakc インスタンスのサイト名。programId はインスタンス単位のスコープ\nしか持たないため、この site と組にしないと資源が一意に定まらない\n（issue #31）。api プロセス自身は特定の site に束縛されない\n（不変条件 1: mirakc にもファイルシステムにも依存しない）ので、権威は\n「`config.mirakc`\/`mirakcs` レジストリに存在するか」であり、1 プロセスが\nレジストリの全 site を処理できる（issue #184 M4-12）。レジストリに無い\nsite のエラーコードはエンドポイントの HTTP メソッドで決まる —— GET 系は\n404、POST\/PUT\/PATCH\/DELETE 系は 400（他の入力検証と同じ扱い。詳細は各\nエンドポイントの description・レスポンス定義を参照）。存在する site の\n一覧は `GET \/api\/sites` で取得できる。\n'),
  "programId": zod.number()
})

export const PutProgramIntentBody = zod.object({
  "action": zod.enum(['record', 'skip'])
}).describe('PUT \/api\/sites\/{site}\/programs\/{programId}\/intent のボディ。\n`record` は「録れ」（手動予約、およびルール由来予約への上書き）。\n`skip` は「録るな」（どのルール経由でも一貫して除外される）。\n')

export const PutProgramIntentResponse = zod.void()


/**
 * `program_intents` の行を削除するだけ（意見なし。純粋にルール由来へ戻す）。
 * 取消（「録るな」の明示的な主張）は `PUT .../intent {action: skip}`。
 * こちらは「何も主張しない」状態に戻す操作で、`program_overrides` には
 * 一切触れない（別表・別軸。issue #29）。冪等（行が無くても 204）。
 * @summary Clear intent for a program (defer to the rule)
 */
export const DeleteProgramIntentParams = zod.object({
  "site": zod.string().describe('mirakc インスタンスのサイト名。programId はインスタンス単位のスコープ\nしか持たないため、この site と組にしないと資源が一意に定まらない\n（issue #31）。api プロセス自身は特定の site に束縛されない\n（不変条件 1: mirakc にもファイルシステムにも依存しない）ので、権威は\n「`config.mirakc`\/`mirakcs` レジストリに存在するか」であり、1 プロセスが\nレジストリの全 site を処理できる（issue #184 M4-12）。レジストリに無い\nsite のエラーコードはエンドポイントの HTTP メソッドで決まる —— GET 系は\n404、POST\/PUT\/PATCH\/DELETE 系は 400（他の入力検証と同じ扱い。詳細は各\nエンドポイントの description・レスポンス定義を参照）。存在する site の\n一覧は `GET \/api\/sites` で取得できる。\n'),
  "programId": zod.number()
})

export const DeleteProgramIntentResponse = zod.void()


/**
 * 値を書いたフィールドはそのフィールドの override を設定する。`reset`
 * 配列に名前を挙げたフィールドは override を削除する（フィールド単位の
 * 「ルールに戻す」）。どちらにも現れないフィールドは変更しない。
 *
 * `null` で消す形にはしない（`*T` は「キーが無い」と `null` を区別できず、
 * 「消す」が「変更しない」に化けて黙って壊れるため。
 * docs/recording.md §4.2「overrides API の形」）。
 *
 * 同じフィールドを値と `reset` の両方に書いたら 400（意図が不明なので
 * 推測しない）。`reset` に未知のフィールド名があっても 400。
 *
 * `skip` は overrides のキーではない（`program_intents.action` が担う）ので
 * ここでは扱わない。取消は `PUT .../intent {action: skip}`。
 *
 * `(site, programId)` を自身のキーとして `program_overrides` を書く
 * （issue #29）。導出行（`reservations`）の有無には依存しない。
 * @summary Update per-program overrides
 */
export const PatchProgramOverridesParams = zod.object({
  "site": zod.string().describe('mirakc インスタンスのサイト名。programId はインスタンス単位のスコープ\nしか持たないため、この site と組にしないと資源が一意に定まらない\n（issue #31）。api プロセス自身は特定の site に束縛されない\n（不変条件 1: mirakc にもファイルシステムにも依存しない）ので、権威は\n「`config.mirakc`\/`mirakcs` レジストリに存在するか」であり、1 プロセスが\nレジストリの全 site を処理できる（issue #184 M4-12）。レジストリに無い\nsite のエラーコードはエンドポイントの HTTP メソッドで決まる —— GET 系は\n404、POST\/PUT\/PATCH\/DELETE 系は 400（他の入力検証と同じ扱い。詳細は各\nエンドポイントの description・レスポンス定義を参照）。存在する site の\n一覧は `GET \/api\/sites` で取得できる。\n'),
  "programId": zod.number()
})

export const PatchProgramOverridesBody = zod.object({
  "priority": zod.number().optional().describe('mirakc の schedule に反映される（reconciler が DELETE + POST で\nschedule を再作成する）。ただし録画開始後の recorder には\n効かない可能性が高い（docs\/recording.md §4.5）。\n'),
  "contentPath": zod.string().optional().describe('明示指定した値は既存の schedule にも反映される（reconciler が\nDELETE + POST で張り替える）。ただし録画が始まった schedule には\n反映されない（docs\/recording.md §4.5）。空文字は 400（override を\n消すのは `reset`。消しても既存 schedule のパスは変わらない）。\n'),
  "filenameTemplate": zod.string().optional().describe('Go text\/template のテンプレート文字列。既存の schedule には\n反映されず、まだ schedule が作られていない予約にだけ効く\n（docs\/recording.md §4.5）。`contentPath` を明示指定すればそちらは\n既存の schedule にも反映される（このフィールドとの違い）。\n'),
  "keepOriginal": zod.enum(['always', 'until_encoded']).optional().describe('ingest が原本をコミットする tx の中で recording_encode_policy 行の\nINSERT として焼かれる（凍結される）瞬間まで効く。録画開始後の変更でも、\n放送終了・ingest 完了より前ならこの録画に反映されるが、ingest 完了後の\n変更はこの録画には反映されない（docs\/recording\/reservation-model.md\n§4.5）。\n\n\*\*「ingest 完了より前なら必ず反映される」ではない\*\* --- 凍結の導出元\n（program_snapshots と CASCADE で連なる予約系の表）は放送終了 +\n`epg.retention_grace`（既定 24h）で GC されるため、エッジに record が\n滞留して ingest がそれを超えて遅れると、指定は効かず既定値\n（keepOriginal=always \/ encodeProfiles=[]）で凍結される（原本は残る\nがエンコードは投入されない。docs\/storage\/retention.md §6「凍結が\n依存する寿命と、エッジの滞留の交点」）。\n'),
  "encodeProfiles": zod.array(zod.string()).optional().describe('ingest が原本をコミットする tx の中で recording_encode_policy 行の\nINSERT として焼かれる（凍結される）瞬間まで効く。録画開始後の変更でも、\n放送終了・ingest 完了より前ならこの録画に反映されるが、ingest 完了後の\n変更はこの録画には反映されない（docs\/recording\/reservation-model.md\n§4.5）。\n\n\*\*「ingest 完了より前なら必ず反映される」ではない\*\* --- 凍結の導出元\n（program_snapshots と CASCADE で連なる予約系の表）は放送終了 +\n`epg.retention_grace`（既定 24h）で GC されるため、エッジに record が\n滞留して ingest がそれを超えて遅れると、指定は効かず既定値\n（keepOriginal=always \/ encodeProfiles=[]）で凍結される（原本は残る\nがエンコードは投入されない。docs\/storage\/retention.md §6「凍結が\n依存する寿命と、エッジの滞留の交点」）。\n'),
  "reset": zod.array(zod.enum(['priority', 'contentPath', 'filenameTemplate', 'keepOriginal', 'encodeProfiles'])).optional().describe('指定したフィールドの override を削除する（フィールド単位の\n「ルールに戻す」）。値を書いたフィールドと重複して指定すると 400。\n')
}).describe('PATCH \/api\/sites\/{site}\/programs\/{programId}\/overrides のボディ。\n値を書いたフィールドは override を設定し、`reset` に名前を挙げた\nフィールドは override を削除する。どちらにも現れないフィールドは\n変更しない。同じフィールドを値と `reset` の両方に書いたら 400、\n`reset` に未知のフィールド名があっても 400（docs\/recording.md §4.2）。\n')

export const PatchProgramOverridesResponse = zod.void()


/**
 * `program_overrides` の行を削除するだけ。`action`（record/skip。
 * `program_intents` 側）は触らない（別表・別軸。docs/recording.md §4.2
 * 「overrides は program_intents とは別の表に置く」）。冪等（行が無くても 204）。
 * @summary Reset all overrides for a program (revert to rule)
 */
export const DeleteProgramOverridesParams = zod.object({
  "site": zod.string().describe('mirakc インスタンスのサイト名。programId はインスタンス単位のスコープ\nしか持たないため、この site と組にしないと資源が一意に定まらない\n（issue #31）。api プロセス自身は特定の site に束縛されない\n（不変条件 1: mirakc にもファイルシステムにも依存しない）ので、権威は\n「`config.mirakc`\/`mirakcs` レジストリに存在するか」であり、1 プロセスが\nレジストリの全 site を処理できる（issue #184 M4-12）。レジストリに無い\nsite のエラーコードはエンドポイントの HTTP メソッドで決まる —— GET 系は\n404、POST\/PUT\/PATCH\/DELETE 系は 400（他の入力検証と同じ扱い。詳細は各\nエンドポイントの description・レスポンス定義を参照）。存在する site の\n一覧は `GET \/api\/sites` で取得できる。\n'),
  "programId": zod.number()
})

export const DeleteProgramOverridesResponse = zod.void()


/**
 * 録画履歴。既定は program_start_at 降順（`order=asc` で昇順）。ドロップ統計は
 * PID 別の合計のみを含む。PID 別の内訳は `GET /api/recordings/{id}/drop-stats`
 * で取得する。
 *
 * 既定は生きている録画（`deleted_at IS NULL`）のみ。`trash=true` でごみ箱
 * （`deleted_at IS NOT NULL AND purged_at IS NULL`）を返す。完全削除
 * （purge）が完了した tombstone（`purged_at` が立った行、issue #135）は
 * ファイルが既に無いため、ごみ箱にも通常一覧にも出ない。`trash` と各
 * 絞り込み条件は直交する --- `trash=true` でも条件は同じように効く。
 *
 * ## 絞り込み
 *
 * - `q` はキーワードの部分一致。`qTarget`（既定 `titleDescription`）で対象を
 *   `title` 単体に絞れる。全角/半角の揺れは `normalize_search_text` で吸収する
 *   （docs/data.md §5）。`/search`（EPG 検索）と同じ正規化方言を使うが、
 *   エンジン（`internal/rulequery`）は共有しない --- 理由は docs/data.md §5
 *   「録画検索は rulequery を共有しない」
 * - `genre` は `genre_lv1`（ジャンル大分類。`genres` から生成列で導出）との
 *   重なりで絞る（複数指定は OR）
 * - `site` / `channelType` / `service` は複数指定可（`style: form,
 *   explode: true`）。`service` は `Service.id`（例: `?service=400101`）。
 *   **すべての軸は「軸内は OR、軸間は AND」**
 * - `status` / `source` / `ruleId` は録画自身の観測・出自での絞り込み
 * - `encodeState` は River の active な encode ジョブを待機中 / 実行中で絞る。
 * - `from` / `to` は `program_start_at` の範囲（`from` 以上 `to` 未満）
 *
 * 不正な値（enum に一致しない `status`/`source`/`encodeState`/`qTarget`/`channelType`/
 * `order`、ドメイン外の `genre`）は無視・切り詰めせず 400 にする。
 *
 * ## ページング（キーセット）
 *
 * トークンを発行しない。返った配列の**最後の要素**の `startAt` / `id` を、
 * 次のリクエストの `before` / `beforeId` にそのまま渡す（EPG の時間窓カーソル
 * --- docs/api.md「時間窓がカーソル」--- と同じ思想だが、録画は有界に増え続ける
 * ため境界は時間窓ではなく `(program_start_at, id)` の複合キーになる。同一
 * `program_start_at` の録画（同時刻開始の別チャンネル）が普通に発生するため、
 * `id` を tie-breaker にしないとページ跨ぎで重複・欠落が出る）。`before` /
 * `beforeId` は両方揃って初めて有効（片方だけの指定は 400）。`order=asc` では
 * カーソルの不等号を反転する。総件数は返さない（別クエリが要り、キーセットの
 * 利点を打ち消すため。必要になったら別 issue）。`limit` の既定は 50、上限は
 * 200（超えると 400）。
 *
 * `trash=true` でもカーソル軸は `program_start_at` のまま（旧
 * `ListTrashRecordings` の `deleted_at` 降順からの意図的な変更。理由は
 * docs/api.md「録画一覧: 絞り込み + キーセットページング」参照）。
 *
 * **既定では全サイトの録画を返す**（issue #184 M4-12）。`?site=` で
 * 絞り込める。各要素の `site` フィールドでも区別できる。
 * @summary List recordings
 */
export const listRecordingsQueryQTargetDefault = `titleDescription`;
export const listRecordingsQueryGenreItemMin = 0;
export const listRecordingsQueryGenreItemMax = 15;

export const listRecordingsQuerySiteItemRegExp = new RegExp('^[a-z0-9](?:[_-]?[a-z0-9])*$');
export const listRecordingsQueryServiceItemMax = 6553565535;

export const listRecordingsQueryOrderDefault = `desc`;
export const listRecordingsQueryTrashDefault = false;
export const listRecordingsQueryLimitDefault = 50;
export const listRecordingsQueryLimitMax = 200;



export const ListRecordingsQueryParams = zod.object({
  "q": zod.string().optional().describe('キーワード（部分一致）。qTarget が対象列を決める'),
  "qTarget": zod.enum(['title', 'titleDescription']).default(listRecordingsQueryQTargetDefault),
  "genre": zod.array(zod.number().min(listRecordingsQueryGenreItemMin).max(listRecordingsQueryGenreItemMax)).optional().describe('genre_lv1（ジャンル大分類）との重なり。複数指定可'),
  "channelType": zod.array(zod.enum(['GR', 'BS', 'CS', 'SKY'])).optional(),
  "site": zod.array(zod.string().regex(listRecordingsQuerySiteItemRegExp)).optional().describe('mirakc サイト名。複数指定は OR。site 名の構文は\n`config.mirakc`\/`mirakcs` レジストリと同じ（`internal\/config` の\n`mirakcSiteNamePattern`）。レジストリに無い名前を渡してもエラーには\nせず 0 件になる --- 絞り込みは「あるものから選ぶ」操作なので、\n存在しない値の指定は空の結果として素直に読める。\n'),
  "service": zod.array(zod.number().min(1).max(listRecordingsQueryServiceItemMax)).optional().describe('`Service.id`（`networkId \* 100000 + serviceId`）。複数指定は OR。\n\n\*\*site は含めない\*\*（`site` パラメータが別軸）。他の絞り込み軸と\n同じく「軸内は OR、軸間は AND」で、`?site=tokyo&service=400101` は\n「tokyo の BS 101」を意味する。\n'),
  "status": zod.enum(['recording', 'finished', 'canceled', 'failed']).optional().describe('recordings.status の CHECK と一致させた 4 値（\'canceled\' は issue #130 で\nCHECK に追加済み）。\n\n`status=failed` は通常一覧（`trash=false`）に限り supersede 済みの\nfailed 行を返さない。本物の record が観測されて置き換わった擬似\nfailed 行を「録画失敗」として返さないため（ホームの警告が偽陽性を\n出し続けるのを防ぐ）。無条件一覧・`trash=true` は履歴として両行を残す。\n'),
  "encodeState": zod.enum(['queued', 'running']).optional().describe('active な River encode ジョブの状態。`queued` は `available` \/\n`pending` \/ `scheduled` \/ `retryable`、`running` は実行中を表す。\n件数は録画数ではなく録画 × プロファイルのジョブ数になる。\n'),
  "source": zod.enum(['rule', 'manual']).optional(),
  "ruleId": zod.number().optional().describe('特定ルール由来の録画に絞る'),
  "from": zod.string().datetime({"offset":true}).optional().describe('program_start_at がこの時刻以上'),
  "to": zod.string().datetime({"offset":true}).optional().describe('program_start_at がこの時刻未満'),
  "order": zod.enum(['desc', 'asc']).default(listRecordingsQueryOrderDefault),
  "trash": zod.boolean().default(listRecordingsQueryTrashDefault).describe('true のときごみ箱（論理削除済み）を返す'),
  "limit": zod.number().min(1).max(listRecordingsQueryLimitMax).default(listRecordingsQueryLimitDefault),
  "before": zod.string().datetime({"offset":true}).optional().describe('キーセットカーソル。前ページ最後の要素の startAt。beforeId と対で使う'),
  "beforeId": zod.number().optional().describe('キーセットカーソル。前ページ最後の要素の id。before と対で使う')
})

export const ListRecordingsResponseItem = zod.object({
  "id": zod.number(),
  "site": zod.string().describe('この録画がどのサイト（mirakc インスタンス）のものか。`recordings.site`\nそのまま。`GET \/api\/recordings` は全サイトの録画を返すため\n（issue #184 M4-12）、クライアントはこの値で区別する。\n'),
  "ruleId": zod.number().optional(),
  "source": zod.enum(['rule', 'manual']),
  "serviceName": zod.string(),
  "channelType": zod.enum(['GR', 'BS', 'CS', 'SKY']),
  "channel": zod.string(),
  "networkId": zod.number(),
  "serviceId": zod.number(),
  "eventId": zod.number(),
  "title": zod.string(),
  "description": zod.string().optional(),
  "startAt": zod.string().datetime({"offset":true}).describe('番組の放送開始時刻。常に UTC（\"Z\" 終端の RFC3339）で返す。'),
  "durationMs": zod.number(),
  "status": zod.enum(['recording', 'finished', 'canceled', 'failed']),
  "startedAt": zod.string().datetime({"offset":true}).optional().describe('録画の実開始時刻。常に UTC（\"Z\" 終端の RFC3339）で返す。'),
  "endedAt": zod.string().datetime({"offset":true}).optional().describe('録画の実終了時刻。常に UTC（\"Z\" 終端の RFC3339）で返す。'),
  "sizeBytes": zod.number().optional().describe('原本の実サイズ。ingest 済み（media_assets 行あり）の場合のみ。\n省略は「まだ取り込めていない」と「取り込んだ後に削除した」の両方を\n含むので、区別が要るときは `ingest.state` を見る（issue #211 \/\n#212）。\*\*転送中の途中ファイルのサイズはここに混ぜない\*\*（コミット =\nDB 行。不変条件 3）--- 途中経過は `ingest.writtenBytes`。\n'),
  "encodedAssets": zod.array(zod.object({
  "profile": zod.string(),
  "sizeBytes": zod.number().optional().describe('encoded 派生物の実サイズ。`media_assets.size_bytes` は NOT NULL\nなので active な行が存在する限り常に付く（未検証の断言にしないため:\n`media_assets.size_bytes` 列の `NOT NULL` 制約が根拠、実行時計測\nではない。同テーブルの CHECK は\n`kind` \/ `profile` \/ `state` に掛かるものだけで `size_bytes` には\n無い）。省略可能にしているのは、サイズが取れない資産があっても\n選択肢そのものは隠さない（ドロップ統計の「分類できなかった PID」と\n同じ判断。docs\/frontend\/recordings.md）という UI 側の表示規律を\n型で表現するため。\n')
})).optional().describe('再生可能な encoded 派生物（media_assets の active のみ）。\nブラウザ再生は GET \/api\/recordings\/{id}\/file?profile=<name> を使う。\ndesired（encodeProfiles）ではなく observed。空配列は省略可。\n'),
  "encodeProfiles": zod.array(zod.string()).optional().describe('凍結された「望ましい」エンコードプロファイル一覧（desired。\nrecordings.encode_profiles）。ingest 完了時に一度だけ焼き込まれ、以後は\n`POST \/api\/recordings\/{id}\/encode-profiles` による事後追加（凍結の例外。\ndocs\/storage.md §6「原本 TS の保持ポリシー」）でのみ増える。\n`encodedAssets`（observed、再生可能なもの）とは異なり、まだ完了して\nいない pending なジョブのプロファイルも含む --- UI が「追加済み」を\n判定するのに使う。空配列は省略可。\n'),
  "encodeStatus": zod.array(zod.object({
  "profile": zod.string(),
  "state": zod.enum(['queued', 'running', 'failed']).describe('\*\*サーバー側で recording_encode_attempts（衛星表）から毎回導出する\*\*\n（列に焼いた値ではない）。River の river_job は直接露出しない\n（docs\/schema.md の recording_encode_attempts の節を参照。\ndocs\/recording\/ingest.md §5.6 と共通なのは「river_job を露出しない」\nことだけで、§5.6 の「リトライ中と待ちを区別しない」判断とは逆に\nこの表は区別する）。\n\n- `queued`: まだ 1 度も試行が始まっていない（試行行が無い状態）。\n  \*\*一度 `running`\/`failed` を書いた行は成功するまで消えないので、\n  失敗後に `queued` へ戻ることはない\*\*。「来る根拠」の無い\n  `queued` は出さない --- ごみ箱の録画（ジョブが二度と投入されない）\n  と、api が現在の設定にあるプロファイル一覧を知っていて、かつ\n  そのプロファイルが設定から消えていて試行行も無い場合は、この\n  プロファイルの要素自体が省略される\n- `running`: いま ffmpeg が走っている\n- `failed`: 直前の試行が失敗した。\*\*`failed` は「二度と来ない」の\n  断定ではない\*\* --- 失敗したジョブはジョブキューの既定のリトライ\n  上限（25 回。上書きしていない）まで再実行され、その各試行の先頭で\n  `running` に戻る。上限に達した後も、encoded 資産が無い状態が続く\n  限り EncodeReconcileWorker が 15 分ごとに再投入する。例外は設定\n  から消えたプロファイルで、これは EncodeReconcileWorker の既知\n  プロファイル絞り込みが投入対象から外すため、リトライ上限に達した\n  ところで `failed` に留まる（\*\*`failed` に固定されるのはリトライを\n  使い切った後で、最初の失敗の時点ではない\*\*）\n')
})).optional().describe('完了していないエンコードプロファイルの試行状態（issue #316）。\n`encodeProfiles`（desired）のうち `encodedAssets`（observed、\n再生可能）にまだ現れていないプロファイルだけを列挙する ---\n完了したプロファイルはここに出さず `encodedAssets` の存在で示す\n（2 つの配列に同じプロファイルが同時に出ることはない）。\n\nプロファイルを 1 つも設定していない録画・全プロファイルが完了\n済みの録画では省略する（空配列は返さない。機能しないキュー画面や\n空の進捗バーを出さない判断はサーバー側のこの省略で表現する）。\n\n`%` は含まない --- この REST モデルは `queued` \/ `running` \/\n`failed` \/ 完了を復元する durable な状態だけを持つ。実行中の割合は\nnotifier の `\/api\/events` が `encode-progress` SSE として配送する\n揮発テレメトリで、テーブルにも OpenAPI にも保存しない。\n'),
  "dropSummary": zod.object({
  "packets": zod.number(),
  "drops": zod.number(),
  "errors": zod.number(),
  "scrambled": zod.number()
}).optional(),
  "ingest": zod.object({
  "state": zod.enum(['committed', 'transferring', 'pending', 'unknown']).describe('原本の取り込みの粗い状態。\*\*サーバー側で DB 行から毎回導出する\*\*\n（列に焼いた値ではない）。優先順に:\n\n- `committed`: `kind=\'original\'` の `media_assets` 行が存在する。\n  取り込みは少なくとも 1 回完了した。その原本が\*\*いま\*\*あるかどうかは\n  `sizeBytes` の有無で見る（`state=\'deleted\'` の原本でもここは\n  `committed` のまま --- 「取り込めなかった」と「取り込んだ後に\n  消した」を混同しないため。issue #211）\n- `transferring`: 原本行が無く、転送の進捗行がある。`writtenBytes` \/\n  `observedAt` が付く。`observedAt` が古いまま止まっていれば停滞して\n  いる（River のバックオフ待ち・ストール）\n- `pending`: 原本行も進捗行も無く、\*\*ingest ジョブが投入される\n  はずの\*\* mirakc record の観測（`record_sync.status = \'finished\'`。\n  watcher が ingest を投入する条件と同じ述語）がある。取り込み待ち、\n  または失敗して再試行待ち\n- `unknown`: 上のどれでもない。取り込みが始まった観測が無い ---\n  mirakc record が観測されていないか、record が `finished` でない\n  （録画中・`failed`・`canceled`。\*\*この録画に ingest ジョブは\n  投入されない\*\*）\n\n\*\*`pending` は「これから来る」の断定なので、来る根拠が無いものは\n入れない。\*\* `record_sync` 行の存在だけを根拠にすると、`failed` \/\n`canceled` の録画（ingest が一度も投入されず、`record_sync` 行も\n消えない）が永久に「取り込み待ち」を名乗る。\n\n\*\*「リトライ中」を `pending` と区別する値は持たない。\*\* 区別するには\nRiver の `river_job` を API 契約に露出させる（内部実装の露出）か、\n失敗の観測という別寿命の値を進捗行に混ぜる（不変条件 9 \/ 12）\n必要があり、どちらも取らなかった。停滞は `observedAt` の古さで読む。\n'),
  "writtenBytes": zod.number().optional().describe('転送先ファイルに書けたバイト数。`state = transferring` のときだけ付く。\n\n\*\*これは「いまファイルに書けているバイト数」であって累積の転送実績\nではない。\*\* ジョブ再試行（部分ファイルを truncate してゼロから\n作り直す。docs\/recording\/ingest.md §5.3 の層 2）で 0 に戻ることが\nある。戻りを隠さないのは、隠すと「進んでいるのに終わらない」に見えて\n実際に起きているやり直しが観測できなくなるため。\n\n\*\*`sizeBytes`（原本の実サイズ）とは別のフィールドである。\*\* コミット =\nDB 行（不変条件 3）なので、コミット前の途中ファイルのサイズを\n`sizeBytes` に混ぜない。\n'),
  "expectedBytes": zod.number().optional().describe('転送の分母。`record_sync.content_length`（watcher が mirakc record の\n`content.length` として観測した値）を転送開始時に写したもの。mirakc が\nlength を返していなければ\*\*省略する\*\* --- でっち上げた分母を置かない。\n省略時、UI は % を出さず `writtenBytes` だけを出す。\n'),
  "observedAt": zod.string().datetime({"offset":true}).optional().describe('進捗を最後に観測した時刻。`state = transferring` のときだけ付く。\n現在時刻との差が開いていれば転送は停滞している。常に UTC\n（\"Z\" 終端の RFC3339）で返す。\n')
}).optional(),
  "qualityEvents": zod.array(zod.object({

}).passthrough()).optional().describe('recording.failed \/ record-broken \/ bcas_anomaly の履歴'),
  "deletedAt": zod.string().datetime({"offset":true}).optional().describe('論理削除時刻。ごみ箱一覧（`trash=true`）と `GET \/api\/recordings\/{id}`\n（ごみ箱の録画も 200 で返す）でのみ出現する。通常一覧・生きている\n行では省略（NULL）。常に UTC（\"Z\" 終端の RFC3339）で返す。\n'),
  "createdAt": zod.string().datetime({"offset":true}).describe('常に UTC（\"Z\" 終端の RFC3339）で返す。')
})
export const ListRecordingsResponse = zod.array(ListRecordingsResponseItem)


/**
 * 一覧要素（`GET /api/recordings` の各要素）と同形。単体ページ・skip 理由や
 * 予約からの導線が着地する先。
 *
 * **ごみ箱（`deleted_at IS NOT NULL`）の録画も 200 で返す。** メディア配信の
 * 404 契約（`recordings.deleted_at IS NOT NULL` を 404 にする。
 * docs/api/media.md）とメタデータの可視性は別の判断 --- 一覧が
 * `trash=true` で既にごみ箱の録画のメタデータを 200 で返しているため、
 * 単体 GET だけ厳しくする理由が無い。単体ページ（`/recordings/$id`）は
 * この `deletedAt` を見て再生系（プレイヤー・原本リンク）を出さない
 * （docs/frontend/recordings.md）。
 *
 * **完全削除（purge）済みの tombstone（`purged_at` が立った行、issue
 * #135）は 404。** ファイルが既に無く、通常一覧・ごみ箱一覧のどちらにも
 * 現れない行なので、単体 GET だけ見える形にしない。
 *
 * ごみ箱の行では一覧と同じく `encodedAssets` を省略する
 * （一覧・単体とも常に射影し、Go 側で落とす。プレイヤーを出さないので
 * 揃える必要が無い）。
 * @summary Get a single recording by id
 */
export const GetRecordingParams = zod.object({
  "id": zod.number()
})

export const GetRecordingResponse = zod.object({
  "id": zod.number(),
  "site": zod.string().describe('この録画がどのサイト（mirakc インスタンス）のものか。`recordings.site`\nそのまま。`GET \/api\/recordings` は全サイトの録画を返すため\n（issue #184 M4-12）、クライアントはこの値で区別する。\n'),
  "ruleId": zod.number().optional(),
  "source": zod.enum(['rule', 'manual']),
  "serviceName": zod.string(),
  "channelType": zod.enum(['GR', 'BS', 'CS', 'SKY']),
  "channel": zod.string(),
  "networkId": zod.number(),
  "serviceId": zod.number(),
  "eventId": zod.number(),
  "title": zod.string(),
  "description": zod.string().optional(),
  "startAt": zod.string().datetime({"offset":true}).describe('番組の放送開始時刻。常に UTC（\"Z\" 終端の RFC3339）で返す。'),
  "durationMs": zod.number(),
  "status": zod.enum(['recording', 'finished', 'canceled', 'failed']),
  "startedAt": zod.string().datetime({"offset":true}).optional().describe('録画の実開始時刻。常に UTC（\"Z\" 終端の RFC3339）で返す。'),
  "endedAt": zod.string().datetime({"offset":true}).optional().describe('録画の実終了時刻。常に UTC（\"Z\" 終端の RFC3339）で返す。'),
  "sizeBytes": zod.number().optional().describe('原本の実サイズ。ingest 済み（media_assets 行あり）の場合のみ。\n省略は「まだ取り込めていない」と「取り込んだ後に削除した」の両方を\n含むので、区別が要るときは `ingest.state` を見る（issue #211 \/\n#212）。\*\*転送中の途中ファイルのサイズはここに混ぜない\*\*（コミット =\nDB 行。不変条件 3）--- 途中経過は `ingest.writtenBytes`。\n'),
  "encodedAssets": zod.array(zod.object({
  "profile": zod.string(),
  "sizeBytes": zod.number().optional().describe('encoded 派生物の実サイズ。`media_assets.size_bytes` は NOT NULL\nなので active な行が存在する限り常に付く（未検証の断言にしないため:\n`media_assets.size_bytes` 列の `NOT NULL` 制約が根拠、実行時計測\nではない。同テーブルの CHECK は\n`kind` \/ `profile` \/ `state` に掛かるものだけで `size_bytes` には\n無い）。省略可能にしているのは、サイズが取れない資産があっても\n選択肢そのものは隠さない（ドロップ統計の「分類できなかった PID」と\n同じ判断。docs\/frontend\/recordings.md）という UI 側の表示規律を\n型で表現するため。\n')
})).optional().describe('再生可能な encoded 派生物（media_assets の active のみ）。\nブラウザ再生は GET \/api\/recordings\/{id}\/file?profile=<name> を使う。\ndesired（encodeProfiles）ではなく observed。空配列は省略可。\n'),
  "encodeProfiles": zod.array(zod.string()).optional().describe('凍結された「望ましい」エンコードプロファイル一覧（desired。\nrecordings.encode_profiles）。ingest 完了時に一度だけ焼き込まれ、以後は\n`POST \/api\/recordings\/{id}\/encode-profiles` による事後追加（凍結の例外。\ndocs\/storage.md §6「原本 TS の保持ポリシー」）でのみ増える。\n`encodedAssets`（observed、再生可能なもの）とは異なり、まだ完了して\nいない pending なジョブのプロファイルも含む --- UI が「追加済み」を\n判定するのに使う。空配列は省略可。\n'),
  "encodeStatus": zod.array(zod.object({
  "profile": zod.string(),
  "state": zod.enum(['queued', 'running', 'failed']).describe('\*\*サーバー側で recording_encode_attempts（衛星表）から毎回導出する\*\*\n（列に焼いた値ではない）。River の river_job は直接露出しない\n（docs\/schema.md の recording_encode_attempts の節を参照。\ndocs\/recording\/ingest.md §5.6 と共通なのは「river_job を露出しない」\nことだけで、§5.6 の「リトライ中と待ちを区別しない」判断とは逆に\nこの表は区別する）。\n\n- `queued`: まだ 1 度も試行が始まっていない（試行行が無い状態）。\n  \*\*一度 `running`\/`failed` を書いた行は成功するまで消えないので、\n  失敗後に `queued` へ戻ることはない\*\*。「来る根拠」の無い\n  `queued` は出さない --- ごみ箱の録画（ジョブが二度と投入されない）\n  と、api が現在の設定にあるプロファイル一覧を知っていて、かつ\n  そのプロファイルが設定から消えていて試行行も無い場合は、この\n  プロファイルの要素自体が省略される\n- `running`: いま ffmpeg が走っている\n- `failed`: 直前の試行が失敗した。\*\*`failed` は「二度と来ない」の\n  断定ではない\*\* --- 失敗したジョブはジョブキューの既定のリトライ\n  上限（25 回。上書きしていない）まで再実行され、その各試行の先頭で\n  `running` に戻る。上限に達した後も、encoded 資産が無い状態が続く\n  限り EncodeReconcileWorker が 15 分ごとに再投入する。例外は設定\n  から消えたプロファイルで、これは EncodeReconcileWorker の既知\n  プロファイル絞り込みが投入対象から外すため、リトライ上限に達した\n  ところで `failed` に留まる（\*\*`failed` に固定されるのはリトライを\n  使い切った後で、最初の失敗の時点ではない\*\*）\n')
})).optional().describe('完了していないエンコードプロファイルの試行状態（issue #316）。\n`encodeProfiles`（desired）のうち `encodedAssets`（observed、\n再生可能）にまだ現れていないプロファイルだけを列挙する ---\n完了したプロファイルはここに出さず `encodedAssets` の存在で示す\n（2 つの配列に同じプロファイルが同時に出ることはない）。\n\nプロファイルを 1 つも設定していない録画・全プロファイルが完了\n済みの録画では省略する（空配列は返さない。機能しないキュー画面や\n空の進捗バーを出さない判断はサーバー側のこの省略で表現する）。\n\n`%` は含まない --- この REST モデルは `queued` \/ `running` \/\n`failed` \/ 完了を復元する durable な状態だけを持つ。実行中の割合は\nnotifier の `\/api\/events` が `encode-progress` SSE として配送する\n揮発テレメトリで、テーブルにも OpenAPI にも保存しない。\n'),
  "dropSummary": zod.object({
  "packets": zod.number(),
  "drops": zod.number(),
  "errors": zod.number(),
  "scrambled": zod.number()
}).optional(),
  "ingest": zod.object({
  "state": zod.enum(['committed', 'transferring', 'pending', 'unknown']).describe('原本の取り込みの粗い状態。\*\*サーバー側で DB 行から毎回導出する\*\*\n（列に焼いた値ではない）。優先順に:\n\n- `committed`: `kind=\'original\'` の `media_assets` 行が存在する。\n  取り込みは少なくとも 1 回完了した。その原本が\*\*いま\*\*あるかどうかは\n  `sizeBytes` の有無で見る（`state=\'deleted\'` の原本でもここは\n  `committed` のまま --- 「取り込めなかった」と「取り込んだ後に\n  消した」を混同しないため。issue #211）\n- `transferring`: 原本行が無く、転送の進捗行がある。`writtenBytes` \/\n  `observedAt` が付く。`observedAt` が古いまま止まっていれば停滞して\n  いる（River のバックオフ待ち・ストール）\n- `pending`: 原本行も進捗行も無く、\*\*ingest ジョブが投入される\n  はずの\*\* mirakc record の観測（`record_sync.status = \'finished\'`。\n  watcher が ingest を投入する条件と同じ述語）がある。取り込み待ち、\n  または失敗して再試行待ち\n- `unknown`: 上のどれでもない。取り込みが始まった観測が無い ---\n  mirakc record が観測されていないか、record が `finished` でない\n  （録画中・`failed`・`canceled`。\*\*この録画に ingest ジョブは\n  投入されない\*\*）\n\n\*\*`pending` は「これから来る」の断定なので、来る根拠が無いものは\n入れない。\*\* `record_sync` 行の存在だけを根拠にすると、`failed` \/\n`canceled` の録画（ingest が一度も投入されず、`record_sync` 行も\n消えない）が永久に「取り込み待ち」を名乗る。\n\n\*\*「リトライ中」を `pending` と区別する値は持たない。\*\* 区別するには\nRiver の `river_job` を API 契約に露出させる（内部実装の露出）か、\n失敗の観測という別寿命の値を進捗行に混ぜる（不変条件 9 \/ 12）\n必要があり、どちらも取らなかった。停滞は `observedAt` の古さで読む。\n'),
  "writtenBytes": zod.number().optional().describe('転送先ファイルに書けたバイト数。`state = transferring` のときだけ付く。\n\n\*\*これは「いまファイルに書けているバイト数」であって累積の転送実績\nではない。\*\* ジョブ再試行（部分ファイルを truncate してゼロから\n作り直す。docs\/recording\/ingest.md §5.3 の層 2）で 0 に戻ることが\nある。戻りを隠さないのは、隠すと「進んでいるのに終わらない」に見えて\n実際に起きているやり直しが観測できなくなるため。\n\n\*\*`sizeBytes`（原本の実サイズ）とは別のフィールドである。\*\* コミット =\nDB 行（不変条件 3）なので、コミット前の途中ファイルのサイズを\n`sizeBytes` に混ぜない。\n'),
  "expectedBytes": zod.number().optional().describe('転送の分母。`record_sync.content_length`（watcher が mirakc record の\n`content.length` として観測した値）を転送開始時に写したもの。mirakc が\nlength を返していなければ\*\*省略する\*\* --- でっち上げた分母を置かない。\n省略時、UI は % を出さず `writtenBytes` だけを出す。\n'),
  "observedAt": zod.string().datetime({"offset":true}).optional().describe('進捗を最後に観測した時刻。`state = transferring` のときだけ付く。\n現在時刻との差が開いていれば転送は停滞している。常に UTC\n（\"Z\" 終端の RFC3339）で返す。\n')
}).optional(),
  "qualityEvents": zod.array(zod.object({

}).passthrough()).optional().describe('recording.failed \/ record-broken \/ bcas_anomaly の履歴'),
  "deletedAt": zod.string().datetime({"offset":true}).optional().describe('論理削除時刻。ごみ箱一覧（`trash=true`）と `GET \/api\/recordings\/{id}`\n（ごみ箱の録画も 200 で返す）でのみ出現する。通常一覧・生きている\n行では省略（NULL）。常に UTC（\"Z\" 終端の RFC3339）で返す。\n'),
  "createdAt": zod.string().datetime({"offset":true}).describe('常に UTC（\"Z\" 終端の RFC3339）で返す。')
})


/**
 * 論理削除。`recordings.deleted_at = now()` を立てるだけ。ファイルには触れない
 * （docs/storage.md「ごみ箱 = 論理削除」）。既に削除済みなら冪等に 204。
 * 行が無ければ 404。
 * @summary Soft-delete a recording (move to trash)
 */
export const DeleteRecordingParams = zod.object({
  "id": zod.number()
})

export const DeleteRecordingResponse = zod.void()


/**
 * `deleted_at` を消し、即時削除の要求（`recording_purge_requests` の行）を
 * 取り消すだけ（ファイル操作ゼロ・即時）。
 * ごみ箱に入っていない、または行が無い場合は 404。
 * 同一イベントに生きている録画があると partial unique index で衝突し 409。
 * @summary Restore a soft-deleted recording from trash
 */
export const RestoreRecordingParams = zod.object({
  "id": zod.number()
})

export const RestoreRecordingResponse = zod.void()


/**
 * 即時物理削除の要求。`recording_purge_requests` に行を入れ、未 soft-delete
 * なら `deleted_at` も同時に立てる。**ファイルは消さない**（M3-8 の削除
 * reconcile がこの要求を拾って unlink する）。既に要求済みでも冪等に 204。
 * @summary Mark a recording for immediate physical purge
 */
export const PurgeRecordingParams = zod.object({
  "id": zod.number()
})

export const PurgeRecordingResponse = zod.void()


/**
 * `recordings.encode_profiles` は ingest 完了時に一度だけ焼き込まれる凍結値
 * だが（docs/storage.md §6「原本 TS の保持ポリシー」）、ユーザー起点の事後
 * 追加だけは凍結の例外として認める（issue #133）。**追加専用**（union +
 * dedup）で書き、全置換にはしない --- 誤って他プロファイルの指定を消す事故を
 * 避けるため。
 *
 * 原本の media_assets 行が `state = 'active'` でない録画には 409 を返す。
 * これは次のいずれかに当たる --- 本当に削除済み（`keep_original=until_encoded`
 * でエンコード完了後に原本削除 reconcile が消した等）、`state = 'deleting'`
 * （unlink 待ち。一覧では「原本あり」に見えるが事後追加は決定的に 409 になる）、
 * またはそもそも ingest が完了しておらず original 行自体が無い。この場合
 * `EnqueueMissingEncodes` は黙って no-op になるため、api 層で明示的に
 * 検査してサイレントな失敗にしない。
 *
 * 既に完了済み/pending のプロファイル名を再指定してもエラーにはならず
 * （River の UniqueOpts が二重投入を防ぐ）、冪等に 204 を返す。
 * @summary Request additional encode profiles for an already-ingested recording
 */
export const AddRecordingEncodeProfilesParams = zod.object({
  "id": zod.number()
})




export const AddRecordingEncodeProfilesBody = zod.object({
  "profiles": zod.array(zod.string()).min(1).describe('追加したいエンコードプロファイル名（config.encode.profiles に定義された\n名前のみ許可。未知名は 400）。既存の recordings.encode_profiles には\n\*\*追加専用\*\*（union + dedup）で書かれ、全置換にはならない --- 既存の\n指定を消す事故を避けるため。空配列は 400。\n')
})

export const AddRecordingEncodeProfilesResponse = zod.void()


/**
 * @summary Get per-PID drop statistics for a recording
 */
export const ListRecordingDropStatsParams = zod.object({
  "id": zod.number()
})

export const ListRecordingDropStatsResponseItem = zod.object({
  "pid": zod.number(),
  "packets": zod.number(),
  "drops": zod.number(),
  "errors": zod.number(),
  "scrambled": zod.number(),
  "pidType": zod.string().optional().describe('PID 種別（M2-13, issue #24）。\*\*値はすべて小文字\*\*で、権威は Go 側の定数\n（`internal\/tsstat`）。enum にしないのは分類の追加をスキーマ変更なしで\nできるようにするため（`drop_stats.pid_type` に CHECK を置かないのと同じ理由）。\n\n- `video` \/ `audio` --- PMT の stream_type から分類した ES\n- `other` --- PMT に載っているが映像でも音声でもない ES（字幕・文字スーパー・\n  データ放送はすべてここ。記述子を読まないため字幕と文字スーパーは区別しない）\n- `pat` \/ `cat` \/ `nit` \/ `sdt` \/ `eit` \/ `tot` --- 固定 PID（静的表。解析不要）\n- `pmt` --- PAT が PMT の在り処として指した PID\n\n\*\*分類できなければ省略する\*\*（PSI 解析の失敗は ingest を失敗させない。\ndocs\/recording.md「例外の境界」）。省略は「分類しなかった」であって\n「該当なし」ではない\n')
})
export const ListRecordingDropStatsResponse = zod.array(ListRecordingDropStatsResponseItem)


/**
 * チューナーが不足している**区間**を結合済みで返す（M2-10、issue #21 /
 * docs/data.md §6.5）。
 *
 * **主張は下界に限る。** 「この区間は超過している」は確実だが、返らなかった
 * 区間が「収まる」ことは保証しない。Rokuban から見えない消費者（並走する
 * EPGStation・ライブ視聴・EPG 収集ジョブ）がいるうえ、mirakc の
 * `excluded_channels` は `/api/tuners` に載らないため、既知の盲点はすべて
 * 「警告を見逃す」方向に偏っている。**沈黙を「大丈夫」と読ませてはならない。**
 *
 * 返すのは区間の性質だけで、**どの番組が負けるかは主張しない**。勝敗を決めるのは
 * mirakc であり、Rokuban には見えない消費者がいるので予測できない。UI の文言も
 * 「この予約は競合しています」ではなく「この時間帯はチューナーが不足しています」。
 *
 * 需要の単位は予約件数ではなく**異なる物理チャンネル数**（同一物理チャンネルなら
 * 1 本のチューナーに相乗りできる。副産物としてマルチ編成のサブサービスが
 * 自然に畳まれる）。数えるのは reconciler が実際に schedule を作る予約だけで、
 * `effective.skip` が true の行と `state = 'orphaned'` の行は需要にならない。
 *
 * 判定は種別部分集合に縮約した Hall 条件（`∀A ⊆ {GR,BS,CS,SKY}:
 * Σ_{t∈A} d[t] ≤ cap(A)`）。破れた `A` から不足本数と詰まった種別が
 * 副産物として出るので、`shortfall` / `jammedTypes` で「BS が 1 本不足」まで言える。
 *
 * 判定はサイトごとに独立に行われ、**全サイトの超過区間を返す**
 * （issue #184 M4-12）。各要素の `site` で区別する。
 * @summary List intervals where tuner capacity is exceeded
 */
export const ListCapacityOveragesQueryParams = zod.object({
  "start": zod.string().datetime({"offset":true}).describe('時間窓の開始（この時刻より後に終わる区間が対象）'),
  "end": zod.string().datetime({"offset":true}).describe('時間窓の終了（この時刻より前に始まる区間が対象）')
})

export const ListCapacityOveragesResponseItem = zod.object({
  "site": zod.string().describe('判定はサイトごとに独立して行う。N 予約の決定（docs\/recording.md §3.1）に\nより予約が site に束縛されるため二部グラフがサイトごとに非連結になり、\nHall の条件を成分ごとに確認すれば十分になる。\n'),
  "startAt": zod.string().datetime({"offset":true}),
  "endAt": zod.string().datetime({"offset":true}),
  "shortfall": zod.number().describe('不足本数。破れた種別部分集合 A の `Σ_{t∈A} d[t] − cap(A)` の最大値。\n1 以上（0 なら超過していないので区間そのものが返らない）\n'),
  "jammedTypes": zod.array(zod.enum(['GR', 'BS', 'CS', 'SKY'])).describe('詰まった種別（Hall 条件を破った部分集合 A）。「BS が 1 本不足」と言うための材料')
})
export const ListCapacityOveragesResponse = zod.array(ListCapacityOveragesResponseItem)


/**
 * River の active な encode ジョブを待機中と実行中に分けて数える。
 * `queued` は `available` / `pending` / `scheduled` / `retryable`、
 * `running` は実行中。録画 1 本に複数プロファイルがあれば複数件になる。
 *
 * ffmpeg の進捗率を運ぶ `encode-progress` SSE は揮発テレメトリであり、
 * 待機件数には使わない。River の内部状態名はこの API の外へ出さず、
 * UI が必要とする 2 分類だけを返す。
 * @summary Get active encode job counts
 */
export const getEncodeQueueResponseQueuedMin = 0;

export const getEncodeQueueResponseRunningMin = 0;



export const GetEncodeQueueResponse = zod.object({
  "queued": zod.number().min(getEncodeQueueResponseQueuedMin).describe('待機中（available \/ pending \/ scheduled \/ retryable）のジョブ数。'),
  "running": zod.number().min(getEncodeQueueResponseRunningMin).describe('実行中のジョブ数。')
}).describe('active なエンコードジョブの件数（録画 × プロファイル単位）。')


/**
 * `storage.media_dir`（アーカイブ）と `storage.scratch_dir`（ローカルスクラッチ）の
 * 容量観測（issue #238 M7-5）。api ロールはファイルシステムに依存しない
 * （不変条件 1）ので、ファイルシステムを持つ worker が定期的に statfs 相当で
 * 観測して DB に射影し、ここはその射影を読むだけ。
 *
 * 毎パス全量を作り直す観測値であり、過去の観測を積むログではない
 * （不変条件 9）。`observedAt` は「最後にいつ観測できたか」を表し、UI が
 * 鮮度を示すために必ず使う --- 観測ループが止まっていても行は消えない
 * ので、鮮度が古いことだけが異常の手がかりになる（沈黙は保証ではない）。
 *
 * `scratch` は `storage.scratch_dir` が設定されているときだけ現れる
 * （空文字列に設定を変えると、次の観測パスで消える）。`media` は
 * `storage.media_dir` が必須なので常に現れるはずだが、初回の観測パスが
 * まだ走っていない/失敗し続けている場合は配列が空になることもある。
 * @summary Get observed storage usage
 */
export const GetStorageResponseItem = zod.object({
  "root": zod.enum(['media', 'scratch']).describe('config キー（`storage.media_dir` \/ `storage.scratch_dir`）と 1:1。\n'),
  "path": zod.string().describe('観測対象の絶対パス（config の値そのもの）。他のフィールドと同じく\n`observedAt` 時点のスナップショット --- config の path を変更した\n直後に statfs が失敗すると、次の成功する観測まで\*\*古い path のまま\*\*\n残る（バイト数も同様に古い値のまま）。現在の設定を保証しない。\n'),
  "totalBytes": zod.number().describe('ファイルシステム全体の容量（`observedAt` 時点のスナップショット。\n`path` の説明を参照）。\n'),
  "usedBytes": zod.number().describe('root 予約領域を使用済み側に数えた使用量（total - free）。\n`observedAt` 時点のスナップショット。\n'),
  "availableBytes": zod.number().describe('非特権プロセスが実際に書き込める残量（statfs の Bavail）。\n「残高」として UI に出すべき数字はこちら。`observedAt` 時点の\nスナップショット。\n'),
  "observedAt": zod.string().datetime({"offset":true}).describe('この行を最後に観測できた時刻。観測ループが止まっていても行は\n消えないため、この値の鮮度だけが異常の手がかりになる。\n')
}).describe('1 つのストレージ root（`storage.media_dir` または `storage.scratch_dir`）の\n容量観測 1 件（`storage_sync` 行そのもの。issue #238 M7-5）。\n')
export const GetStorageResponse = zod.array(GetStorageResponseItem)


/**
 * 大量削除サーキットブレーカー（docs/recording.md §3.2）の発動状態。
 * **行の存在 = 発動中**なので、発動していないブレーカーは結果に現れない
 * （すべて停止していなければ空配列）。
 *
 * `detail` は発動時に「何が消されようとしていたか」を説明する抜粋で、
 * 手動確認の材料（`internal/breaker.Sample` と同じ形。最大 20 件）。
 *
 * site はパスに含めない。全サイトの発動を一望する用途のエンドポイントで、
 * レスポンスの各要素に site フィールドがある（issue #102）。ただし
 * `internal/breaker.IsSiteless` が true の名前（`delete_reconcile`）の
 * 行は、その資源自体が site を持たないため `site` が空文字列になる
 * （issue #450）。個別の再開は、site を持つ名前なら
 * `POST /api/sites/{site}/breakers/{name}/resume`、site を持たない名前
 * なら `POST /api/breakers/{name}/resume`。
 * @summary List tripped circuit breakers
 */
export const ListCircuitBreakersResponseItem = zod.object({
  "site": zod.string().describe('この行が属する site。`internal\/breaker.IsSiteless` が true の名前\n（`delete_reconcile`）は資源自体が site を持たないため空文字列\nになる（issue #450）。その場合の再開は\n`POST \/api\/breakers\/{name}\/resume`、それ以外は\n`POST \/api\/sites\/{site}\/breakers\/{name}\/resume`。\n'),
  "name": zod.enum(['ruler_deletes', 'reconcile_total_loss', 'delete_reconcile']).describe('internal\/breaker の定数（RulerDeletes \/ ReconcileTotalLoss \/\nDeleteReconcile）。値の権威は internal\/breaker.All\n（internal\/breaker\/breaker.go）で、この enum はそれを手で複製した\nものなので、breaker.All に定数を足したときはここも合わせて直す。\n\nずれの検知は 2 段構え: internal\/breaker パッケージのエクスポート\n済み文字列定数と All 自体の一致は internal\/breaker の AST テスト\n（TestAll_MatchesDeclaredConstants）が見る。All とこの enum の\n一致は internal\/api の純ユニットテスト\n（TestBreakerAllNamesAreValidCircuitBreakerNameEnumMembers。\nCircuitBreakerName.Valid() 経由）が見る。後者を GET \/api\/breakers\nの runtime チェックにはしていない —— 消費者\n（web\/src\/components\/circuit-breaker-banner.tsx・web\/src\/pages\/home.tsx）\nが isError を見ておらず、enum 外の 1 行のせいで一覧全体を 500 に\nすると発動中の他のブレーカーまで隠れてしまうため（issue #199 の\nレビューで指摘）。\n'),
  "trippedAt": zod.string().datetime({"offset":true}).describe('発動した時刻（最初の発動時刻。再発動で更新されるのは pending \/\nthreshold \/ detail のみ）。\n'),
  "pending": zod.number().describe('発動時に止めた削除の件数。'),
  "threshold": zod.number().describe('発動時の閾値。'),
  "detail": zod.object({
  "total": zod.number().describe('止めた削除の総数。'),
  "programs": zod.array(zod.object({
  "programId": zod.number(),
  "title": zod.string().optional()
})).optional().describe('先頭いくつかの抜粋（`internal\/breaker.MaxSampleSize` 件まで）。')
}).describe('発動時に「何が消されようとしていたか」を説明する抜粋\n（`internal\/breaker.Sample` と同じ形。手動確認の材料）。\n')
}).describe('発動中の大量削除サーキットブレーカー 1 件（`circuit_breakers` 行 = 発動中。\ndocs\/recording.md §3.2）。\n')
export const ListCircuitBreakersResponse = zod.array(ListCircuitBreakersResponseItem)


/**
 * 手動確認後の再開。ブレーカーは人間が確認するまで止まり続けるラッチ
 * （docs/recording.md §3.2）なので、確認が済んだことをこの API で明示する。
 *
 * `DELETE /api/sites/{site}/breakers/{name}` にしていないのは、運用者から
 * 見た操作が「行を削除する」ではなく「**確認したので再開する**」であるため。
 * DB の行が消えるのは実装詳細（`internal/breaker` のラッチが行の存在で
 * 表される、という設計の帰結）であり、URL に出す概念ではない。
 *
 * site をパスに含めるのは、資源の PK が `(site, name)` であるため
 * （issue #102）。`GET /api/breakers` はサイト横断の一覧に価値があるので
 * グローバルのまま残すが、再開は行 1 件を特定する操作なので PK と
 * 一致させる。
 *
 * site を持たない名前（`delete_reconcile`）を渡すと 400 ---
 * `POST /api/breakers/{name}/resume` を使う（issue #450）。
 * @summary Resume a tripped circuit breaker that has a site (manual acknowledgement)
 */
export const ResumeCircuitBreakerParams = zod.object({
  "site": zod.string().describe('mirakc インスタンスのサイト名。programId はインスタンス単位のスコープ\nしか持たないため、この site と組にしないと資源が一意に定まらない\n（issue #31）。api プロセス自身は特定の site に束縛されない\n（不変条件 1: mirakc にもファイルシステムにも依存しない）ので、権威は\n「`config.mirakc`\/`mirakcs` レジストリに存在するか」であり、1 プロセスが\nレジストリの全 site を処理できる（issue #184 M4-12）。レジストリに無い\nsite のエラーコードはエンドポイントの HTTP メソッドで決まる —— GET 系は\n404、POST\/PUT\/PATCH\/DELETE 系は 400（他の入力検証と同じ扱い。詳細は各\nエンドポイントの description・レスポンス定義を参照）。存在する site の\n一覧は `GET \/api\/sites` で取得できる。\n'),
  "name": zod.string().describe('site を持つブレーカー識別子（`internal\/breaker` の定数のうち\n`internal\/breaker.IsSiteless` が false のもの。`ruler_deletes` \/\n`reconcile_total_loss`）。未知の値、および site を持たない名前\n（`delete_reconcile`）は 400 --- 後者は\n`POST \/api\/breakers\/{name}\/resume` を使う（issue #450）。\n')
})

export const ResumeCircuitBreakerResponse = zod.void()


/**
 * site を持たないブレーカー専用の再開エンドポイント
 * （`internal/breaker.IsSiteless`。今のところ `delete_reconcile` のみ）。
 * 理由と経緯は `internal/worker/delete_reconcile.go` の
 * `DeleteReconcileWorker` doc コメント参照（issue #450）。
 *
 * site を持つ名前（`ruler_deletes` / `reconcile_total_loss`）を渡すと
 * 400 --- `POST /api/sites/{site}/breakers/{name}/resume` を使う。
 * @summary Resume a tripped circuit breaker that has no site (manual acknowledgement)
 */
export const ResumeSitelessCircuitBreakerParams = zod.object({
  "name": zod.string().describe('site を持たないブレーカー識別子（`internal\/breaker.IsSiteless` が\ntrue のもの。今のところ `delete_reconcile` のみ）。未知の値、および\nsite を持つ名前（`ruler_deletes` \/ `reconcile_total_loss`）は 400 ---\n後者は `POST \/api\/sites\/{site}\/breakers\/{name}\/resume` を使う。\n')
})

export const ResumeSitelessCircuitBreakerResponse = zod.void()
