// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chapters.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const catalogInsertRecordingChapterSpan = `-- name: CatalogInsertRecordingChapterSpan :exec
INSERT INTO recording_chapter_spans (recording_id, span, label, cut)
VALUES (
    $1,
    int8range($2::bigint, $3::bigint),
    $4,
    $5
)
ON CONFLICT DO NOTHING
`

type CatalogInsertRecordingChapterSpanParams struct {
	RecordingID int64
	StartMs     int64
	EndMs       int64
	Label       *string
	Cut         bool
}

// 所有の行を先に upsert してから呼ぶ（FK 先）。主キーが無く、同じ区間を 2 回
// 入れると EXCLUDE が自分自身と衝突するので DO NOTHING で受ける（同じ世代を
// 2 回当てても rescue が落ちない）。
func (q *Queries) CatalogInsertRecordingChapterSpan(ctx context.Context, arg CatalogInsertRecordingChapterSpanParams) error {
	_, err := q.db.Exec(ctx, catalogInsertRecordingChapterSpan,
		arg.RecordingID,
		arg.StartMs,
		arg.EndMs,
		arg.Label,
		arg.Cut,
	)
	return err
}

const catalogListRecordingChapterOwnerships = `-- name: CatalogListRecordingChapterOwnerships :many

SELECT recording_id, adopted_at
FROM recording_chapter_ownership
ORDER BY recording_id
`

// ---------------------------------------------------------------------------
// catalog（export / rescue）
// ---------------------------------------------------------------------------
// ユーザーの手作業（不可逆）なので rescue で戻す。所有の行が無い録画は
// 自動層のまま = 何も復元しない（行の不在そのものが意味を持つ。不変条件 10）。
func (q *Queries) CatalogListRecordingChapterOwnerships(ctx context.Context) ([]RecordingChapterOwnership, error) {
	rows, err := q.db.Query(ctx, catalogListRecordingChapterOwnerships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecordingChapterOwnership
	for rows.Next() {
		var i RecordingChapterOwnership
		if err := rows.Scan(&i.RecordingID, &i.AdoptedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogListRecordingChapterSpans = `-- name: CatalogListRecordingChapterSpans :many
SELECT recording_id, lower(span)::bigint AS start_ms, upper(span)::bigint AS end_ms, label, cut
FROM recording_chapter_spans
ORDER BY recording_id, lower(span)
`

type CatalogListRecordingChapterSpansRow struct {
	RecordingID int64
	StartMs     int64
	EndMs       int64
	Label       *string
	Cut         bool
}

func (q *Queries) CatalogListRecordingChapterSpans(ctx context.Context) ([]CatalogListRecordingChapterSpansRow, error) {
	rows, err := q.db.Query(ctx, catalogListRecordingChapterSpans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogListRecordingChapterSpansRow
	for rows.Next() {
		var i CatalogListRecordingChapterSpansRow
		if err := rows.Scan(
			&i.RecordingID,
			&i.StartMs,
			&i.EndMs,
			&i.Label,
			&i.Cut,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogUpsertRecordingChapterOwnership = `-- name: CatalogUpsertRecordingChapterOwnership :exec
INSERT INTO recording_chapter_ownership (recording_id, adopted_at)
VALUES ($1, $2)
ON CONFLICT (recording_id) DO UPDATE SET
    adopted_at = EXCLUDED.adopted_at
`

type CatalogUpsertRecordingChapterOwnershipParams struct {
	RecordingID int64
	AdoptedAt   time.Time
}

func (q *Queries) CatalogUpsertRecordingChapterOwnership(ctx context.Context, arg CatalogUpsertRecordingChapterOwnershipParams) error {
	_, err := q.db.Exec(ctx, catalogUpsertRecordingChapterOwnership, arg.RecordingID, arg.AdoptedAt)
	return err
}

const deleteRecordingChapterOwnership = `-- name: DeleteRecordingChapterOwnership :exec
DELETE FROM recording_chapter_ownership WHERE recording_id = $1
`

// 自動に戻す。spans は ON DELETE CASCADE で一緒に落ちる。
func (q *Queries) DeleteRecordingChapterOwnership(ctx context.Context, recordingID int64) error {
	_, err := q.db.Exec(ctx, deleteRecordingChapterOwnership, recordingID)
	return err
}

const deleteRecordingChapterSpans = `-- name: DeleteRecordingChapterSpans :exec
DELETE FROM recording_chapter_spans WHERE recording_id = $1
`

func (q *Queries) DeleteRecordingChapterSpans(ctx context.Context, recordingID int64) error {
	_, err := q.db.Exec(ctx, deleteRecordingChapterSpans, recordingID)
	return err
}

const getRecordingCMRangesJSON = `-- name: GetRecordingCMRangesJSON :one
SELECT COALESCE(
    jsonb_agg(
        jsonb_build_object('startMs', lower(cr.cm_range), 'endMs', upper(cr.cm_range))
        ORDER BY lower(cr.cm_range)
    ),
    '[]'::jsonb
)::jsonb AS ranges
FROM recording_cm_detections d
CROSS JOIN LATERAL unnest(d.cm_ranges) AS cr(cm_range)
WHERE d.recording_id = $1
`

// 自動層の CM 区間。ms の半開区間。行が無ければ空配列を返す（COALESCE が要る
// --- 集約は行が無いと NULL になる）。
func (q *Queries) GetRecordingCMRangesJSON(ctx context.Context, recordingID int64) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getRecordingCMRangesJSON, recordingID)
	var ranges json.RawMessage
	err := row.Scan(&ranges)
	return ranges, err
}

const getRecordingChapterSpansJSON = `-- name: GetRecordingChapterSpansJSON :one
SELECT COALESCE(
    jsonb_agg(
        jsonb_build_object('startMs', lower(s.span), 'endMs', upper(s.span), 'label', s.label, 'cut', s.cut)
        ORDER BY lower(s.span)
    ),
    '[]'::jsonb
)::jsonb AS spans
FROM recording_chapter_spans s
WHERE s.recording_id = $1
`

// ユーザー層。行が無ければ空配列。label は NULL を保つ（sqlc のポインタ型）。
func (q *Queries) GetRecordingChapterSpansJSON(ctx context.Context, recordingID int64) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getRecordingChapterSpansJSON, recordingID)
	var spans json.RawMessage
	err := row.Scan(&spans)
	return spans, err
}

const getRecordingChapterState = `-- name: GetRecordingChapterState :one

SELECT COALESCE(p.cm_detect, false)::boolean AS cm_detect,
       r.program_duration_ms,
       EXISTS (SELECT 1 FROM recording_cm_detections d WHERE d.recording_id = r.id) AS detected,
       EXISTS (
           SELECT 1 FROM recording_cm_attempts ca
           WHERE ca.recording_id = r.id AND ca.state = 'failed'
       ) AS failed,
       EXISTS (
           SELECT 1 FROM recording_chapter_ownership o WHERE o.recording_id = r.id
       ) AS owned
FROM recordings r
LEFT JOIN recording_encode_policy p ON p.recording_id = r.id
WHERE r.id = $1
  AND r.purged_at IS NULL
`

type GetRecordingChapterStateRow struct {
	CmDetect          bool
	ProgramDurationMs int64
	Detected          bool
	Failed            bool
	Owned             bool
}

// ---------------------------------------------------------------------------
// 読む
// ---------------------------------------------------------------------------
func (q *Queries) GetRecordingChapterState(ctx context.Context, recordingID int64) (GetRecordingChapterStateRow, error) {
	row := q.db.QueryRow(ctx, getRecordingChapterState, recordingID)
	var i GetRecordingChapterStateRow
	err := row.Scan(
		&i.CmDetect,
		&i.ProgramDurationMs,
		&i.Detected,
		&i.Failed,
		&i.Owned,
	)
	return i, err
}

const insertRecordingChapterSpan = `-- name: InsertRecordingChapterSpan :exec
INSERT INTO recording_chapter_spans (recording_id, span, label, cut)
VALUES (
    $1,
    int8range($2::bigint, $3::bigint),
    $4,
    $5
)
`

type InsertRecordingChapterSpanParams struct {
	RecordingID int64
	StartMs     int64
	EndMs       int64
	Label       *string
	Cut         bool
}

func (q *Queries) InsertRecordingChapterSpan(ctx context.Context, arg InsertRecordingChapterSpanParams) error {
	_, err := q.db.Exec(ctx, insertRecordingChapterSpan,
		arg.RecordingID,
		arg.StartMs,
		arg.EndMs,
		arg.Label,
		arg.Cut,
	)
	return err
}

const lockRecording = `-- name: LockRecording :one


SELECT id,
       (deleted_at IS NOT NULL)::boolean AS is_trashed,
       (purged_at IS NOT NULL)::boolean AS is_purged
FROM recordings
WHERE id = $1
FOR UPDATE
`

type LockRecordingRow struct {
	ID        int64
	IsTrashed bool
	IsPurged  bool
}

// チャプターの所有モデル。自動層（recording_cm_detections）は導出値、
// ユーザー層（recording_chapter_ownership + recording_chapter_spans）は
// 二度と再取得できない事実。所有の行がある録画では自動層を読まない。
// ---------------------------------------------------------------------------
// 行ロック。書き込みの tx は必ずこれを先頭で取る。
// ---------------------------------------------------------------------------
func (q *Queries) LockRecording(ctx context.Context, recordingID int64) (LockRecordingRow, error) {
	row := q.db.QueryRow(ctx, lockRecording, recordingID)
	var i LockRecordingRow
	err := row.Scan(&i.ID, &i.IsTrashed, &i.IsPurged)
	return i, err
}

const upsertRecordingChapterOwnership = `-- name: UpsertRecordingChapterOwnership :exec

INSERT INTO recording_chapter_ownership (recording_id)
VALUES ($1)
ON CONFLICT (recording_id) DO NOTHING
`

// ---------------------------------------------------------------------------
// 書く
// ---------------------------------------------------------------------------
// 所有の行が無ければ作る。既にあれば adopted_at を書き換えない（「いつ確認したか」
// は最初の 1 回の事実）。
func (q *Queries) UpsertRecordingChapterOwnership(ctx context.Context, recordingID int64) error {
	_, err := q.db.Exec(ctx, upsertRecordingChapterOwnership, recordingID)
	return err
}
