// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_reconcile.sql

package sqlcgen

import (
	"context"
	"time"
)

const deleteOrphanFile = `-- name: DeleteOrphanFile :exec
DELETE FROM orphan_files WHERE rel_path = $1
`

func (q *Queries) DeleteOrphanFile(ctx context.Context, relPath string) error {
	_, err := q.db.Exec(ctx, deleteOrphanFile, relPath)
	return err
}

const getRecordingPurgeState = `-- name: GetRecordingPurgeState :one
SELECT
  r.site,
  r.title,
  -- 明示キャストが無いと sqlc が型を推論できず interface{} になる。
  (r.deleted_at IS NOT NULL)::boolean AS trashed,
  EXISTS (
    SELECT 1 FROM media_assets a
    WHERE a.recording_id = r.id AND a.state <> 'deleted'
  ) AS assets_remaining
FROM recordings r
WHERE r.id = $1
`

type GetRecordingPurgeStateRow struct {
	Site            string
	Title           string
	Trashed         bool
	AssetsRemaining bool
}

// recording.deleted（M3-11）の発火判定。「録画そのものが消えた」と言えるのは、
// ごみ箱に入った（deleted_at IS NOT NULL）録画で、物理削除が終わっていない
// media_assets が 1 行も残っていないときだけである。判定をアセットの kind に
// 取ると until_encoded の原本削除（録画は生きている）で誤発火し、逆に原本を
// 先に消した録画のごみ箱削除では発火しない。
func (q *Queries) GetRecordingPurgeState(ctx context.Context, id int64) (GetRecordingPurgeStateRow, error) {
	row := q.db.QueryRow(ctx, getRecordingPurgeState, id)
	var i GetRecordingPurgeStateRow
	err := row.Scan(
		&i.Site,
		&i.Title,
		&i.Trashed,
		&i.AssetsRemaining,
	)
	return i, err
}

const listAgedOrphanFiles = `-- name: ListAgedOrphanFiles :many
SELECT rel_path FROM orphan_files WHERE first_seen <= $1::timestamptz
`

// エイジング済みの孤児（first_seen が age_cutoff 以前）。
func (q *Queries) ListAgedOrphanFiles(ctx context.Context, ageCutoff time.Time) ([]string, error) {
	rows, err := q.db.Query(ctx, listAgedOrphanFiles, ageCutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var rel_path string
		if err := rows.Scan(&rel_path); err != nil {
			return nil, err
		}
		items = append(items, rel_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMediaAssetRelPaths = `-- name: ListAllMediaAssetRelPaths :many
SELECT rel_path FROM media_assets
`

// 孤児判定用。テーブル全体を読んで Go 側でファイル一覧と突き合わせる
// （家庭用サーバー規模の行数を前提。件数が増えたら bloom filter 等の検討対象）。
func (q *Queries) ListAllMediaAssetRelPaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAllMediaAssetRelPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var rel_path string
		if err := rows.Scan(&rel_path); err != nil {
			return nil, err
		}
		items = append(items, rel_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllOrphanFiles = `-- name: ListAllOrphanFiles :many
SELECT rel_path, first_seen FROM orphan_files
`

func (q *Queries) ListAllOrphanFiles(ctx context.Context) ([]OrphanFile, error) {
	rows, err := q.db.Query(ctx, listAllOrphanFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrphanFile
	for rows.Next() {
		var i OrphanFile
		if err := rows.Scan(&i.RelPath, &i.FirstSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaAssetsPendingDelete = `-- name: ListMediaAssetsPendingDelete :many

SELECT id, recording_id, rel_path, size_bytes, kind
FROM media_assets
WHERE state = 'deleting'
ORDER BY id
LIMIT $1
`

type ListMediaAssetsPendingDeleteRow struct {
	ID          int64
	RecordingID int64
	RelPath     string
	SizeBytes   int64
	Kind        string
}

// 削除 reconcile（M3-8、docs/storage.md §7）。物理 unlink に至る 3 ソース
// （ごみ箱 / until_encoded / 孤児）を 1 本のループに統一するためのクエリ群。
//
// 削除プロトコルは冪等: active → deleting → deleted。deleting のまま
// プロセスが落ちても ListMediaAssetsPendingDelete が次パスで拾い直す。
// 前パスで deleting にマークしたまま unlink できずに終わった行を拾い直す。
// 「既に決めた削除」の再実行であり、新規の判断ではないのでブレーカーの対象外。
func (q *Queries) ListMediaAssetsPendingDelete(ctx context.Context, rowLimit int32) ([]ListMediaAssetsPendingDeleteRow, error) {
	rows, err := q.db.Query(ctx, listMediaAssetsPendingDelete, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMediaAssetsPendingDeleteRow
	for rows.Next() {
		var i ListMediaAssetsPendingDeleteRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordingID,
			&i.RelPath,
			&i.SizeBytes,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashMediaAssetsToDelete = `-- name: ListTrashMediaAssetsToDelete :many
SELECT a.id, a.recording_id, a.rel_path, a.size_bytes, a.kind
FROM media_assets a
JOIN recordings r ON r.id = a.recording_id
WHERE a.state = 'active'
  AND r.deleted_at IS NOT NULL
  AND (
    (r.purge_after IS NOT NULL AND r.purge_after <= now())
    OR r.deleted_at <= $1::timestamptz
  )
ORDER BY a.id
LIMIT $2
`

type ListTrashMediaAssetsToDeleteParams struct {
	GraceCutoff time.Time
	RowLimit    int32
}

type ListTrashMediaAssetsToDeleteRow struct {
	ID          int64
	RecordingID int64
	RelPath     string
	SizeBytes   int64
	Kind        string
}

// ごみ箱の猶予超過、または「今すぐ完全削除」（purge_after）の対象。
func (q *Queries) ListTrashMediaAssetsToDelete(ctx context.Context, arg ListTrashMediaAssetsToDeleteParams) ([]ListTrashMediaAssetsToDeleteRow, error) {
	rows, err := q.db.Query(ctx, listTrashMediaAssetsToDelete, arg.GraceCutoff, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrashMediaAssetsToDeleteRow
	for rows.Next() {
		var i ListTrashMediaAssetsToDeleteRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordingID,
			&i.RelPath,
			&i.SizeBytes,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUntilEncodedOriginalsToDelete = `-- name: ListUntilEncodedOriginalsToDelete :many
SELECT a.id, a.recording_id, a.rel_path, a.size_bytes, a.kind
FROM media_assets a
JOIN recordings r ON r.id = a.recording_id
WHERE a.state = 'active'
  AND a.kind = 'original'
  AND r.keep_original = 'until_encoded'
  AND r.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM unnest(r.encode_profiles) AS want(profile)
    WHERE NOT EXISTS (
      SELECT 1 FROM media_assets e
      WHERE e.recording_id = r.id
        AND e.kind = 'encoded'
        AND e.state = 'active'
        AND e.profile = want.profile
    )
  )
  AND EXISTS (
    SELECT 1 FROM media_assets t
    WHERE t.recording_id = r.id AND t.kind = 'thumbnail' AND t.state = 'active'
  )
ORDER BY a.id
LIMIT $1
`

type ListUntilEncodedOriginalsToDeleteRow struct {
	ID          int64
	RecordingID int64
	RelPath     string
	SizeBytes   int64
	Kind        string
}

// keep_original='until_encoded' で、desired な派生物（全 encode_profiles +
// thumbnail）がすべて active でコミット済みの原本。ごみ箱経由の録画は
// ListTrashMediaAssetsToDelete 側で扱うのでここでは除外する。
func (q *Queries) ListUntilEncodedOriginalsToDelete(ctx context.Context, rowLimit int32) ([]ListUntilEncodedOriginalsToDeleteRow, error) {
	rows, err := q.db.Query(ctx, listUntilEncodedOriginalsToDelete, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUntilEncodedOriginalsToDeleteRow
	for rows.Next() {
		var i ListUntilEncodedOriginalsToDeleteRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordingID,
			&i.RelPath,
			&i.SizeBytes,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMediaAssetDeleted = `-- name: MarkMediaAssetDeleted :execrows
UPDATE media_assets SET state = 'deleted', deleted_at = now(), updated_at = now()
WHERE id = $1 AND state = 'deleting'
`

func (q *Queries) MarkMediaAssetDeleted(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markMediaAssetDeleted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markMediaAssetDeleting = `-- name: MarkMediaAssetDeleting :execrows
UPDATE media_assets SET state = 'deleting', updated_at = now()
WHERE id = $1 AND state = 'active'
`

func (q *Queries) MarkMediaAssetDeleting(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markMediaAssetDeleting, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertOrphanFile = `-- name: UpsertOrphanFile :exec
INSERT INTO orphan_files (rel_path) VALUES ($1)
ON CONFLICT (rel_path) DO NOTHING
`

// 孤児候補を記録する。既存行があれば first_seen を保持する
// （DO NOTHING。エイジングの起点は「最初に孤児だと気づいた時刻」）。
func (q *Queries) UpsertOrphanFile(ctx context.Context, relPath string) error {
	_, err := q.db.Exec(ctx, upsertOrphanFile, relPath)
	return err
}
