// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: epg.sql

package sqlcgen

import (
	"context"
	"time"
)

const countEpgPrograms = `-- name: CountEpgPrograms :one
SELECT count(*) FROM epg_programs WHERE site = $1
`

func (q *Queries) CountEpgPrograms(ctx context.Context, site string) (int64, error) {
	row := q.db.QueryRow(ctx, countEpgPrograms, site)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteStaleEpgProgramsForServices = `-- name: DeleteStaleEpgProgramsForServices :execrows
DELETE FROM epg_programs
WHERE site = $1
  AND observed_at < $2
  AND network_id = $3
  AND service_id = ANY($4::integer[])
`

type DeleteStaleEpgProgramsForServicesParams struct {
	Site       string
	ObservedAt time.Time
	NetworkID  int32
	ServiceIds []int32
}

// mirakc の EPG 収集は物理チャンネル単位（1 回チューニングして collect-eits を回す）なので、
// スイープも「今回番組を返したチャンネルに属するサービス」に限定する。
// あるチャンネルの収集失敗がそのチャンネルの番組表を消してしまうのを防ぐ。
// 呼び出し側が対象サービスを network_id ごとにまとめて 1 回ずつ呼ぶ。
func (q *Queries) DeleteStaleEpgProgramsForServices(ctx context.Context, arg DeleteStaleEpgProgramsForServicesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleEpgProgramsForServices,
		arg.Site,
		arg.ObservedAt,
		arg.NetworkID,
		arg.ServiceIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleEpgServices = `-- name: DeleteStaleEpgServices :execrows
DELETE FROM epg_services
WHERE site = $1 AND observed_at < $2
`

type DeleteStaleEpgServicesParams struct {
	Site       string
	ObservedAt time.Time
}

func (q *Queries) DeleteStaleEpgServices(ctx context.Context, arg DeleteStaleEpgServicesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleEpgServices, arg.Site, arg.ObservedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const epgSweepMark = `-- name: EpgSweepMark :one
SELECT now()::timestamptz AS mark
`

// 全量同期のスイープ基準時刻。observed_at は DB の now() で書かれるため、
// 基準時刻もアプリのクロックではなく DB から取る（クロックスキューで
// プロジェクション全体を消して再投入する事故を防ぐ）。
func (q *Queries) EpgSweepMark(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, epgSweepMark)
	var mark time.Time
	err := row.Scan(&mark)
	return mark, err
}

const getEpgProgram = `-- name: GetEpgProgram :one
SELECT site, program_id, network_id, service_id, event_id, start_at, duration_ms, end_at, is_free, name, description, extended, genres, video, audios, observed_at, genre_lv1 FROM epg_programs
WHERE site = $1 AND program_id = $2
`

type GetEpgProgramParams struct {
	Site      string
	ProgramID int64
}

func (q *Queries) GetEpgProgram(ctx context.Context, arg GetEpgProgramParams) (EpgProgram, error) {
	row := q.db.QueryRow(ctx, getEpgProgram, arg.Site, arg.ProgramID)
	var i EpgProgram
	err := row.Scan(
		&i.Site,
		&i.ProgramID,
		&i.NetworkID,
		&i.ServiceID,
		&i.EventID,
		&i.StartAt,
		&i.DurationMs,
		&i.EndAt,
		&i.IsFree,
		&i.Name,
		&i.Description,
		&i.Extended,
		&i.Genres,
		&i.Video,
		&i.Audios,
		&i.ObservedAt,
		&i.GenreLv1,
	)
	return i, err
}

const getProgramSnapshotSource = `-- name: GetProgramSnapshotSource :one
SELECT p.name AS title, p.start_at, p.duration_ms,
       s.network_id, s.service_id, s.channel_type, s.channel,
       p.event_id, s.name AS service_name
FROM epg_programs p
JOIN epg_services s
  ON s.site = p.site AND s.network_id = p.network_id AND s.service_id = p.service_id
WHERE p.site = $1 AND p.program_id = $2
`

type GetProgramSnapshotSourceParams struct {
	Site      string
	ProgramID int64
}

type GetProgramSnapshotSourceRow struct {
	Title       string
	StartAt     time.Time
	DurationMs  int64
	NetworkID   int32
	ServiceID   int32
	ChannelType string
	Channel     string
	EventID     int32
	ServiceName string
}

// 意図・上書きの書き込み時に、program_snapshots へスナップショットする番組の事実
// （title / 開始時刻 / 尺 / チャンネル識別）を EPG プロジェクションから引く。
// mirakc の programId 内部構造への算術（NID*10^10 + SID*10^5 + EID）に頼らないのは
// 元々の理由のままだが、title / start_at / duration_ms も返すのは #27 の決定
// （「値の出所を EPG 射影ただ 1 つに固定する」）による: クライアント申告の
// title / 開始時刻 / 尺を信じると、GC の比較対象（program_snapshots.start_at +
// duration_ms）がクライアントの古い番組表に引きずられ得るため
// （api.ensureProgramSnapshot から使う）。
// event_id / s.name (service_name) は issue #98 で追加した参照 --- program_snapshots
// 側の event_id / service_name 列を埋めるのに使う。他のチャンネル識別列と
// 同じ経路（射影から直接引く。mirakc の programId 分解には頼らない）。
func (q *Queries) GetProgramSnapshotSource(ctx context.Context, arg GetProgramSnapshotSourceParams) (GetProgramSnapshotSourceRow, error) {
	row := q.db.QueryRow(ctx, getProgramSnapshotSource, arg.Site, arg.ProgramID)
	var i GetProgramSnapshotSourceRow
	err := row.Scan(
		&i.Title,
		&i.StartAt,
		&i.DurationMs,
		&i.NetworkID,
		&i.ServiceID,
		&i.ChannelType,
		&i.Channel,
		&i.EventID,
		&i.ServiceName,
	)
	return i, err
}

const listEpgPrograms = `-- name: ListEpgPrograms :many
SELECT site, program_id, network_id, service_id, event_id, start_at, duration_ms, end_at, is_free, name, description, extended, genres, video, audios, observed_at, genre_lv1 FROM epg_programs
WHERE site = $1
  AND start_at < $2::timestamptz
  AND end_at   > $3::timestamptz
  AND ($4::integer IS NULL OR network_id = $4::integer)
  AND ($5::integer IS NULL OR service_id = $5::integer)
ORDER BY start_at, network_id, service_id
`

type ListEpgProgramsParams struct {
	Site        string
	WindowEnd   time.Time
	WindowStart time.Time
	NetworkID   *int32
	ServiceID   *int32
}

func (q *Queries) ListEpgPrograms(ctx context.Context, arg ListEpgProgramsParams) ([]EpgProgram, error) {
	rows, err := q.db.Query(ctx, listEpgPrograms,
		arg.Site,
		arg.WindowEnd,
		arg.WindowStart,
		arg.NetworkID,
		arg.ServiceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EpgProgram
	for rows.Next() {
		var i EpgProgram
		if err := rows.Scan(
			&i.Site,
			&i.ProgramID,
			&i.NetworkID,
			&i.ServiceID,
			&i.EventID,
			&i.StartAt,
			&i.DurationMs,
			&i.EndAt,
			&i.IsFree,
			&i.Name,
			&i.Description,
			&i.Extended,
			&i.Genres,
			&i.Video,
			&i.Audios,
			&i.ObservedAt,
			&i.GenreLv1,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpgProgramsForList = `-- name: ListEpgProgramsForList :many
SELECT site, program_id, network_id, service_id, event_id,
       start_at, duration_ms, end_at, is_free, name, description, genre_lv1
FROM epg_programs
WHERE site = $1
  AND start_at < $2::timestamptz
  AND end_at   > $3::timestamptz
  AND (
    coalesce(cardinality($4::integer[]), 0) = 0
    OR EXISTS (
      SELECT 1
      FROM generate_subscripts($4::integer[], 1) AS i
      WHERE ($4::integer[])[i] = epg_programs.network_id
        AND ($5::integer[])[i] = epg_programs.service_id
    )
  )
ORDER BY start_at, network_id, service_id
`

type ListEpgProgramsForListParams struct {
	Site            string
	WindowEnd       time.Time
	WindowStart     time.Time
	ExactNetworkIds []int32
	ExactServiceIds []int32
}

type ListEpgProgramsForListRow struct {
	Site        string
	ProgramID   int64
	NetworkID   int32
	ServiceID   int32
	EventID     int32
	StartAt     time.Time
	DurationMs  int64
	EndAt       time.Time
	IsFree      bool
	Name        string
	Description string
	GenreLv1    []int16
}

// 一覧向けの軽い形。extended / video / audios は返さない（1 行あたり数 KB になり
// 時間窓を広げたときの転送量が跳ねるため。詳細は GetEpgProgram で取る）。
//
// exact_network_ids / exact_service_ids は同じ添字が 1 組で、呼び出し側が必ず
// 同じ長さにして渡す。複数組は OR。空/NULL ならその条件を効かせない。
// `unnest(a, b)` は sqlc の組み込み analyzer が解決できないため、start_delay.sql と
// 同じ generate_subscripts + 添字参照を使う。
func (q *Queries) ListEpgProgramsForList(ctx context.Context, arg ListEpgProgramsForListParams) ([]ListEpgProgramsForListRow, error) {
	rows, err := q.db.Query(ctx, listEpgProgramsForList,
		arg.Site,
		arg.WindowEnd,
		arg.WindowStart,
		arg.ExactNetworkIds,
		arg.ExactServiceIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEpgProgramsForListRow
	for rows.Next() {
		var i ListEpgProgramsForListRow
		if err := rows.Scan(
			&i.Site,
			&i.ProgramID,
			&i.NetworkID,
			&i.ServiceID,
			&i.EventID,
			&i.StartAt,
			&i.DurationMs,
			&i.EndAt,
			&i.IsFree,
			&i.Name,
			&i.Description,
			&i.GenreLv1,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpgServices = `-- name: ListEpgServices :many
SELECT es.site, es.network_id, es.service_id, es.type, es.logo_id, es.remote_control_key_id, es.name, es.channel_type, es.channel, es.has_logo_data, es.observed_at,
    EXISTS (
        SELECT 1 FROM epg_programs ep
        WHERE ep.site = es.site
          AND ep.network_id = es.network_id
          AND ep.service_id = es.service_id
    ) AS has_programs
FROM epg_services es
WHERE es.site = $1
ORDER BY es.channel_type, es.remote_control_key_id, es.service_id
`

type ListEpgServicesRow struct {
	Site               string
	NetworkID          int32
	ServiceID          int32
	Type               int32
	LogoID             int32
	RemoteControlKeyID int32
	Name               string
	ChannelType        string
	Channel            string
	HasLogoData        bool
	ObservedAt         time.Time
	HasPrograms        bool
}

// has_programs は「射影全体で 1 件でも番組を持つか」であり、表示中の時間窓では
// 判定しない。時間窓に依存させると、フロントのピッカー候補が「ページを読み込む
// ほど増える」形になり、しかもサーバー側で serviceId 絞り込みをかけたときに
// 候補が絞り込み結果に連動して縮む（1 局に絞ると他局へ切り替えられなくなる）
// 問題を再発させる。候補集合を絞り込みから独立させるのがこの列を足す理由
// そのものなので、判定は射影全体で固定する（docs/frontend.md「番組リスト」）。
func (q *Queries) ListEpgServices(ctx context.Context, site string) ([]ListEpgServicesRow, error) {
	rows, err := q.db.Query(ctx, listEpgServices, site)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEpgServicesRow
	for rows.Next() {
		var i ListEpgServicesRow
		if err := rows.Scan(
			&i.Site,
			&i.NetworkID,
			&i.ServiceID,
			&i.Type,
			&i.LogoID,
			&i.RemoteControlKeyID,
			&i.Name,
			&i.ChannelType,
			&i.Channel,
			&i.HasLogoData,
			&i.ObservedAt,
			&i.HasPrograms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneEpgPrograms = `-- name: PruneEpgPrograms :execrows
DELETE FROM epg_programs
WHERE site = $1 AND end_at < $2
`

type PruneEpgProgramsParams struct {
	Site  string
	EndAt time.Time
}

func (q *Queries) PruneEpgPrograms(ctx context.Context, arg PruneEpgProgramsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneEpgPrograms, arg.Site, arg.EndAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
