// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inplace.sql

package sqlcgen

import (
	"context"
	"time"
)

const getInPlaceAssetByRelPath = `-- name: GetInPlaceAssetByRelPath :one

SELECT id, recording_id, kind, profile,
       (state <> 'deleted')::boolean AS published
FROM media_assets
WHERE rel_path = $1
ORDER BY (state <> 'deleted')::boolean DESC, id DESC
LIMIT 1
`

type GetInPlaceAssetByRelPathRow struct {
	ID          int64
	RecordingID int64
	Kind        string
	Profile     *string
	Published   bool
}

// In-place media registration shared by `rokuban rescue` and M3-10 imports.
// Bytes are already under storage.media_dir; these queries only publish DB rows.
// media_assets_rel_path_idx は state <> 'deleted' の部分索引なので、実ファイルが残る限り
// deleted 行もそのファイルの所属を示すという理由でここは意図的に述語を外し、索引を使えず
// seq scan になる。実測 (media_assets 3000 行、EXPLAIN (ANALYZE, TIMING OFF)): 旧クエリ
// (述語あり) Index Scan 0.010 ms → 新クエリ (述語なし) Seq Scan 0.123 ms。Register は
// asset 1 件ごとに呼ぶので rescue 全体ではアセット数に比例するが、家庭用サーバー規模を
// 前提に許容する。増えたら非部分索引の追加が上げ幅。
func (q *Queries) GetInPlaceAssetByRelPath(ctx context.Context, relPath string) (GetInPlaceAssetByRelPathRow, error) {
	row := q.db.QueryRow(ctx, getInPlaceAssetByRelPath, relPath)
	var i GetInPlaceAssetByRelPathRow
	err := row.Scan(
		&i.ID,
		&i.RecordingID,
		&i.Kind,
		&i.Profile,
		&i.Published,
	)
	return i, err
}

const upsertInPlaceMediaAsset = `-- name: UpsertInPlaceMediaAsset :one
INSERT INTO media_assets (
    recording_id, kind, profile, rel_path, size_bytes, state
) VALUES (
    $1, $2, $3,
    $4, $5, 'active'
)
ON CONFLICT (recording_id, kind, profile)
DO UPDATE SET
    size_bytes = EXCLUDED.size_bytes,
    state      = 'active',
    deleted_at = NULL,
    updated_at = now()
WHERE media_assets.rel_path = EXCLUDED.rel_path
RETURNING id
`

type UpsertInPlaceMediaAssetParams struct {
	RecordingID int64
	Kind        string
	Profile     *string
	RelPath     string
	SizeBytes   int64
}

// A tuple is immutable once published. A different path here means a synthetic identity
// collision or conflicting import; fail (RETURNING no row) instead of orphaning the old file.
func (q *Queries) UpsertInPlaceMediaAsset(ctx context.Context, arg UpsertInPlaceMediaAssetParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertInPlaceMediaAsset,
		arg.RecordingID,
		arg.Kind,
		arg.Profile,
		arg.RelPath,
		arg.SizeBytes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertInPlaceRecording = `-- name: UpsertInPlaceRecording :one
INSERT INTO recordings (
    source, site,
    network_id, service_id, event_id,
    service_name, channel_type, channel,
    title, program_start_at, program_duration_ms,
    status, started_at, ended_at
) VALUES (
    $1, $2,
    $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14
)
ON CONFLICT (site, network_id, service_id, event_id, program_start_at)
    WHERE deleted_at IS NULL AND superseded_at IS NULL
DO UPDATE SET
    source              = EXCLUDED.source,
    service_name        = EXCLUDED.service_name,
    channel_type        = EXCLUDED.channel_type,
    channel             = EXCLUDED.channel,
    title               = EXCLUDED.title,
    program_duration_ms = EXCLUDED.program_duration_ms,
    status              = EXCLUDED.status,
    started_at          = COALESCE(recordings.started_at, EXCLUDED.started_at),
    ended_at            = COALESCE(recordings.ended_at, EXCLUDED.ended_at),
    updated_at          = now()
RETURNING id
`

type UpsertInPlaceRecordingParams struct {
	Source            string
	Site              string
	NetworkID         int32
	ServiceID         int32
	EventID           int32
	ServiceName       string
	ChannelType       string
	Channel           string
	Title             string
	ProgramStartAt    time.Time
	ProgramDurationMs int64
	Status            string
	StartedAt         *time.Time
	EndedAt           *time.Time
}

// ON CONFLICT の対象列と述語は recordings_unique_active_event（issue #129 症状 2 で
// `AND superseded_at IS NULL` を追加済み）と一字一句一致させる
// 必要がある。in-place 登録が superseded_at を立てることはない（それは watcher の
// 録画 supersede 専用の概念）が、索引の述語が変わった以上、対象インデックスの
// 照合のためにここも揃える。program_start_at は放送イベントの永続 identity
// の一部なので、DO UPDATE で書き換えず、開始時刻が変われば別行を作る。
func (q *Queries) UpsertInPlaceRecording(ctx context.Context, arg UpsertInPlaceRecordingParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertInPlaceRecording,
		arg.Source,
		arg.Site,
		arg.NetworkID,
		arg.ServiceID,
		arg.EventID,
		arg.ServiceName,
		arg.ChannelType,
		arg.Channel,
		arg.Title,
		arg.ProgramStartAt,
		arg.ProgramDurationMs,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
