// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: label_rules.sql

package sqlcgen

import (
	"context"
)

const applyLabelRuleReevaluation = `-- name: ApplyLabelRuleReevaluation :one
WITH winners AS MATERIALIZED (
    SELECT r.id AS recording_id, public.label_rule_winner(r.title) AS label_rule_id
    FROM recordings r
),
upserted AS (
    INSERT INTO label_rule_hits (recording_id, label_rule_id)
    SELECT w.recording_id, w.label_rule_id
    FROM winners w
    WHERE w.label_rule_id IS NOT NULL
    ON CONFLICT (recording_id) DO UPDATE
        SET label_rule_id = EXCLUDED.label_rule_id
        WHERE label_rule_hits.label_rule_id IS DISTINCT FROM EXCLUDED.label_rule_id
    RETURNING 1
),
removed AS (
    DELETE FROM label_rule_hits h
    WHERE NOT EXISTS (
        SELECT 1
        FROM winners w
        WHERE w.recording_id = h.recording_id
          AND w.label_rule_id IS NOT NULL
    )
    RETURNING 1
)
SELECT (SELECT count(*) FROM upserted) + (SELECT count(*) FROM removed)
`

// label_rules の変更後に、全録画の当たりを差分だけ適用する。全件を DELETE
// してから INSERT し直すと、変化が無くてもデッドタプルが全行ぶん出る。
//
//   - upserted: 勝者がいる録画。ON CONFLICT ... WHERE IS DISTINCT FROM で、
//     値が同じ行は UPDATE 自体を起こさない（新しいタプルを作らない）
//   - removed: 勝者が居なくなった録画の行。当たりは勝者しか持たないので、
//     ルールの削除はここでしか落ちない（CASCADE だけだと次点に移らない）
//
// winners を MATERIALIZED にするのは、2 つのデータ変更 CTE が同じ評価結果を
// 見るようにするため（評価は label_rule_winner の呼び出しで、行数ぶん走る）。
func (q *Queries) ApplyLabelRuleReevaluation(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, applyLabelRuleReevaluation)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createLabelRule = `-- name: CreateLabelRule :one
INSERT INTO label_rules (key, value, keyword, priority)
VALUES ($1, $2, $3, $4)
RETURNING id, key, value, keyword, priority, value_key, keyword_key, created_at, updated_at
`

type CreateLabelRuleParams struct {
	Key      string
	Value    string
	Keyword  string
	Priority int32
}

func (q *Queries) CreateLabelRule(ctx context.Context, arg CreateLabelRuleParams) (LabelRule, error) {
	row := q.db.QueryRow(ctx, createLabelRule,
		arg.Key,
		arg.Value,
		arg.Keyword,
		arg.Priority,
	)
	var i LabelRule
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Keyword,
		&i.Priority,
		&i.ValueKey,
		&i.KeywordKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLabelRule = `-- name: DeleteLabelRule :execrows
DELETE FROM label_rules WHERE id = $1
`

func (q *Queries) DeleteLabelRule(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLabelRule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLabelRule = `-- name: GetLabelRule :one
SELECT id, key, value, keyword, priority, value_key, keyword_key, created_at, updated_at FROM label_rules WHERE id = $1
`

func (q *Queries) GetLabelRule(ctx context.Context, id int64) (LabelRule, error) {
	row := q.db.QueryRow(ctx, getLabelRule, id)
	var i LabelRule
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Keyword,
		&i.Priority,
		&i.ValueKey,
		&i.KeywordKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLabelRules = `-- name: ListLabelRules :many
SELECT id, key, value, keyword, priority, value_key, keyword_key, created_at, updated_at FROM label_rules
ORDER BY priority DESC, id ASC
`

// priority DESC, id ASC はラベルの勝者を決める順と同じ（label_rule_winner）。
// 並びを 2 箇所に書き下すと、一覧の見た目と実効の順が食い違う。
func (q *Queries) ListLabelRules(ctx context.Context) ([]LabelRule, error) {
	rows, err := q.db.Query(ctx, listLabelRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabelRule
	for rows.Next() {
		var i LabelRule
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Value,
			&i.Keyword,
			&i.Priority,
			&i.ValueKey,
			&i.KeywordKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordingShelves = `-- name: ListRecordingShelves :many
WITH playable_assets AS MATERIALIZED (
    SELECT DISTINCT ma.recording_id
    FROM media_assets ma
    WHERE (ma.kind = 'original' AND ma.state <> 'deleted')
       OR (ma.kind = 'encoded' AND ma.state = 'active')
),
playable AS MATERIALIZED (
    SELECT r.id,
           r.title,
           r.program_start_at,
           COALESCE(lr.value_key, r.series_key) AS value
    FROM recordings r
    JOIN playable_assets pa ON pa.recording_id = r.id
    LEFT JOIN label_rule_hits h ON h.recording_id = r.id
    LEFT JOIN label_rules lr ON lr.id = h.label_rule_id
    WHERE r.deleted_at IS NULL
      AND r.superseded_at IS NULL
)
SELECT p.value,
       (array_agg(p.title ORDER BY p.program_start_at DESC, p.id DESC))[1]::text AS title,
       count(*) AS recording_count,
       (array_agg(p.id ORDER BY p.program_start_at DESC, p.id DESC))[1]::bigint AS representative_id
FROM playable p
GROUP BY p.value
ORDER BY recording_count DESC, p.value ASC NULLS LAST
`

type ListRecordingShelvesRow struct {
	Value            *string
	Title            string
	RecordingCount   int64
	RepresentativeID int64
}

// 棚 1 件 = 実効シリーズの値 1 つ。母集団は生きていて再生できる録画
// （原本の media_asset がある、または encoded の派生物がある）。
//
// 代表は program_start_at の新しい順で先頭の 1 件。title は代表の生のタイトルで、
// 値（棚のキー）そのものではない --- 値は正規化の産物なので表示名にならない。
//
// 値が NULL の棚も返す（UI が「その他」にまとめる材料にする）。値が NULL の行を
// 落とすと、まとめ先の件数が API からは分からなくなる。
//
// 値が NULL の棚の行は `GROUP BY value` が 1 つのグループにまとめる（SQL の
// GROUP BY は NULL を等しいものとして扱う）。
//
// **この形はプランの形に依存するので、崩すと 4 倍以上遅くなる。** 73,000 行が
// すべて再生可能な状態での実測（sqlc / pgx の prepared statement 経由）:
//
//   - この形: 141 ms
//   - 代表と件数を別々の CTE に割る: 231 ms（playable をもう 1 度走査する）
//   - playable を MATERIALIZED にしない: 617 ms（下記）
//
// MATERIALIZED を外すと、プランナは recordings_unique_active_event（部分一意
// 索引）を選ぶ。一意索引の行数を 1 と見積もるので下流が全部 1 行の計画になり、
// 代表を求めるソートが外側の行数ぶん繰り返される。**psql で単発実行すると
// prepared statement ではないのでこの計画を踏まず、146 ms に見える**（アプリは
// 必ず踏む）。docs/data/series.md §8 の予算はこの経路の値である。
func (q *Queries) ListRecordingShelves(ctx context.Context) ([]ListRecordingShelvesRow, error) {
	rows, err := q.db.Query(ctx, listRecordingShelves)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordingShelvesRow
	for rows.Next() {
		var i ListRecordingShelvesRow
		if err := rows.Scan(
			&i.Value,
			&i.Title,
			&i.RecordingCount,
			&i.RepresentativeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLabelRule = `-- name: UpdateLabelRule :one
UPDATE label_rules SET
    value      = $1,
    keyword    = $2,
    priority   = $3,
    updated_at = now()
WHERE id = $4
RETURNING id, key, value, keyword, priority, value_key, keyword_key, created_at, updated_at
`

type UpdateLabelRuleParams struct {
	Value    string
	Keyword  string
	Priority int32
	ID       int64
}

// value_key は value の生成列なので、value を変えれば一緒に変わる。
func (q *Queries) UpdateLabelRule(ctx context.Context, arg UpdateLabelRuleParams) (LabelRule, error) {
	row := q.db.QueryRow(ctx, updateLabelRule,
		arg.Value,
		arg.Keyword,
		arg.Priority,
		arg.ID,
	)
	var i LabelRule
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Keyword,
		&i.Priority,
		&i.ValueKey,
		&i.KeywordKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
