// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loop_pass_snapshots.sql

package sqlcgen

import (
	"context"
	"time"
)

const getRecordSweepSnapshot = `-- name: GetRecordSweepSnapshot :one
SELECT last_success_at
FROM record_sweep_snapshots
WHERE site = $1
`

func (q *Queries) GetRecordSweepSnapshot(ctx context.Context, site string) (time.Time, error) {
	row := q.db.QueryRow(ctx, getRecordSweepSnapshot, site)
	var last_success_at time.Time
	err := row.Scan(&last_success_at)
	return last_success_at, err
}

const getRulerPassSnapshot = `-- name: GetRulerPassSnapshot :one
SELECT last_success_at
FROM ruler_pass_snapshots
WHERE site = $1
`

func (q *Queries) GetRulerPassSnapshot(ctx context.Context, site string) (time.Time, error) {
	row := q.db.QueryRow(ctx, getRulerPassSnapshot, site)
	var last_success_at time.Time
	err := row.Scan(&last_success_at)
	return last_success_at, err
}

const upsertRecordSweepSnapshot = `-- name: UpsertRecordSweepSnapshot :exec
INSERT INTO record_sweep_snapshots (site, last_success_at)
VALUES ($1, now())
ON CONFLICT (site) DO UPDATE SET
    last_success_at = EXCLUDED.last_success_at
`

func (q *Queries) UpsertRecordSweepSnapshot(ctx context.Context, site string) error {
	_, err := q.db.Exec(ctx, upsertRecordSweepSnapshot, site)
	return err
}

const upsertRulerPassSnapshot = `-- name: UpsertRulerPassSnapshot :exec

INSERT INTO ruler_pass_snapshots (site, last_success_at)
VALUES ($1, now())
ON CONFLICT (site) DO UPDATE SET
    last_success_at = EXCLUDED.last_success_at
`

// ruler / record_sweep の成功鮮度は、それぞれの処理結果の行とは別の寿命を持つ
// ため、専用の衛星表に保存する。呼び出し側は処理が成功した後だけ upsert する。
func (q *Queries) UpsertRulerPassSnapshot(ctx context.Context, site string) error {
	_, err := q.db.Exec(ctx, upsertRulerPassSnapshot, site)
	return err
}
