// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package sqlcgen

import (
	"context"
)

const getUningestedRecordBacklog = `-- name: GetUningestedRecordBacklog :one
SELECT
    count(*)::bigint                          AS records,
    COALESCE(sum(rs.content_length), 0)::bigint AS bytes
FROM record_sync rs
WHERE rs.site = $1
  AND rs.status = 'finished'
  AND NOT EXISTS (
      SELECT 1 FROM media_assets a
      WHERE a.recording_id = rs.recording_id
        AND a.kind = 'original'
        AND a.state <> 'deleted'
  )
`

type GetUningestedRecordBacklogRow struct {
	Records int64
	Bytes   int64
}

// 未 ingest の record（エッジに滞留しているぶん）の件数とバイト数。
//
// 「録画は終わったが Rokuban 側にコミットされていない」もの。回線断や
// クラウド側障害で ingest が詰まるとここが増え続け、エッジの録画バッファを
// 食い潰す（issue #4 のサイジングコメント）。エッジディスク残量アラートと
// 対で使う。
//
// コミット = media_assets 行なので、その不在で判定する。ファイルの有無は見ない
// （不変条件 3）。content_length は mirakc の観測値で NULL のこともある。
func (q *Queries) GetUningestedRecordBacklog(ctx context.Context, site string) (GetUningestedRecordBacklogRow, error) {
	row := q.db.QueryRow(ctx, getUningestedRecordBacklog, site)
	var i GetUningestedRecordBacklogRow
	err := row.Scan(&i.Records, &i.Bytes)
	return i, err
}
