// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package sqlcgen

import (
	"context"
)

const getUningestedRecordBacklog = `-- name: GetUningestedRecordBacklog :one
SELECT
    count(*)::bigint                          AS records,
    COALESCE(sum(rs.content_length), 0)::bigint AS bytes
FROM record_sync rs
WHERE rs.site = $1
  AND rs.status = 'finished'
  AND NOT EXISTS (
      SELECT 1 FROM media_assets a
      WHERE a.recording_id = rs.recording_id
        AND a.kind = 'original'
        AND a.state <> 'deleted'
  )
`

type GetUningestedRecordBacklogRow struct {
	Records int64
	Bytes   int64
}

// 未 ingest の record（エッジに滞留しているぶん）の件数とバイト数。
//
// 「録画は終わったが Rokuban 側にコミットされていない」もの。ingest が詰まると
// ここが増え続け、エッジの録画バッファを食い潰す（issue #4 のサイジング
// コメント）。エッジディスク残量アラートと対で使う。
//
// **数えるのは「クラウドが観測できた record」だけ。** record_sync の行は watcher が
// mirakc を観測して初めて作られる（internal/watcher の processRecord。入口の
// AcquireRecordSync が status を問わず作る）ので、**エッジ↔クラウドの回線が
// 切れている間に始まった録画はここに現れず、この値は増えない**。回線断の検知は
// 滞留量ではなく rokuban_sweep_last_pass_timestamp_seconds /
// rokuban_epg_sync_last_success_timestamp_seconds の停滞で行う
// （docs/operations.md §4。断が epg.retention_grace を超えると encode 意図が
// 落ちる交点も同節）。
//
// コミット = media_assets 行なので、その不在で判定する。ファイルの有無は見ない
// （不変条件 3）。content_length は mirakc の観測値で NULL のこともある。
func (q *Queries) GetUningestedRecordBacklog(ctx context.Context, site string) (GetUningestedRecordBacklogRow, error) {
	row := q.db.QueryRow(ctx, getUningestedRecordBacklog, site)
	var i GetUningestedRecordBacklogRow
	err := row.Scan(&i.Records, &i.Bytes)
	return i, err
}
