// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CircuitBreaker struct {
	Site      string
	Name      string
	TrippedAt time.Time
	Pending   int32
	Threshold int32
	Detail    json.RawMessage
}

type DropStat struct {
	MediaAssetID int64
	Pid          int32
	Packets      int64
	Drops        int64
	Errors       int64
	Scrambled    int64
	PidType      *string
}

type EpgProgram struct {
	Site        string
	ProgramID   int64
	NetworkID   int32
	ServiceID   int32
	EventID     int32
	StartAt     time.Time
	DurationMs  int64
	EndAt       time.Time
	IsFree      bool
	Name        string
	Description string
	GenreLv1    []int16
	Extended    json.RawMessage
	Genres      json.RawMessage
	Video       json.RawMessage
	Audios      json.RawMessage
	ObservedAt  time.Time
}

type EpgService struct {
	Site               string
	NetworkID          int32
	ServiceID          int32
	Type               int32
	LogoID             int32
	RemoteControlKeyID int32
	Name               string
	ChannelType        string
	Channel            string
	HasLogoData        bool
	ObservedAt         time.Time
}

type MediaAsset struct {
	ID          int64
	RecordingID int64
	Kind        string
	Profile     *string
	RelPath     string
	SizeBytes   int64
	State       string
	DeletedAt   *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type NeverScheduledEvent struct {
	Site       string
	NetworkID  int32
	ServiceID  int32
	EventID    int32
	ObservedAt time.Time
}

type OrphanFile struct {
	RelPath   string
	FirstSeen time.Time
}

type ProgramIntent struct {
	Site      string
	ProgramID int64
	Action    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ProgramInvestment struct {
	Site      string
	ProgramID int64
}

type ProgramOverride struct {
	Site      string
	ProgramID int64
	Overrides json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ProgramSnapshot struct {
	Site        string
	ProgramID   int64
	Title       string
	StartAt     time.Time
	DurationMs  int64
	NetworkID   int32
	ServiceID   int32
	ChannelType string
	Channel     string
	UpdatedAt   time.Time
	EventID     int32
	ServiceName string
}

type RecordSync struct {
	Site          string
	RecordID      string
	RecordingID   *int64
	ProgramID     int64
	Status        string
	ContentPath   *string
	ContentLength *int64
	Tags          []string
	FailedReason  json.RawMessage
	ObservedAt    time.Time
}

type Recording struct {
	ID                int64
	RuleID            *int64
	Source            string
	Site              string
	NetworkID         int32
	ServiceID         int32
	EventID           int32
	ServiceName       string
	ChannelType       string
	Channel           string
	Title             string
	Description       *string
	Extended          json.RawMessage
	Genres            json.RawMessage
	IsFree            bool
	ProgramStartAt    time.Time
	ProgramDurationMs int64
	Status            string
	StartedAt         *time.Time
	EndedAt           *time.Time
	QualityEvents     json.RawMessage
	DeletedAt         *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	SupersededAt      *time.Time
	PurgedAt          *time.Time
	GenreLv1          []int16
	PurgeRequested    bool
}

type RecordingEncodePolicy struct {
	RecordingID    int64
	KeepOriginal   string
	EncodeProfiles []string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type RecordingIngestProgress struct {
	RecordingID   int64
	WrittenBytes  int64
	ExpectedBytes *int64
	ObservedAt    time.Time
}

type Reservation struct {
	ID                    int64
	Site                  string
	ProgramID             int64
	RuleID                *int64
	Base                  json.RawMessage
	CreatedAt             time.Time
	UpdatedAt             time.Time
	DedupMatchRecordingID *int64
	DedupSimilarity       pgtype.Float4
}

type Rule struct {
	ID               int64
	Name             string
	Description      string
	Enabled          bool
	Priority         int32
	IsFree           pgtype.Bool
	DurationMinMs    *int64
	DurationMaxMs    *int64
	PeriodStartAt    *time.Time
	PeriodEndAt      *time.Time
	DedupeEnabled    bool
	DedupeThreshold  pgtype.Float4
	DedupeWindow     pgtype.Interval
	KeepOriginal     string
	EncodeProfiles   []string
	FilenameTemplate string
	Metadata         json.RawMessage
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type RuleChannelType struct {
	RuleID      int64
	ChannelType string
}

type RuleGenre struct {
	RuleID   int64
	GenreLv1 int16
}

type RuleService struct {
	RuleID    int64
	NetworkID int32
	ServiceID int32
}

type RuleSite struct {
	RuleID int64
	Site   string
}

type RuleTextMatch struct {
	RuleID        int64
	Seq           int32
	Target        string
	Mode          string
	Value         string
	CaseSensitive bool
	Negate        bool
}

type RuleTime struct {
	RuleID   int64
	Seq      int32
	Weekdays int32
	StartSec int32
	EndSec   int32
}

type ScheduleSync struct {
	Site         string
	ProgramID    int64
	State        string
	Options      json.RawMessage
	Tags         []string
	FailedReason json.RawMessage
	ObservedAt   time.Time
}

type SchemaInfo struct {
	Key   string
	Value string
}

type StorageSync struct {
	Root           string
	Path           string
	TotalBytes     int64
	UsedBytes      int64
	AvailableBytes int64
	ObservedAt     time.Time
}

type TunerSync struct {
	Site        string
	TunerIndex  int32
	Name        string
	Types       []string
	IsAvailable bool
	IsFault     bool
	ObservedAt  time.Time
}

type UntilEncodedDeletableOriginal struct {
	AssetID     int64
	RecordingID int64
	RelPath     string
	SizeBytes   int64
	State       string
}
