// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overlaps.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const listOverlappingReservations = `-- name: ListOverlappingReservations :many

SELECT r.site, r.program_id, r.rule_id, r.base, r.created_at, r.updated_at, r.dedup_match_recording_id, r.dedup_similarity, s.site, s.program_id, s.title, s.start_at, s.duration_ms, s.network_id, s.service_id, s.channel_type, s.channel, s.updated_at, s.event_id, s.service_name, i.action AS intent_action, o.overrides AS overrides
FROM reservations r
JOIN program_snapshots s ON s.site = r.site AND s.program_id = r.program_id
LEFT JOIN program_intents i ON i.site = r.site AND i.program_id = r.program_id
LEFT JOIN program_overrides o ON o.site = r.site AND o.program_id = r.program_id
WHERE r.site = $1
  AND r.program_id <> $2::bigint
  AND NOT EXISTS (
      SELECT 1 FROM never_scheduled_events nse
      -- 宛先のキーは**放送イベント**であって reservations 行ではない。reservations は
      -- program_snapshots への FK が ON DELETE CASCADE なので、スナップショットが
      -- GC された瞬間に一緒に消える。never_scheduled_events は program_snapshots への
      -- FK を持たないので program_snapshots の GC と同時には消えない。ただし
      -- EPG の放送地平を超えた観測は別の GC で刈る。reservations 行に依存すると、
      -- GC された瞬間に「never-scheduled 行が無い」ことになり、終了済み予約が
      -- 毎パス desired に戻り続ける（CLAUDE.md 不変条件 9 の identity: 導出器が
      -- 作るキーを宛先にしない、と同じ族）。
      WHERE nse.site = r.site
        AND nse.network_id = s.network_id
        AND nse.service_id = s.service_id
        AND nse.event_id = s.event_id
  )
  AND s.start_at < $3::timestamptz
  AND s.start_at + (s.duration_ms * interval '1 millisecond') > $4::timestamptz
ORDER BY s.start_at
`

type ListOverlappingReservationsParams struct {
	Site            string
	TargetProgramID int64
	WindowEnd       time.Time
	WindowStart     time.Time
}

type ListOverlappingReservationsRow struct {
	Reservation     Reservation
	ProgramSnapshot ProgramSnapshot
	IntentAction    *string
	Overrides       json.RawMessage
}

// 予約時の重なり警告 (issue #24 M2-8, issue #21 の「案 C」)。
//
// チューナー射影は使わない。同時間帯に既に何件の予約があるかという事実だけを
// 返す（docs/data.md §6.5 が扱う容量超過判定は M2-10 の領分で、ここでは行わない）。
// 半開区間 [window_start, window_end) と重なる予約を、自分自身
// （program_id = target_program_id）を除き、never-scheduled 済みの予約を
// 除外して返す。番組の開始時刻・尺は program_snapshots に移設された（#27）
// ので JOIN して引く。半開区間の判定はここ（SQL）で行うが、effective.skip
// の判定は Go 側で reservation.EffectiveOptions を通す
// （internal/api/reservations_overlaps.go）。program_intents /
// program_overrides との JOIN は ListReservationsFull
// (internal/db/queries/reservations.sql) と同じ形。
//
// 欠測除外の述語は never_scheduled_events 表を放送イベントキーで引く NOT EXISTS
// で、ListReservationsForSyncEvaluation (internal/db/queries/reservations.sql) /
// ListCapacityDemand (internal/db/queries/capacity.sql) と全く同じ。
// 理由は internal/db/queries/reservations.sql のコメント参照。
func (q *Queries) ListOverlappingReservations(ctx context.Context, arg ListOverlappingReservationsParams) ([]ListOverlappingReservationsRow, error) {
	rows, err := q.db.Query(ctx, listOverlappingReservations,
		arg.Site,
		arg.TargetProgramID,
		arg.WindowEnd,
		arg.WindowStart,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOverlappingReservationsRow
	for rows.Next() {
		var i ListOverlappingReservationsRow
		if err := rows.Scan(
			&i.Reservation.Site,
			&i.Reservation.ProgramID,
			&i.Reservation.RuleID,
			&i.Reservation.Base,
			&i.Reservation.CreatedAt,
			&i.Reservation.UpdatedAt,
			&i.Reservation.DedupMatchRecordingID,
			&i.Reservation.DedupSimilarity,
			&i.ProgramSnapshot.Site,
			&i.ProgramSnapshot.ProgramID,
			&i.ProgramSnapshot.Title,
			&i.ProgramSnapshot.StartAt,
			&i.ProgramSnapshot.DurationMs,
			&i.ProgramSnapshot.NetworkID,
			&i.ProgramSnapshot.ServiceID,
			&i.ProgramSnapshot.ChannelType,
			&i.ProgramSnapshot.Channel,
			&i.ProgramSnapshot.UpdatedAt,
			&i.ProgramSnapshot.EventID,
			&i.ProgramSnapshot.ServiceName,
			&i.IntentAction,
			&i.Overrides,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
