// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: program_overrides.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const deleteProgramOverrides = `-- name: DeleteProgramOverrides :execrows
DELETE FROM program_overrides WHERE site = $1 AND program_id = $2
`

type DeleteProgramOverridesParams struct {
	Site      string
	ProgramID int64
}

func (q *Queries) DeleteProgramOverrides(ctx context.Context, arg DeleteProgramOverridesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProgramOverrides, arg.Site, arg.ProgramID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProgramOverrides = `-- name: GetProgramOverrides :one

SELECT site, program_id, overrides, created_at, updated_at FROM program_overrides WHERE site = $1 AND program_id = $2
`

type GetProgramOverridesParams struct {
	Site      string
	ProgramID int64
}

// 番組単位のパラメータ上書き（M2-4 で program_intents から分離。issue #18
// の案 A の続き）。api だけが書き、ruler は読むだけ（program_intents と同じ規律）。
//
// overrides の中身は internal/api がマージする（reservation.ReservationOptions の型付き
// フィールドとして。docs/recording.md §4.2「jsonb を許す条件」）。SQL 側は
// 常に上書き後の完成形を受け取って書くだけで、jsonb の内容を検査・加工しない。
func (q *Queries) GetProgramOverrides(ctx context.Context, arg GetProgramOverridesParams) (ProgramOverride, error) {
	row := q.db.QueryRow(ctx, getProgramOverrides, arg.Site, arg.ProgramID)
	var i ProgramOverride
	err := row.Scan(
		&i.Site,
		&i.ProgramID,
		&i.Overrides,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProgramOverrides = `-- name: UpsertProgramOverrides :one
INSERT INTO program_overrides (
    site, program_id, overrides
) VALUES ($1, $2, $3)
ON CONFLICT (site, program_id) DO UPDATE SET
    overrides  = EXCLUDED.overrides,
    updated_at = now()
RETURNING site, program_id, overrides, created_at, updated_at
`

type UpsertProgramOverridesParams struct {
	Site      string
	ProgramID int64
	Overrides json.RawMessage
}

// program_start_at / program_duration_ms は #27 で program_snapshots に抽出され、
// program_overrides からは落ちた。FK (site, program_id) REFERENCES program_snapshots
// があるので、呼び出し側はこの INSERT より先に program_snapshots の行を
// upsert しておくこと。
func (q *Queries) UpsertProgramOverrides(ctx context.Context, arg UpsertProgramOverridesParams) (ProgramOverride, error) {
	row := q.db.QueryRow(ctx, upsertProgramOverrides, arg.Site, arg.ProgramID, arg.Overrides)
	var i ProgramOverride
	err := row.Scan(
		&i.Site,
		&i.ProgramID,
		&i.Overrides,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
