// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: program_intents.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const deleteEndedProgramIntents = `-- name: DeleteEndedProgramIntents :execrows
DELETE FROM program_intents
WHERE program_start_at + (program_duration_ms * interval '1 millisecond') < $1
`

// 番組終了後の GC。意図の寿命を放送の寿命に揃える。
func (q *Queries) DeleteEndedProgramIntents(ctx context.Context, programStartAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEndedProgramIntents, programStartAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProgramIntent = `-- name: DeleteProgramIntent :execrows
DELETE FROM program_intents WHERE site = $1 AND program_id = $2
`

type DeleteProgramIntentParams struct {
	Site      string
	ProgramID int64
}

func (q *Queries) DeleteProgramIntent(ctx context.Context, arg DeleteProgramIntentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProgramIntent, arg.Site, arg.ProgramID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProgramIntent = `-- name: GetProgramIntent :one
SELECT site, program_id, action, overrides, program_start_at, program_duration_ms, created_at, updated_at FROM program_intents WHERE site = $1 AND program_id = $2
`

type GetProgramIntentParams struct {
	Site      string
	ProgramID int64
}

func (q *Queries) GetProgramIntent(ctx context.Context, arg GetProgramIntentParams) (ProgramIntent, error) {
	row := q.db.QueryRow(ctx, getProgramIntent, arg.Site, arg.ProgramID)
	var i ProgramIntent
	err := row.Scan(
		&i.Site,
		&i.ProgramID,
		&i.Action,
		&i.Overrides,
		&i.ProgramStartAt,
		&i.ProgramDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSkippedProgramIntentsBySite = `-- name: ListSkippedProgramIntentsBySite :many
SELECT i.program_id, i.program_start_at, i.program_duration_ms, p.name
FROM program_intents i
LEFT JOIN epg_programs p ON p.site = i.site AND p.program_id = i.program_id
WHERE i.site = $1 AND i.action = 'skip'
ORDER BY i.program_start_at
`

type ListSkippedProgramIntentsBySiteRow struct {
	ProgramID         int64
	ProgramStartAt    time.Time
	ProgramDurationMs int64
	Name              *string
}

// shadow-diff（M2-14）用。skip 意図は reservations 行を持たないため
// （案 A の核心。上の UpsertProgramIntent のコメント参照）、EPGStation との
// 差分照合では program_intents を直接引く必要がある。番組名は表示のためだけに
// EPG プロジェクションから補う。放送終了間際で epg_programs から刈られていれば
// NULL のままでよい（照合キーは programId であってタイトルではない）。
func (q *Queries) ListSkippedProgramIntentsBySite(ctx context.Context, site string) ([]ListSkippedProgramIntentsBySiteRow, error) {
	rows, err := q.db.Query(ctx, listSkippedProgramIntentsBySite, site)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSkippedProgramIntentsBySiteRow
	for rows.Next() {
		var i ListSkippedProgramIntentsBySiteRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.ProgramStartAt,
			&i.ProgramDurationMs,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skipProgram = `-- name: SkipProgram :one
INSERT INTO program_intents (
    site, program_id, action, program_start_at, program_duration_ms
) VALUES ($1, $2, 'skip', $3, $4)
ON CONFLICT (site, program_id) DO UPDATE SET
    action     = 'skip',
    updated_at = now()
RETURNING site, program_id, action, overrides, program_start_at, program_duration_ms, created_at, updated_at
`

type SkipProgramParams struct {
	Site              string
	ProgramID         int64
	ProgramStartAt    time.Time
	ProgramDurationMs int64
}

// 取消（intent{skip}）は既存の overrides を保ったまま action だけを倒す。
// 番組情報のスナップショットは新規作成時のみ必要。
func (q *Queries) SkipProgram(ctx context.Context, arg SkipProgramParams) (ProgramIntent, error) {
	row := q.db.QueryRow(ctx, skipProgram,
		arg.Site,
		arg.ProgramID,
		arg.ProgramStartAt,
		arg.ProgramDurationMs,
	)
	var i ProgramIntent
	err := row.Scan(
		&i.Site,
		&i.ProgramID,
		&i.Action,
		&i.Overrides,
		&i.ProgramStartAt,
		&i.ProgramDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProgramIntent = `-- name: UpsertProgramIntent :one

INSERT INTO program_intents (
    site, program_id, action, overrides, program_start_at, program_duration_ms
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (site, program_id) DO UPDATE SET
    action     = EXCLUDED.action,
    overrides  = EXCLUDED.overrides,
    updated_at = now()
RETURNING site, program_id, action, overrides, program_start_at, program_duration_ms, created_at, updated_at
`

type UpsertProgramIntentParams struct {
	Site              string
	ProgramID         int64
	Action            string
	Overrides         json.RawMessage
	ProgramStartAt    time.Time
	ProgramDurationMs int64
}

// 番組単位のユーザー意図（issue #18 の案 A）。api だけが書き、ruler は読むだけ。
func (q *Queries) UpsertProgramIntent(ctx context.Context, arg UpsertProgramIntentParams) (ProgramIntent, error) {
	row := q.db.QueryRow(ctx, upsertProgramIntent,
		arg.Site,
		arg.ProgramID,
		arg.Action,
		arg.Overrides,
		arg.ProgramStartAt,
		arg.ProgramDurationMs,
	)
	var i ProgramIntent
	err := row.Scan(
		&i.Site,
		&i.ProgramID,
		&i.Action,
		&i.Overrides,
		&i.ProgramStartAt,
		&i.ProgramDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
