// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: program_intents.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const deleteEndedProgramIntents = `-- name: DeleteEndedProgramIntents :execrows
DELETE FROM program_intents
WHERE program_start_at + (program_duration_ms * interval '1 millisecond') < $1
`

// 番組終了後の GC。意図の寿命を放送の寿命に揃える。
func (q *Queries) DeleteEndedProgramIntents(ctx context.Context, programStartAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEndedProgramIntents, programStartAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProgramIntent = `-- name: DeleteProgramIntent :execrows
DELETE FROM program_intents WHERE site = $1 AND program_id = $2
`

type DeleteProgramIntentParams struct {
	Site      string
	ProgramID int64
}

func (q *Queries) DeleteProgramIntent(ctx context.Context, arg DeleteProgramIntentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProgramIntent, arg.Site, arg.ProgramID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProgramIntent = `-- name: GetProgramIntent :one
SELECT site, program_id, action, overrides, program_start_at, program_duration_ms, created_at, updated_at FROM program_intents WHERE site = $1 AND program_id = $2
`

type GetProgramIntentParams struct {
	Site      string
	ProgramID int64
}

func (q *Queries) GetProgramIntent(ctx context.Context, arg GetProgramIntentParams) (ProgramIntent, error) {
	row := q.db.QueryRow(ctx, getProgramIntent, arg.Site, arg.ProgramID)
	var i ProgramIntent
	err := row.Scan(
		&i.Site,
		&i.ProgramID,
		&i.Action,
		&i.Overrides,
		&i.ProgramStartAt,
		&i.ProgramDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const skipProgram = `-- name: SkipProgram :one
INSERT INTO program_intents (
    site, program_id, action, program_start_at, program_duration_ms
) VALUES ($1, $2, 'skip', $3, $4)
ON CONFLICT (site, program_id) DO UPDATE SET
    action     = 'skip',
    updated_at = now()
RETURNING site, program_id, action, overrides, program_start_at, program_duration_ms, created_at, updated_at
`

type SkipProgramParams struct {
	Site              string
	ProgramID         int64
	ProgramStartAt    time.Time
	ProgramDurationMs int64
}

// 取消（intent{skip}）は既存の overrides を保ったまま action だけを倒す。
// 番組情報のスナップショットは新規作成時のみ必要。
func (q *Queries) SkipProgram(ctx context.Context, arg SkipProgramParams) (ProgramIntent, error) {
	row := q.db.QueryRow(ctx, skipProgram,
		arg.Site,
		arg.ProgramID,
		arg.ProgramStartAt,
		arg.ProgramDurationMs,
	)
	var i ProgramIntent
	err := row.Scan(
		&i.Site,
		&i.ProgramID,
		&i.Action,
		&i.Overrides,
		&i.ProgramStartAt,
		&i.ProgramDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProgramIntent = `-- name: UpsertProgramIntent :one

INSERT INTO program_intents (
    site, program_id, action, overrides, program_start_at, program_duration_ms
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (site, program_id) DO UPDATE SET
    action     = EXCLUDED.action,
    overrides  = EXCLUDED.overrides,
    updated_at = now()
RETURNING site, program_id, action, overrides, program_start_at, program_duration_ms, created_at, updated_at
`

type UpsertProgramIntentParams struct {
	Site              string
	ProgramID         int64
	Action            string
	Overrides         json.RawMessage
	ProgramStartAt    time.Time
	ProgramDurationMs int64
}

// 番組単位のユーザー意図（issue #18 の案 A）。api だけが書き、ruler は読むだけ。
func (q *Queries) UpsertProgramIntent(ctx context.Context, arg UpsertProgramIntentParams) (ProgramIntent, error) {
	row := q.db.QueryRow(ctx, upsertProgramIntent,
		arg.Site,
		arg.ProgramID,
		arg.Action,
		arg.Overrides,
		arg.ProgramStartAt,
		arg.ProgramDurationMs,
	)
	var i ProgramIntent
	err := row.Scan(
		&i.Site,
		&i.ProgramID,
		&i.Action,
		&i.Overrides,
		&i.ProgramStartAt,
		&i.ProgramDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
