// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recording_policy.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const getReservationEncodePolicy = `-- name: GetReservationEncodePolicy :one
SELECT r.id, r.site, r.program_id, r.rule_id, r.base, r.created_at, r.updated_at, r.dedup_match_recording_id, r.dedup_similarity, i.action AS intent_action, o.overrides AS overrides
FROM reservations r
LEFT JOIN program_intents   i ON i.site = r.site AND i.program_id = r.program_id
LEFT JOIN program_overrides o ON o.site = r.site AND o.program_id = r.program_id
WHERE r.id = $1
`

type GetReservationEncodePolicyRow struct {
	Reservation  Reservation
	IntentAction *string
	Overrides    json.RawMessage
}

// ingest が recordings.keep_original / encode_profiles を焼くために読む実効オプション
// （M3-14、issue #103）。reservations.sql は #52（M2 出口基準の並走）の間は触らない
// 方針のため、読み取り専用のこのクエリを新規ファイルに切る
// （CLAUDE.md「クエリファイルは新規に切る」）。
//
// reservations.sql の GetReservationFull と似ているが、program_snapshots への
// INNER JOIN をしない。ingest がここで必要なのは base / overrides / intent の
// 3 つだけで、番組の事実のスナップショット（title 等）は要らない。
// この 2 つの jsonb（base / overrides）を扱う箇所は db.EffectiveOptions を通す
// （CLAUDE.md 不変条件 9/12 の教訓）。呼び出し側（internal/worker/ingest.go）の責務。
func (q *Queries) GetReservationEncodePolicy(ctx context.Context, id int64) (GetReservationEncodePolicyRow, error) {
	row := q.db.QueryRow(ctx, getReservationEncodePolicy, id)
	var i GetReservationEncodePolicyRow
	err := row.Scan(
		&i.Reservation.ID,
		&i.Reservation.Site,
		&i.Reservation.ProgramID,
		&i.Reservation.RuleID,
		&i.Reservation.Base,
		&i.Reservation.CreatedAt,
		&i.Reservation.UpdatedAt,
		&i.Reservation.DedupMatchRecordingID,
		&i.Reservation.DedupSimilarity,
		&i.IntentAction,
		&i.Overrides,
	)
	return i, err
}
