// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recordings.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const appendQualityEvents = `-- name: AppendQualityEvents :exec
UPDATE recordings
SET quality_events = quality_events || $1::jsonb,
    updated_at = now()
WHERE id = $2
`

type AppendQualityEventsParams struct {
	Events json.RawMessage
	ID     int64
}

func (q *Queries) AppendQualityEvents(ctx context.Context, arg AppendQualityEventsParams) error {
	_, err := q.db.Exec(ctx, appendQualityEvents, arg.Events, arg.ID)
	return err
}

const createFailedRecording = `-- name: CreateFailedRecording :exec
INSERT INTO recordings (
    reservation_id, rule_id, source, site,
    network_id, service_id, event_id, service_name,
    channel_type, channel, title, description,
    extended, genres, is_free,
    program_start_at, program_duration_ms,
    status, quality_events
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15,
    $16, $17,
    'failed', $18
)
ON CONFLICT (site, network_id, service_id, event_id) WHERE deleted_at IS NULL
DO UPDATE SET
    quality_events = recordings.quality_events || EXCLUDED.quality_events,
    updated_at = now()
`

type CreateFailedRecordingParams struct {
	ReservationID     *int64
	RuleID            *int64
	Source            string
	Site              string
	NetworkID         int32
	ServiceID         int32
	EventID           int32
	ServiceName       string
	ChannelType       string
	Channel           string
	Title             string
	Description       *string
	Extended          json.RawMessage
	Genres            json.RawMessage
	IsFree            bool
	ProgramStartAt    time.Time
	ProgramDurationMs int64
	QualityEvents     json.RawMessage
}

func (q *Queries) CreateFailedRecording(ctx context.Context, arg CreateFailedRecordingParams) error {
	_, err := q.db.Exec(ctx, createFailedRecording,
		arg.ReservationID,
		arg.RuleID,
		arg.Source,
		arg.Site,
		arg.NetworkID,
		arg.ServiceID,
		arg.EventID,
		arg.ServiceName,
		arg.ChannelType,
		arg.Channel,
		arg.Title,
		arg.Description,
		arg.Extended,
		arg.Genres,
		arg.IsFree,
		arg.ProgramStartAt,
		arg.ProgramDurationMs,
		arg.QualityEvents,
	)
	return err
}

const createRecording = `-- name: CreateRecording :one
INSERT INTO recordings (
    reservation_id, rule_id, source, site,
    network_id, service_id, event_id, service_name,
    channel_type, channel, title, description,
    extended, genres, is_free,
    program_start_at, program_duration_ms,
    status, started_at, ended_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15,
    $16, $17,
    $18, $19, $20
) RETURNING id
`

type CreateRecordingParams struct {
	ReservationID     *int64
	RuleID            *int64
	Source            string
	Site              string
	NetworkID         int32
	ServiceID         int32
	EventID           int32
	ServiceName       string
	ChannelType       string
	Channel           string
	Title             string
	Description       *string
	Extended          json.RawMessage
	Genres            json.RawMessage
	IsFree            bool
	ProgramStartAt    time.Time
	ProgramDurationMs int64
	Status            string
	StartedAt         *time.Time
	EndedAt           *time.Time
}

func (q *Queries) CreateRecording(ctx context.Context, arg CreateRecordingParams) (int64, error) {
	row := q.db.QueryRow(ctx, createRecording,
		arg.ReservationID,
		arg.RuleID,
		arg.Source,
		arg.Site,
		arg.NetworkID,
		arg.ServiceID,
		arg.EventID,
		arg.ServiceName,
		arg.ChannelType,
		arg.Channel,
		arg.Title,
		arg.Description,
		arg.Extended,
		arg.Genres,
		arg.IsFree,
		arg.ProgramStartAt,
		arg.ProgramDurationMs,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listRecordingDropStats = `-- name: ListRecordingDropStats :many
SELECT d.pid, d.packets, d.drops, d.errors, d.scrambled, d.pid_type
FROM drop_stats d
JOIN media_assets a ON a.id = d.media_asset_id
WHERE a.recording_id = $1 AND a.kind = 'original' AND a.state <> 'deleted'
ORDER BY d.pid
`

type ListRecordingDropStatsRow struct {
	Pid       int32
	Packets   int64
	Drops     int64
	Errors    int64
	Scrambled int64
	PidType   *string
}

func (q *Queries) ListRecordingDropStats(ctx context.Context, recordingID int64) ([]ListRecordingDropStatsRow, error) {
	rows, err := q.db.Query(ctx, listRecordingDropStats, recordingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordingDropStatsRow
	for rows.Next() {
		var i ListRecordingDropStatsRow
		if err := rows.Scan(
			&i.Pid,
			&i.Packets,
			&i.Drops,
			&i.Errors,
			&i.Scrambled,
			&i.PidType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordings = `-- name: ListRecordings :many
SELECT
    r.id, r.reservation_id, r.rule_id, r.source, r.site, r.network_id, r.service_id, r.event_id, r.service_name, r.channel_type, r.channel, r.title, r.description, r.extended, r.genres, r.is_free, r.program_start_at, r.program_duration_ms, r.status, r.started_at, r.ended_at, r.keep_original, r.encode_profiles, r.quality_events, r.deleted_at, r.created_at, r.updated_at, r.purge_after,
    a.size_bytes                        AS original_size_bytes,
    COALESCE(d.packets, 0)::bigint      AS drop_packets,
    COALESCE(d.drops, 0)::bigint        AS drop_drops,
    COALESCE(d.errors, 0)::bigint       AS drop_errors,
    COALESCE(d.scrambled, 0)::bigint    AS drop_scrambled,
    -- ブラウザ再生用。desired（r.encode_profiles）ではなく observed（active encoded）。
    -- sqlc は array_agg の型を推論しきれないことがあるので text[] に明示キャストする。
    (
        SELECT coalesce(array_agg(e.profile ORDER BY e.profile), '{}')::text[]
        FROM media_assets e
        WHERE e.recording_id = r.id
          AND e.kind = 'encoded'
          AND e.state = 'active'
          AND e.profile IS NOT NULL
    ) AS available_encoded_profiles
FROM recordings r
LEFT JOIN media_assets a
    ON a.recording_id = r.id AND a.kind = 'original' AND a.state <> 'deleted'
LEFT JOIN LATERAL (
    SELECT sum(packets) AS packets, sum(drops) AS drops,
           sum(errors) AS errors, sum(scrambled) AS scrambled
    FROM drop_stats
    WHERE media_asset_id = a.id
) d ON true
WHERE r.site = $1 AND r.deleted_at IS NULL
ORDER BY r.program_start_at DESC, r.id DESC
`

type ListRecordingsRow struct {
	ID                       int64
	ReservationID            *int64
	RuleID                   *int64
	Source                   string
	Site                     string
	NetworkID                int32
	ServiceID                int32
	EventID                  int32
	ServiceName              string
	ChannelType              string
	Channel                  string
	Title                    string
	Description              *string
	Extended                 json.RawMessage
	Genres                   json.RawMessage
	IsFree                   bool
	ProgramStartAt           time.Time
	ProgramDurationMs        int64
	Status                   string
	StartedAt                *time.Time
	EndedAt                  *time.Time
	KeepOriginal             string
	EncodeProfiles           []string
	QualityEvents            json.RawMessage
	DeletedAt                *time.Time
	CreatedAt                time.Time
	UpdatedAt                time.Time
	PurgeAfter               *time.Time
	OriginalSizeBytes        *int64
	DropPackets              int64
	DropDrops                int64
	DropErrors               int64
	DropScrambled            int64
	AvailableEncodedProfiles []string
}

// 録画一覧。原本のサイズと PID 別 drop_stats の合計、
// 再生可能な encoded プロファイル名を同梱する。
// PID 別の内訳は行数が多く一覧では使わないので ListRecordingDropStats で別に取る。
func (q *Queries) ListRecordings(ctx context.Context, site string) ([]ListRecordingsRow, error) {
	rows, err := q.db.Query(ctx, listRecordings, site)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordingsRow
	for rows.Next() {
		var i ListRecordingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.RuleID,
			&i.Source,
			&i.Site,
			&i.NetworkID,
			&i.ServiceID,
			&i.EventID,
			&i.ServiceName,
			&i.ChannelType,
			&i.Channel,
			&i.Title,
			&i.Description,
			&i.Extended,
			&i.Genres,
			&i.IsFree,
			&i.ProgramStartAt,
			&i.ProgramDurationMs,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.KeepOriginal,
			&i.EncodeProfiles,
			&i.QualityEvents,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PurgeAfter,
			&i.OriginalSizeBytes,
			&i.DropPackets,
			&i.DropDrops,
			&i.DropErrors,
			&i.DropScrambled,
			&i.AvailableEncodedProfiles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecordingStatus = `-- name: UpdateRecordingStatus :exec
UPDATE recordings SET
    status     = CASE WHEN status IN ('finished', 'failed') THEN status ELSE $1 END,
    started_at = COALESCE(started_at, $2),
    ended_at   = CASE WHEN $3::timestamptz IS NOT NULL THEN $3 ELSE ended_at END,
    updated_at = now()
WHERE id = $4
`

type UpdateRecordingStatusParams struct {
	NewStatus string
	StartedAt *time.Time
	EndedAt   *time.Time
	ID        int64
}

func (q *Queries) UpdateRecordingStatus(ctx context.Context, arg UpdateRecordingStatusParams) error {
	_, err := q.db.Exec(ctx, updateRecordingStatus,
		arg.NewStatus,
		arg.StartedAt,
		arg.EndedAt,
		arg.ID,
	)
	return err
}
