// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const createManualReservation = `-- name: CreateManualReservation :one
INSERT INTO reservations (site, program_id)
VALUES ($1, $2)
RETURNING site, program_id, rule_id, base, created_at, updated_at, dedup_match_recording_id, dedup_similarity
`

type CreateManualReservationParams struct {
	Site      string
	ProgramID int64
}

// テスト用の直接 INSERT ヘルパー。reservations の実運用上の書き手は
// ruler の一括 INSERT（internal/ruler/sql.go）で、api はこの表に INSERT を
// 一切書かない（M3-1、issue #29「導出器が作るキーを宛先にしない」の帰結）。
// 例外は DELETE のみ: DeleteRule がルール削除と同一 tx で
// DeleteReservationsByRuleWithoutIntent（rules.sql）を実行する。明示操作は
// 同期・ブレーカー対象外という既存の線に乗るための例外で、WHERE が
// program_investments を適用の瞬間に再評価するので #29 の窓は生じない
// （docs/recording/reservation-model.md §4.4「取消は `PUT .../intent {action:
// skip}`。api は `reservations` に触れない（M3-1）」に追記した例外）。
//
// 番組の事実のスナップショット（title / 開始時刻 / 尺 / チャンネル識別）は
// program_snapshots に抽出された（#27）。FK (site, program_id) REFERENCES
// program_snapshots があるので、呼び出し側（テストの fixture）はこの
// INSERT より先に program_snapshots の行を upsert しておくこと。
//
// reservations.source は持たない（issue #26 で削除）。この予約が「手動」で
// あることは、program_intents.action='record' の行がそのまま表す。
func (q *Queries) CreateManualReservation(ctx context.Context, arg CreateManualReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createManualReservation, arg.Site, arg.ProgramID)
	var i Reservation
	err := row.Scan(
		&i.Site,
		&i.ProgramID,
		&i.RuleID,
		&i.Base,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DedupMatchRecordingID,
		&i.DedupSimilarity,
	)
	return i, err
}

const createNeverScheduledEvent = `-- name: CreateNeverScheduledEvent :execrows
INSERT INTO never_scheduled_events (site, network_id, service_id, event_id)
SELECT $1, $2, $3, $4
WHERE NOT EXISTS (
    SELECT 1 FROM recordings rec
    WHERE rec.site = $1
      AND rec.network_id = $2
      AND rec.service_id = $3
      AND rec.event_id = $4
      AND rec.deleted_at IS NULL
      AND rec.superseded_at IS NULL
)
ON CONFLICT (site, network_id, service_id, event_id) DO NOTHING
`

type CreateNeverScheduledEventParams struct {
	Site      string
	NetworkID int32
	ServiceID int32
	EventID   int32
}

// 「番組終了時点で schedule が一度も観測されなかった」欠測を記録する
// （issue #318。旧 CreateNeverScheduledRecording を置き換える）。書き手は
// reconciler.recordNeverScheduled だけ。行の存在＝欠測なので、宛先は放送
// イベント (site, network_id, service_id, event_id) の PK。
//
// 書き込み条件は「その放送イベントに生きている recordings 行が無いこと」。
// live の定義は recordings_unique_active_event の部分述語と同じ
// （deleted_at IS NULL AND superseded_at IS NULL）で、本物の record が先にあれば
// 欠測を書かない。ON CONFLICT DO NOTHING は前パスで既に書いた欠測、または
// 他パスとの競合で 2 行目を作らない（CLAUDE.md 不変条件 5: レベルトリガー）。
// :execrows で実際に INSERT できたか（1）条件不成立/既存か（0）を呼び出し側が
// 区別できる。
func (q *Queries) CreateNeverScheduledEvent(ctx context.Context, arg CreateNeverScheduledEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, createNeverScheduledEvent,
		arg.Site,
		arg.NetworkID,
		arg.ServiceID,
		arg.EventID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getReservationBySiteAndProgramID = `-- name: GetReservationBySiteAndProgramID :one
SELECT rule_id, base FROM reservations
WHERE site = $1 AND program_id = $2
`

type GetReservationBySiteAndProgramIDParams struct {
	Site      string
	ProgramID int64
}

type GetReservationBySiteAndProgramIDRow struct {
	RuleID *int64
	Base   json.RawMessage
}

// base も返す（issue #104: PatchProgramOverrides が「既存 override + このパッチ +
// ルールの base」をマージした実効値を検証するために必要）。既存の呼び出し元
// （internal/watcher, internal/reconciler）は RuleID しか見ていないので
// 列追加の影響を受けない。
func (q *Queries) GetReservationBySiteAndProgramID(ctx context.Context, arg GetReservationBySiteAndProgramIDParams) (GetReservationBySiteAndProgramIDRow, error) {
	row := q.db.QueryRow(ctx, getReservationBySiteAndProgramID, arg.Site, arg.ProgramID)
	var i GetReservationBySiteAndProgramIDRow
	err := row.Scan(&i.RuleID, &i.Base)
	return i, err
}

const getReservationFullBySiteAndProgramID = `-- name: GetReservationFullBySiteAndProgramID :one
SELECT r.site, r.program_id, r.rule_id, r.base, r.created_at, r.updated_at, r.dedup_match_recording_id, r.dedup_similarity, s.site, s.program_id, s.title, s.start_at, s.duration_ms, s.network_id, s.service_id, s.channel_type, s.channel, s.updated_at, s.event_id, s.service_name, i.action AS intent_action, o.overrides AS overrides,
       (EXISTS (
           SELECT 1 FROM never_scheduled_events nse
           WHERE nse.site = r.site
             AND nse.network_id = s.network_id
             AND nse.service_id = s.service_id
             AND nse.event_id = s.event_id
       ) AND NOT EXISTS (
           SELECT 1 FROM recordings rec
           WHERE rec.site = r.site
             AND rec.network_id = s.network_id
             AND rec.service_id = s.service_id
             AND rec.event_id = s.event_id
       ))::boolean AS never_recorded
FROM reservations r
JOIN program_snapshots s ON s.site = r.site AND s.program_id = r.program_id
LEFT JOIN program_intents i ON i.site = r.site AND i.program_id = r.program_id
LEFT JOIN program_overrides o ON o.site = r.site AND o.program_id = r.program_id
WHERE r.site = $1 AND r.program_id = $2
`

type GetReservationFullBySiteAndProgramIDParams struct {
	Site      string
	ProgramID int64
}

type GetReservationFullBySiteAndProgramIDRow struct {
	Reservation     Reservation
	ProgramSnapshot ProgramSnapshot
	IntentAction    *string
	Overrides       json.RawMessage
	NeverRecorded   bool
}

// 予約とユーザー意図・上書き・番組スナップショットを 1 行に合わせて返す。
// action は program_intents、overrides は program_overrides（M2-4 で分離）
// にあり、予約が存在しても意図・上書きのどちらかしかない（あるいはどちらも
// 無い）ことがあるので両方 LEFT JOIN する。番組スナップショットは FK が
// あるので必ず存在する（INNER JOIN）。
//
// never_recorded は orphaned_at の代わりに読むたび導出する列（CLAUDE.md
// 不変条件 9）。放送イベントキーで never_scheduled_events 表を引き、欠測行が
// あり、かつそのイベントに本物の recordings 行が 1 つも無いときだけ true。
//
// recordings の照合は live 限定にしない --- 限定すると、後から本物の record が
// 来たときに never-scheduled 擬似行を永久に supersede してしまい、ごみ箱操作後も
// orphaned に戻らなくなる。同じ意味を `NOT EXISTS(recordings)` で保つ（#59
// 「録れたのに orphaned のまま」の再発を防ぐ）。同期除外は recordings の有無を
// 見ず、一度欠測と書いたイベントを対象に戻さないので、表示とは意図的に別の述語
// である。
//
// 宛先は (site, program_id)（issue #99）。書き込み側
// （program_intents / program_overrides、issue #29）は既にこのキーに寄っており、
// reservations 自体もこの複合キーを主キーとして持つ。予約行が ruler の導出削除・
// 再実体化を跨いでも、このキーは変わらない（#53 が mirakc の tag を
// program:{programId} に変えたのと同じ論法）。
func (q *Queries) GetReservationFullBySiteAndProgramID(ctx context.Context, arg GetReservationFullBySiteAndProgramIDParams) (GetReservationFullBySiteAndProgramIDRow, error) {
	row := q.db.QueryRow(ctx, getReservationFullBySiteAndProgramID, arg.Site, arg.ProgramID)
	var i GetReservationFullBySiteAndProgramIDRow
	err := row.Scan(
		&i.Reservation.Site,
		&i.Reservation.ProgramID,
		&i.Reservation.RuleID,
		&i.Reservation.Base,
		&i.Reservation.CreatedAt,
		&i.Reservation.UpdatedAt,
		&i.Reservation.DedupMatchRecordingID,
		&i.Reservation.DedupSimilarity,
		&i.ProgramSnapshot.Site,
		&i.ProgramSnapshot.ProgramID,
		&i.ProgramSnapshot.Title,
		&i.ProgramSnapshot.StartAt,
		&i.ProgramSnapshot.DurationMs,
		&i.ProgramSnapshot.NetworkID,
		&i.ProgramSnapshot.ServiceID,
		&i.ProgramSnapshot.ChannelType,
		&i.ProgramSnapshot.Channel,
		&i.ProgramSnapshot.UpdatedAt,
		&i.ProgramSnapshot.EventID,
		&i.ProgramSnapshot.ServiceName,
		&i.IntentAction,
		&i.Overrides,
		&i.NeverRecorded,
	)
	return i, err
}

const listReservationsForSyncEvaluation = `-- name: ListReservationsForSyncEvaluation :many
SELECT r.site, r.program_id, r.rule_id, r.base, r.created_at, r.updated_at, r.dedup_match_recording_id, r.dedup_similarity, s.site, s.program_id, s.title, s.start_at, s.duration_ms, s.network_id, s.service_id, s.channel_type, s.channel, s.updated_at, s.event_id, s.service_name, i.action AS intent_action, o.overrides AS overrides
FROM reservations r
JOIN program_snapshots s ON s.site = r.site AND s.program_id = r.program_id
LEFT JOIN program_intents i ON i.site = r.site AND i.program_id = r.program_id
LEFT JOIN program_overrides o ON o.site = r.site AND o.program_id = r.program_id
WHERE r.site = $1
  AND NOT EXISTS (
      SELECT 1 FROM never_scheduled_events nse
      -- 宛先のキーは**放送イベント**であって予約行の導出キーではない。
      -- 予約行の再実体化に依存すると、EPG フリッカーやルール編集で予約行が作り直された瞬間に
      -- recordings.reservation_id（issue #158 で列自体を削除済み）は当時 ON DELETE SET NULL だった。予約行のキーで
      -- 引いた観測が切れ、「欠測行が無い」ことになり、終了済み予約が毎パス desired に
      -- 戻り続ける（CLAUDE.md 不変条件 9 の identity: 導出器が作るキーを
      -- 宛先にしない）。
      WHERE nse.site = r.site
        AND nse.network_id = s.network_id
        AND nse.service_id = s.service_id
        AND nse.event_id = s.event_id
  )
ORDER BY s.start_at
`

type ListReservationsForSyncEvaluationRow struct {
	Reservation     Reservation
	ProgramSnapshot ProgramSnapshot
	IntentAction    *string
	Overrides       json.RawMessage
}

// 同期対象の「候補」を返すクエリ（issue #54）。
//
// **除外条件は issue #98 で orphaned_at IS NULL から書き換えた。**
// reconciler.markOrphaned が書いていた不可逆な観測（「番組終了後に schedule が
// 観測されなかった」）は、#98 の決定で recordings の試行行（status='failed' +
// quality_events に recording.never-scheduled）に移設され、orphaned_at 列
// 自体が無くなった。
//
// 除外条件を「その放送イベントに既に never-scheduled の recordings 行がある」に
// 置き換える。never-scheduled という特定の quality_events マーカーだけを
// 見て、status='failed' の行全般では絞らないのが要点 ---
// handleRecordingFailed（internal/watcher）が作る「録画開始後に mirakc が
// 失敗を報告した」failed 行まで含めて除外すると、mirakc が schedule を
// 消した後にレコンサイラが再作成を試みる既存の再試行経路（#98 とは無関係の
// 挙動）を壊してしまう。never-scheduled は「番組終了かつ schedule 非観測」
// でしか作られない一方向の事実なので、これだけを除外条件にすれば
// 再試行経路には触れない。
//
// 「番組が既に終了しているか」で直接絞らない（now() との比較にしない）
// 理由: reconciler.programEnded が実際の POST/文言判定を毎パス評価し直す
// ので、ここでの事前絞り込みは効率のためだけに存在してよい。だが
// now() 比較を SQL に持ち込むと、固定時刻を使うテスト（過去に書かれた
// fixture が「将来」のつもりで書いた日時が実行時点で過去になっている等。
// cmd/rokuban/shadowdiff_test.go で実例あり）が経過時間に依存して壊れる。
// never_scheduled_events 表の行の存在という「reconciler 自身が過去に書いた
// 事実」を条件にすればテストの実行時刻に依存しない（reconciler が実際に欠測
// 行を作らない限り除外されない）。
//
// 旧名 ListSyncableReservationsBySite は「もう絞ってある」と約束してしまって
// いた。その約束を信じて shadow-diff（cmd/rokuban/shadowdiff.go）の書き手は
// effective.skip の絞り込みを移植し忘れ、M2-6 の重複排除が base.skip=true を
// 立てた予約を「EPGStation と一致（Both）」と誤報告する見逃しが M2 の出口
// 基準の測定器に入り込んだ（issue #54）。「同期対象か」を最終的に決めるのは
// effective.skip（base + overrides + program_intents.action の合成）であり、
// この行だけでは絞り切れていない。絞り込みは呼び出し元が
// db.EvaluateSyncCandidates（internal/db/sync.go）に通して行う。
//
// 番組の開始時刻・尺（reconciler の開始遅延検出に使う）は program_snapshots に
// 移設された（#27）ので JOIN する。FK があるので必ず存在する。
//
// 欠測除外の述語は never_scheduled_events 表を放送イベントキーで引く NOT EXISTS
// で、overlaps.sql の ListOverlappingReservations / capacity.sql の
// ListCapacityDemand と全く同じ。表示用の never_recorded（このファイルの
// GetReservationFull 等）が本物の recordings 行の不在も条件にする意図的に別の
// 述語であることと対比すること --- 同期除外は recordings の有無を見ず、一度
// 欠測と判定された放送イベントを、その後本物の record が来ても対象に戻さない。
func (q *Queries) ListReservationsForSyncEvaluation(ctx context.Context, site string) ([]ListReservationsForSyncEvaluationRow, error) {
	rows, err := q.db.Query(ctx, listReservationsForSyncEvaluation, site)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservationsForSyncEvaluationRow
	for rows.Next() {
		var i ListReservationsForSyncEvaluationRow
		if err := rows.Scan(
			&i.Reservation.Site,
			&i.Reservation.ProgramID,
			&i.Reservation.RuleID,
			&i.Reservation.Base,
			&i.Reservation.CreatedAt,
			&i.Reservation.UpdatedAt,
			&i.Reservation.DedupMatchRecordingID,
			&i.Reservation.DedupSimilarity,
			&i.ProgramSnapshot.Site,
			&i.ProgramSnapshot.ProgramID,
			&i.ProgramSnapshot.Title,
			&i.ProgramSnapshot.StartAt,
			&i.ProgramSnapshot.DurationMs,
			&i.ProgramSnapshot.NetworkID,
			&i.ProgramSnapshot.ServiceID,
			&i.ProgramSnapshot.ChannelType,
			&i.ProgramSnapshot.Channel,
			&i.ProgramSnapshot.UpdatedAt,
			&i.ProgramSnapshot.EventID,
			&i.ProgramSnapshot.ServiceName,
			&i.IntentAction,
			&i.Overrides,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsFull = `-- name: ListReservationsFull :many
SELECT r.site, r.program_id, r.rule_id, r.base, r.created_at, r.updated_at, r.dedup_match_recording_id, r.dedup_similarity, s.site, s.program_id, s.title, s.start_at, s.duration_ms, s.network_id, s.service_id, s.channel_type, s.channel, s.updated_at, s.event_id, s.service_name, i.action AS intent_action, o.overrides AS overrides,
       (EXISTS (
           SELECT 1 FROM never_scheduled_events nse
           WHERE nse.site = r.site
             AND nse.network_id = s.network_id
             AND nse.service_id = s.service_id
             AND nse.event_id = s.event_id
       ) AND NOT EXISTS (
           SELECT 1 FROM recordings rec
           WHERE rec.site = r.site
             AND rec.network_id = s.network_id
             AND rec.service_id = s.service_id
             AND rec.event_id = s.event_id
       ))::boolean AS never_recorded
FROM reservations r
JOIN program_snapshots s ON s.site = r.site AND s.program_id = r.program_id
LEFT JOIN program_intents i ON i.site = r.site AND i.program_id = r.program_id
LEFT JOIN program_overrides o ON o.site = r.site AND o.program_id = r.program_id
ORDER BY r.site, s.start_at
`

type ListReservationsFullRow struct {
	Reservation     Reservation
	ProgramSnapshot ProgramSnapshot
	IntentAction    *string
	Overrides       json.RawMessage
	NeverRecorded   bool
}

// never_recorded は GetReservationFullBySiteAndProgramID と同じ導出（コメント参照）。
//
// GET /api/reservations は全サイトを返す（issue #184 M4-12。api は不変条件 1 に
// より site に束縛されないため、site 絞り込みは持たない）。並び順は site をまず
// 揃えて start_at にする --- site 単体の ORDER BY start_at だと複数サイトの行が
// 入り交じり、同一サイト内の時系列を読み取りにくい。
func (q *Queries) ListReservationsFull(ctx context.Context) ([]ListReservationsFullRow, error) {
	rows, err := q.db.Query(ctx, listReservationsFull)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservationsFullRow
	for rows.Next() {
		var i ListReservationsFullRow
		if err := rows.Scan(
			&i.Reservation.Site,
			&i.Reservation.ProgramID,
			&i.Reservation.RuleID,
			&i.Reservation.Base,
			&i.Reservation.CreatedAt,
			&i.Reservation.UpdatedAt,
			&i.Reservation.DedupMatchRecordingID,
			&i.Reservation.DedupSimilarity,
			&i.ProgramSnapshot.Site,
			&i.ProgramSnapshot.ProgramID,
			&i.ProgramSnapshot.Title,
			&i.ProgramSnapshot.StartAt,
			&i.ProgramSnapshot.DurationMs,
			&i.ProgramSnapshot.NetworkID,
			&i.ProgramSnapshot.ServiceID,
			&i.ProgramSnapshot.ChannelType,
			&i.ProgramSnapshot.Channel,
			&i.ProgramSnapshot.UpdatedAt,
			&i.ProgramSnapshot.EventID,
			&i.ProgramSnapshot.ServiceName,
			&i.IntentAction,
			&i.Overrides,
			&i.NeverRecorded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
