// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package sqlcgen

import (
	"context"
)

const getReservation = `-- name: GetReservation :one
SELECT id, rule_id, source FROM reservations
WHERE id = $1
`

type GetReservationRow struct {
	ID     int64
	RuleID *int64
	Source string
}

func (q *Queries) GetReservation(ctx context.Context, id int64) (GetReservationRow, error) {
	row := q.db.QueryRow(ctx, getReservation, id)
	var i GetReservationRow
	err := row.Scan(&i.ID, &i.RuleID, &i.Source)
	return i, err
}

const getReservationBySiteAndProgramID = `-- name: GetReservationBySiteAndProgramID :one
SELECT id, rule_id, source FROM reservations
WHERE site = $1 AND program_id = $2
`

type GetReservationBySiteAndProgramIDParams struct {
	Site      string
	ProgramID int64
}

type GetReservationBySiteAndProgramIDRow struct {
	ID     int64
	RuleID *int64
	Source string
}

func (q *Queries) GetReservationBySiteAndProgramID(ctx context.Context, arg GetReservationBySiteAndProgramIDParams) (GetReservationBySiteAndProgramIDRow, error) {
	row := q.db.QueryRow(ctx, getReservationBySiteAndProgramID, arg.Site, arg.ProgramID)
	var i GetReservationBySiteAndProgramIDRow
	err := row.Scan(&i.ID, &i.RuleID, &i.Source)
	return i, err
}
