// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ruler.sql

package sqlcgen

import (
	"context"
)

const deleteReleasedReservationsBySiteAndProgramIDs = `-- name: DeleteReleasedReservationsBySiteAndProgramIDs :many
DELETE FROM reservations r
WHERE r.site = $1 AND r.program_id = ANY($2::bigint[])
  AND NOT EXISTS (
      SELECT 1 FROM program_investments v
      WHERE v.site = r.site AND v.program_id = r.program_id
  )
  AND (
      r.rule_id IS NULL
      OR EXISTS (
          SELECT 1 FROM program_intents i
          WHERE i.site = r.site AND i.program_id = r.program_id AND i.action = 'skip'
      )
  )
RETURNING r.program_id
`

type DeleteReleasedReservationsBySiteAndProgramIDsParams struct {
	Site       string
	ProgramIds []int64
}

// desired から外れた予約のうち、**外れた理由がユーザーの明示操作からしか
// 説明できない**ものを削除し、実際に消した programId を返す。呼び出し側
// （runPassForSite）はこれを大量削除サーキットブレーカーの対象にしない ---
// 「ルール x EPG」から導出される削除だけを止めるのがブレーカーの守備範囲で
// （docs/recording.md §3.2「大量削除サーキットブレーカー」）、下の 2 条件は
// EPG の欠損・フリッカーでは成立しないため。
//
// 明示操作である条件（上の DELETE と同じ NOT EXISTS program_investments に加えて、
// 次のいずれか）:
//
//	r.rule_id IS NULL
//	  いまルールが base を供給していない = この行を desired にしていたのは
//	  投資（record 意図 ∪ overrides）だけだった。その投資が今は無いのだから、
//	  desired から外したのは投資を消した操作しかありえない。rule_id を書くのは
//	  ruler の upsert だけで、desired から外れた行はそのパスで upsert されない
//	  （EPG が動いても既存の rule_id は据え置かれる）ため、EPG 由来の unmatch が
//	  この条件を作ることはない。
//	program_intents.action = 'skip'
//	  ユーザーが「録るな」と書いた。program_intents を書くのは api だけ。
//
// 逆に rule_id が非 NULL で skip 意図も無い行は「ルールが base を供給していたのに
// マッチしなくなった」= EPG 由来と区別できない削除であり、この文の対象外
// （上の DeleteReservationsBySiteAndProgramIDs 側でブレーカーを通す）。
//
// 分類そのものをこの WHERE に置いてあるのは #29 型の窓を作らないため。呼び出し側は
// toDelete 全体をこの文に渡し、RETURNING で「実際に明示操作由来として消えた集合」を
// 受け取って、その差集合をブレーカー対象の導出削除とする。分類がトランザクション外の
// 古い読み取りで決まる余地がない（上の DELETE と同じ規律）。
func (q *Queries) DeleteReleasedReservationsBySiteAndProgramIDs(ctx context.Context, arg DeleteReleasedReservationsBySiteAndProgramIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, deleteReleasedReservationsBySiteAndProgramIDs, arg.Site, arg.ProgramIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var program_id int64
		if err := rows.Scan(&program_id); err != nil {
			return nil, err
		}
		items = append(items, program_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteReservationRuleMatchesBySite = `-- name: DeleteReservationRuleMatchesBySite :exec
DELETE FROM reservation_rule_matches
WHERE reservation_id IN (SELECT id FROM reservations WHERE site = $1)
`

// reservation_rule_matches はサイト内の予約に紐づく行を毎パス全消しして入れ直す
// （insertReservationRuleMatchesSQL のコメント参照。この表には SSE 用の行トリガーが
// ないので差分書き込みは要求されない）。
//
// 対象を「今回マッチした programId」に絞ると、ルールを削除ではなく無効化した
// （ListEnabledRules から外れる）、あるいはルールの条件を変えてマッチしなくなったが
// intent/overrides のおかげで予約行自体は生き残っている、という経路で古いマッチ行が
// 掃除されずに残り続ける（導出表が毎パス作り直されない = CLAUDE.md 不変条件 9 違反。
// ルール自体の削除は reservation_rule_matches.rule_id の FK CASCADE で救われるので
// ここでは対象外でよい）。サイト単位の予約に紐づく行を無条件で全消しすることで、
// 「今回マッチしなかった」を含めて正しく反映する。
func (q *Queries) DeleteReservationRuleMatchesBySite(ctx context.Context, site string) error {
	_, err := q.db.Exec(ctx, deleteReservationRuleMatchesBySite, site)
	return err
}

const deleteReservationsBySiteAndProgramIDs = `-- name: DeleteReservationsBySiteAndProgramIDs :execrows

DELETE FROM reservations r
WHERE r.site = $1 AND r.program_id = ANY($2::bigint[])
  AND NOT EXISTS (
      SELECT 1 FROM program_investments v
      WHERE v.site = r.site AND v.program_id = r.program_id
  )
`

type DeleteReservationsBySiteAndProgramIDsParams struct {
	Site       string
	ProgramIds []int64
}

// UpsertReservationsFromRulerPass と InsertReservationRuleMatches は
// jsonb_to_recordset / unnest を使う集合演算 1 文で、sqlc の組み込みアナライザ
// （実 DB 接続なしのカタログ解析）がこれらの動的レコード型を解決できないため
// （`column "program_id" does not exist` / `function unnest(unknown, unknown)
// does not exist` で generate が失敗する）、rulequery パッケージの流儀に倣って
// internal/ruler/sql.go に生 SQL として置き、pgxpool 経由で直接実行する。
// ルール・program_intents のどちらからも desired でなくなった予約のうち、
// 「ルール x EPG」由来と区別できないものを削除する（導出削除。呼び出し側で
// サーキットブレーカーの閾値判定を先に行うこと）。明示操作からしか説明できない
// 削除は先に DeleteReleasedReservationsBySiteAndProgramIDs が処理済みで、
// ブレーカーの数にも入らない。
//
// toDelete は runPassForSite の先頭（トランザクション外）で ListProgramIntentActionsBySite /
// ListProgramInvestmentProgramIDsBySite / ListReservationProgramIDsBySite を読んでから
// 計算した集合で、この DELETE 文自体は別のトランザクション（tx）内で後から実行される。
// その間に api の PutProgramIntent（program_intents.action='record' をコミットする
// だけで、reservations には一切触れない）が同じ program_id に意図を立てると、
// toDelete は古い読み取りのままその番組を含んでしまい、意図が反映される直前だった
// 既存の予約行を削除してしまう（読み順を入れ替えても「計算してから DELETE を実行する
// までの窓」は必ず残るため、読み順の入れ替えでは直らない）。
//
// そこでガードを読み取り側ではなく DELETE 文自体の WHERE 句に持たせ、削除の瞬間に
// load-bearing な行の有無を再評価する（CLAUDE.md 不変条件 9「導出は読むたびに
// 評価する」を列だけでなく DELETE の対象判定にも適用する）。
// internal/db/queries/rules.sql の DeleteReservationsByRuleWithoutIntent と同じ形。
//
// 「この番組にユーザーの投資があるか」という述語は program_investments view
// （program_intents の action='record' 行 ∪ program_overrides の行）に一本化した
// （#162）。view は実行時にインライン展開されるため、ガードが「削除の瞬間に
// 再評価する」性質は変わらない。
func (q *Queries) DeleteReservationsBySiteAndProgramIDs(ctx context.Context, arg DeleteReservationsBySiteAndProgramIDsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReservationsBySiteAndProgramIDs, arg.Site, arg.ProgramIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listEnabledRules = `-- name: ListEnabledRules :many

SELECT id, name, description, enabled, priority, is_free, duration_min_ms, duration_max_ms, period_start_at, period_end_at, dedupe_enabled, dedupe_threshold, dedupe_window, keep_original, encode_profiles, filename_template, metadata, created_at, updated_at FROM rules WHERE enabled = true ORDER BY priority DESC, id ASC
`

// ruler（M2-3）が使う集合演算クエリ。
// 1 パスで全ルール x 全射影番組を評価し、差分だけを書く（docs/recording.md §3.1）。
// 予約 1 件ずつのループにしないため、書き込みは Postgres の集合演算 1 文にまとめる。
func (q *Queries) ListEnabledRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listEnabledRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Enabled,
			&i.Priority,
			&i.IsFree,
			&i.DurationMinMs,
			&i.DurationMaxMs,
			&i.PeriodStartAt,
			&i.PeriodEndAt,
			&i.DedupeEnabled,
			&i.DedupeThreshold,
			&i.DedupeWindow,
			&i.KeepOriginal,
			&i.EncodeProfiles,
			&i.FilenameTemplate,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpgProgramIDsBySiteAndProgramIDs = `-- name: ListEpgProgramIDsBySiteAndProgramIDs :many
SELECT program_id FROM epg_programs
WHERE site = $1 AND program_id = ANY($2::bigint[])
`

type ListEpgProgramIDsBySiteAndProgramIDsParams struct {
	Site       string
	ProgramIds []int64
}

// 削除候補（desired から外れた既存予約）のうち、EPG プロジェクションに
// まだ番組がある = ルールが「マッチしなくなった」と確信を持って判定できるものだけを
// 絞り込む。射影から番組ごと消えている場合はここに出てこず、呼び出し側は削除せず
// 凍結する（docs/schema.md「射影にある間は更新、消えたら凍結」を削除判定にも適用）。
func (q *Queries) ListEpgProgramIDsBySiteAndProgramIDs(ctx context.Context, arg ListEpgProgramIDsBySiteAndProgramIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listEpgProgramIDsBySiteAndProgramIDs, arg.Site, arg.ProgramIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var program_id int64
		if err := rows.Scan(&program_id); err != nil {
			return nil, err
		}
		items = append(items, program_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramIntentActionsBySite = `-- name: ListProgramIntentActionsBySite :many
SELECT program_id, action FROM program_intents WHERE site = $1
`

type ListProgramIntentActionsBySiteRow struct {
	ProgramID int64
	Action    string
}

// ruler は skip 意図の除外にだけこのクエリを使う。record 側（「この番組に
// ユーザーの投資があるか」の一部）は program_investments view に一本化した
// ため ListProgramInvestmentProgramIDsBySite（下記）から引く（#162）。
func (q *Queries) ListProgramIntentActionsBySite(ctx context.Context, site string) ([]ListProgramIntentActionsBySiteRow, error) {
	rows, err := q.db.Query(ctx, listProgramIntentActionsBySite, site)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProgramIntentActionsBySiteRow
	for rows.Next() {
		var i ListProgramIntentActionsBySiteRow
		if err := rows.Scan(&i.ProgramID, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramInvestmentProgramIDsBySite = `-- name: ListProgramInvestmentProgramIDsBySite :many
SELECT program_id FROM program_investments WHERE site = $1
`

// 「この番組にユーザーの投資があるか」（program_intents の action='record' 行 ∪
// program_overrides の行）は program_investments view（#162。
// internal/db/migrations/00027_program_investments_view.sql）に一本化した。
// ruler は record 意図の中身も overrides の中身も一切読まない（不透明な
// ペイロード）ため programId だけを引く（docs/recording.md §4.2「ruler から
// 見た load-bearing な行」: desired = (マッチ − skip) ∪ record ∪
// {program_overrides に行がある番組}）。
func (q *Queries) ListProgramInvestmentProgramIDsBySite(ctx context.Context, site string) ([]int64, error) {
	rows, err := q.db.Query(ctx, listProgramInvestmentProgramIDsBySite, site)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var program_id int64
		if err := rows.Scan(&program_id); err != nil {
			return nil, err
		}
		items = append(items, program_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramSnapshotProgramIDsBySiteAndProgramIDs = `-- name: ListProgramSnapshotProgramIDsBySiteAndProgramIDs :many

SELECT program_id FROM program_snapshots
WHERE site = $1 AND program_id = ANY($2::bigint[])
`

type ListProgramSnapshotProgramIDsBySiteAndProgramIDsParams struct {
	Site       string
	ProgramIds []int64
}

// 射影から program_snapshots への追従更新（#27）は
// internal/db/queries/program_snapshots.sql の UpsertProgramSnapshotsFromProjection
// 1 本にまとまった。ruler はそれを desiredIDs に対して呼ぶだけで、「射影にある間は
// 更新、消えたら凍結」を自分で判定しない（射影に無い programId は
// UpsertProgramSnapshotsFromProjection の JOIN にそもそも出てこないので、
// 何もせず既存の program_snapshots 行がそのまま凍結される）。
// 旧 ListProgramSnapshotsBySiteAndProgramIDs（epg_programs ⋈ epg_services を
// 直接引いて reservations 側の CASE で凍結を判定していたもの）は撤去した。
// 新規に reservations 行を作れるかどうかの判定に使う。program_snapshots への
// FK があるため、desired な programId のうち program_snapshots の行を持たない
// ものは予約行を作れない（射影にもなく、既存の意図・上書き・予約からも
// スナップショットが作られたことがない = 材料がどこにもない）。
func (q *Queries) ListProgramSnapshotProgramIDsBySiteAndProgramIDs(ctx context.Context, arg ListProgramSnapshotProgramIDsBySiteAndProgramIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listProgramSnapshotProgramIDsBySiteAndProgramIDs, arg.Site, arg.ProgramIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var program_id int64
		if err := rows.Scan(&program_id); err != nil {
			return nil, err
		}
		items = append(items, program_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationIDsBySiteAndProgramIDs = `-- name: ListReservationIDsBySiteAndProgramIDs :many
SELECT id, program_id FROM reservations
WHERE site = $1 AND program_id = ANY($2::bigint[])
`

type ListReservationIDsBySiteAndProgramIDsParams struct {
	Site       string
	ProgramIds []int64
}

type ListReservationIDsBySiteAndProgramIDsRow struct {
	ID        int64
	ProgramID int64
}

func (q *Queries) ListReservationIDsBySiteAndProgramIDs(ctx context.Context, arg ListReservationIDsBySiteAndProgramIDsParams) ([]ListReservationIDsBySiteAndProgramIDsRow, error) {
	rows, err := q.db.Query(ctx, listReservationIDsBySiteAndProgramIDs, arg.Site, arg.ProgramIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservationIDsBySiteAndProgramIDsRow
	for rows.Next() {
		var i ListReservationIDsBySiteAndProgramIDsRow
		if err := rows.Scan(&i.ID, &i.ProgramID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationProgramIDsBySite = `-- name: ListReservationProgramIDsBySite :many
SELECT program_id FROM reservations WHERE site = $1
`

func (q *Queries) ListReservationProgramIDsBySite(ctx context.Context, site string) ([]int64, error) {
	rows, err := q.db.Query(ctx, listReservationProgramIDsBySite, site)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var program_id int64
		if err := rows.Scan(&program_id); err != nil {
			return nil, err
		}
		items = append(items, program_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationTitlesBySiteAndProgramIDs = `-- name: ListReservationTitlesBySiteAndProgramIDs :many
SELECT program_id, title FROM program_snapshots
WHERE site = $1 AND program_id = ANY($2::bigint[])
`

type ListReservationTitlesBySiteAndProgramIDsParams struct {
	Site       string
	ProgramIds []int64
}

type ListReservationTitlesBySiteAndProgramIDsRow struct {
	ProgramID int64
	Title     string
}

// サーキットブレーカー（M2-5）発動時に breaker.Sample へ詰める「何を消そうとしていたか」の
// タイトルスナップショットを引く。programId だけでは手動確認する人間が判断できないため
// （breaker.SampleProgram.Title のコメント参照）。呼び出し側が対象を
// breaker.MaxSampleSize 程度に絞ってから呼ぶ想定なので、ここでは LIMIT を掛けない。
// title は program_snapshots に移設された（#27）。削除候補の programId は
// 呼び出し時点でまだ reservations 行を持つので、FK により program_snapshots の
// 行も必ず存在する（reservations との JOIN は不要）。
func (q *Queries) ListReservationTitlesBySiteAndProgramIDs(ctx context.Context, arg ListReservationTitlesBySiteAndProgramIDsParams) ([]ListReservationTitlesBySiteAndProgramIDsRow, error) {
	rows, err := q.db.Query(ctx, listReservationTitlesBySiteAndProgramIDs, arg.Site, arg.ProgramIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservationTitlesBySiteAndProgramIDsRow
	for rows.Next() {
		var i ListReservationTitlesBySiteAndProgramIDsRow
		if err := rows.Scan(&i.ProgramID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
