// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: start_delay.sql

package sqlcgen

import (
	"context"
)

const listStartedReservationIDs = `-- name: ListStartedReservationIDs :many
SELECT reservation_id FROM recordings
WHERE site = $1
  AND reservation_id = ANY($2::bigint[])
  AND started_at IS NOT NULL
`

type ListStartedReservationIDsParams struct {
	Site           string
	ReservationIds []int64
}

// 開始遅延検出器（issue #24 M2-7、docs/recording.md §3.3「開始遅延検出器」）。
//
// reconciler.detectStartDelays は listDesired が返した desired 予約
// （effective.skip 済み除外、never-scheduled 済み除外。issue #98 で
// state <> 'orphaned' から置き換わった）のうち「開始時刻 +
// 猶予 < now() < 終了時刻」の窓にある予約 ID をここに渡し、その中で
// recordings.started_at が埋まっている（= watcher が mirakc の record から
// 観測済み）予約 ID だけを引く。渡した ID からここで返った ID を除いた差集合が
// 「開始時刻を過ぎたのに録画開始が観測されていない」候補になる。
//
// recordings 行そのものが無い予約（録画がまだ一切観測されていない）は当然
// ここに出てこないので、呼び出し側では「返らなかった ID = 観測なし」として
// 扱えばよい（started_at が NULL の行がある場合と同じ扱いになる）。
func (q *Queries) ListStartedReservationIDs(ctx context.Context, arg ListStartedReservationIDsParams) ([]*int64, error) {
	rows, err := q.db.Query(ctx, listStartedReservationIDs, arg.Site, arg.ReservationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*int64
	for rows.Next() {
		var reservation_id *int64
		if err := rows.Scan(&reservation_id); err != nil {
			return nil, err
		}
		items = append(items, reservation_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
