// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: thumbnail_reconcile.sql

package sqlcgen

import (
	"context"
)

const listMissingThumbnailRecordings = `-- name: ListMissingThumbnailRecordings :many
SELECT o.recording_id
FROM media_assets o
JOIN recordings r ON r.id = o.recording_id
WHERE o.recording_id > $1::bigint
  AND o.kind = 'original'
  AND o.state = 'active'
  AND r.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM media_assets t
    WHERE t.recording_id = o.recording_id
      AND t.kind = 'thumbnail'
      AND t.state = 'active'
  )
  AND NOT EXISTS (
    SELECT 1 FROM missing_media_assets m
    WHERE m.media_asset_id = o.id
  )
ORDER BY o.recording_id
LIMIT $2
`

type ListMissingThumbnailRecordingsParams struct {
	AfterRecordingID int64
	RowLimit         int32
}

// thumbnail の desired（active original）− observed（active thumbnail）を
// 定期的に埋めるための候補。手動の EnqueueMissingThumbnails とは別のクエリに
// して、明示的な復旧投入が missing_media_assets のマーカーを迂回できるようにする。
//
// missing_media_assets に載っている原本は delete_reconcile が実体無しを確認した
// ものなので、ファイルが戻るまで定期パスからは除外する。マーカーが stale に
// なった場合は delete_reconcile が消し、次のパスで再び候補になる。
func (q *Queries) ListMissingThumbnailRecordings(ctx context.Context, arg ListMissingThumbnailRecordingsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listMissingThumbnailRecordings, arg.AfterRecordingID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var recording_id int64
		if err := rows.Scan(&recording_id); err != nil {
			return nil, err
		}
		items = append(items, recording_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
